- README.md
Il manquait un 'u' à structure.
> Correction d'une petite erreur typographique

- .gitignore
- docs/installation.md
Thought this could be helpful to document.
> Update installation documentation

- CONTRIBUTING.md
- README.md
- composer.json
- composer.lock
- docs/1. Installer le projet en local.md
- docs/2. Architecture du projet.md
- docs/3. Processus de développement.md
- docs/index.md
> Restructure documentation and add architecture documentation

- app/Resources/views/base.html.twig
- app/Resources/views/home/index.html.twig
- front/style/_cards.scss
- front/style/_layout.scss
- front/style/_text.scss
Je n'aime pas trop le hover sur les `cards`. À voir avec Thibault. Peut-être faudrait-il changer l'opacité au niveau de chaque carte? A discuter!
> RFR: Connect news with homepage template

- app/Resources/views/home/index.html.twig
- front/style/_buttons.scss
- front/style/_cards.scss
- front/style/_layout.scss
- front/style/_text.scss
- front/style/_vars.scss
- front/style/app.scss
Trés brouillon, mais techniquement responsive. Je continuerai demain.
> RFR: Adds mobile layout to homepage

- app/Resources/views/home/index.html.twig
- front/style/_layout.scss
Une PR minuscule pour reduire la largeur des news stories sur la home.
> RFR: Update width of stories on the homepage

- app/Resources/views/home/article.html.twig
- app/Resources/views/home/index.html.twig
- app/data/articles/2016-12-22-outre-mer-lun-piliers-de-richesse-culturelle/content.md
- front/style/_colors.scss
- front/style/_layout.scss
- front/style/_story.scss
- front/style/_text.scss
- front/style/app.scss
Un rapide layout pour commencer. Il manque le module de don, le module social media, et les grandes images. 
Progress on #37
> RFR: Add story page design

- app/Resources/views/base.html.twig
- app/Resources/views/home/article.html.twig
- app/Resources/views/home/index.html.twig
- docs/CSS-styleguide.md
- front/style/_article.scss
- front/style/_buttons.scss
- front/style/_cards.scss
- front/style/_colors.scss
- front/style/_forms.scss
- front/style/_story.scss
- front/style/_text.scss
- front/style/app.scss
Oui, alors je n'avais pas bien réglé mes options de Whitespace sur Atom. 🐙 Donc ca a retiré tous les trailing whitespaces sur quelques fichiers. Je viens d'ajuster cette option dans Atom, donc ca n'arrivera pas la prochaine fois. 
N'hesites pas si tu veux que je remette tous ces trailing whitespaces. 
Progress on #37
> RFR: Add social media icons to article template

- app/Resources/translations/validators.fr.yml
- app/Resources/views/home/index.html.twig
- app/Resources/views/newsletter/subscribed.html.twig
- app/Resources/views/newsletter/subscription.html.twig
- src/AppBundle/Controller/HomeController.php
- src/AppBundle/Controller/NewsletterController.php
- src/AppBundle/Entity/NewsletterSubscription.php
- src/AppBundle/Form/NewsletterSubscriptionType.php
- src/AppBundle/Repository/NewsletterSubscriptionRepository.php
- tests/AppBundle/Controller/NewsletterControllerTest.php
> Implement newsletter subscription

- app/Resources/views/base.html.twig
- app/Resources/views/home/index.html.twig
- front/style/_cards.scss
- front/style/_footer.scss
- front/style/_forms.scss
- front/style/_layout.scss
- front/style/_text.scss
- front/style/app.scss
Completes #40. Le code est un peu moche, j'aimerais bien faire un refactor la semaine prochaine.
> [RFR] Update homepage design

- app/Resources/views/home/index.html.twig
- front/style/_base.scss
- front/style/_buttons.scss
- front/style/_cards.scss
- front/style/_forms.scss
- front/style/_layout.scss
- front/style/_vars.scss
> [RFR] More homepage work

- app/Resources/views/base.html.twig
- app/Resources/views/home/index.html.twig
- front/style/_base.scss
- front/style/_forms.scss
- front/style/_layout.scss
- front/style/_text.scss
> [RFR] Fix visual bugs

- app/Resources/views/base.html.twig
- app/Resources/views/home/index.html.twig
- front/style/_base.scss
- front/style/_layout.scss
- front/style/_nav.scss
- front/style/_text.scss
- front/style/app.scss
> [RFR] Add mobile menu

- app/Resources/views/home/index.html.twig
- front/style/_cards.scss
- front/style/_layout.scss
> [RFR] Style the movement

- app/config/config.yml
wrong parameters for swiftmailer
> Fix swiftmailer parameters

- app/Resources/views/base.html.twig
- app/Resources/views/home/index.html.twig
- front/style/_cards.scss
- front/style/_colors.scss
- front/style/_donation.scss
- front/style/_layout.scss
- front/style/_vars.scss
> [RFR] Few tweaks on the homepage

- front/style/_cards.scss
> [RFR] Add smooth horizontal scrolling of the movement on iOS

- app/Resources/views/base.html.twig
- app/Resources/views/home/index.html.twig
- front/style/_cards.scss
J'attendrai que l'autre PR soit mergée. Ensuite je rebaserai et j'enleverai le premier commit ci-dessous.
> [RFR] Add social share btns

- app/Resources/views/base.html.twig
- app/Resources/views/home/article.html.twig
- app/Resources/views/home/index.html.twig
- front/components/DonationAmountChooser.js
Il y a une chose que je n'arrive pas à ajuster: je n'arrive pas a `tabber` sur les options de don (10 euros, 20 euros, etc). Bon, ça n'empêchera pas les gens de passer à la page suivante (et de donner), mais si tu as une idée, dis moi. :)
> [RFR] Enhance accessibility

- app/Resources/views/base.html.twig
- app/Resources/views/home/article.html.twig
- app/Resources/views/home/index.html.twig
- app/data/articles/2016-12-22-outre-mer-lun-piliers-de-richesse-culturelle/content.md
- app/data/articles/2016-12-22-outre-mer-lun-piliers-de-richesse-culturelle/metadata.yml
- docs/content-styleguide.md
- front/style/_article.scss
- front/style/_base.scss
- front/style/_cards.scss
- front/style/_colors.scss
- front/style/_donation.scss
- front/style/_layout.scss
- front/style/_text.scss
- src/AppBundle/Content/ArticleRepository.php
- src/AppBundle/Content/Model/Article.php
> [RFR] Article page work

- app/Resources/views/adherent/profile.html.twig
- app/Resources/views/base.html.twig
- app/Resources/views/events/index.html.twig
- app/Resources/views/security/adherent_login.html.twig
- app/config/security.yml
- front/style/_forms.scss
- src/AppBundle/Controller/AdherentController.php
- src/AppBundle/Controller/EventsController.php
- src/AppBundle/Controller/Security/AdherentSecurityController.php
- src/AppBundle/Form/LoginType.php
- src/AppBundle/Validator/CityAssociatedToPostalCodeValidator.php
- tests/AppBundle/Controller/AbstractControllerTest.php
- tests/AppBundle/Controller/AdherentControllerTest.php
- tests/AppBundle/Controller/EventsControllerTest.php
- tests/AppBundle/Controller/Security/AdherentSecurityControllerTest.php
Closes [EM-6](http://jira.sensiolabs.net/browse/EM-6).
Includes an empty "événements" page.
I've also created an extra "tools" container to install assets with Docker.
> Configured security for members login

- app/Resources/views/membership/register.html.twig
- front/components/MembershipAddressForm.js
- front/controllers/MembershipIndexAddress.js
- front/style/_colors.scss
- front/style/_forms.scss
- front/style/_register.scss
- front/style/app.scss
- tests/AppBundle/Controller/MembershipControllerTest.php
Closes [EM-9](http://jira.sensiolabs.net/browse/EM-9).
> Handled integration of registration page

- app/AppKernel.php
- app/Resources/views/admin/admin_qrcode.html.twig
- app/Resources/views/security/admin_google_authenticator.html.twig
- app/config/config.yml
- app/config/services/admin.xml
- app/config/services/security.xml
- composer.json
- composer.lock
- src/AppBundle/Admin/AdministratorAdmin.php
- src/AppBundle/Controller/Security/AdminSecurityController.php
- src/AppBundle/Entity/Administrator.php
- src/AppBundle/Security/TwoFactorAuthenticationQrCodeFactory.php
> Implement Two Factor Authentication for administrators

- app/config/security.yml
- app/config/services/admin.xml
- src/AppBundle/Admin/DonationAdmin.php
- src/AppBundle/Admin/NewsletterSubscriptionAdmin.php
- src/AppBundle/Entity/Donation.php
> Implement donation and newsletter administration

- docs/1. Installer le projet en local.md
Commandes permettant d'initialiser la base de données et de créer un compte utilisateur
> Documentation de l'init de la base de données

- app/Resources/views/form_theme.html.twig
- app/Resources/views/membership/pin_interests.html.twig
- app/config/adherent.yml
- app/config/config.yml
- app/config/config_test.yml
- app/config/services/membership.xml
- src/AppBundle/Controller/MembershipController.php
- src/AppBundle/Entity/Adherent.php
- src/AppBundle/Form/AdherentInterestsFormType.php
- src/AppBundle/Membership/MembershipUtils.php
- tests/AppBundle/Controller/MembershipControllerTest.php
Closes [EM-14](http://jira.sensiolabs.net/browse/EM-14).
> Handled interests step during adherent registration

- app/Resources/views/adherent/_profile_menu.html.twig
- app/Resources/views/adherent/change_password.html.twig
- app/Resources/views/adherent/layout.twig
- app/Resources/views/adherent/pin_interests.html.twig
- app/Resources/views/adherent/set_email_notifications.html.twig
- src/AppBundle/Controller/AdherentController.php
- tests/AppBundle/Controller/AdherentControllerTest.php
Closes [EM-20](http://jira.sensiolabs.net/browse/EM-20).
> Added adherent profile pages skeleton

- app/Resources/translations/messages.fr.yml
- app/Resources/views/adherent/_membership_form.html.twig
- app/Resources/views/adherent/profile.html.twig
- app/Resources/views/base.html.twig
- app/Resources/views/membership/register.html.twig
- app/config/config.yml
- app/config/services/address.xml
- app/config/services/membership.xml
- app/config/services/twig.xml
- front/app.js
- front/components/UpdateMembershipAddressForm.js
- front/controllers/UpdateMembershipIndexAddress.js
- src/AppBundle/Address/Address.php
- src/AppBundle/Controller/AdherentController.php
- src/AppBundle/Controller/MembershipController.php
- src/AppBundle/Entity/Adherent.php
- src/AppBundle/Entity/EntityPostAddressTrait.php
- src/AppBundle/Form/MembershipRequestType.php
- src/AppBundle/Form/UpdateMembershipRequestType.php
- src/AppBundle/Membership/AdherentFactory.php
- src/AppBundle/Membership/MembershipRequest.php
- src/AppBundle/Membership/MembershipRequestHandler.php
- src/AppBundle/Twig/AppIntlExtension.php
- tests/AppBundle/Controller/AdherentControllerTest.php
- tests/AppBundle/Controller/MembershipControllerTest.php
Closes [EM-21](http://jira.sensiolabs.net/browse/EM-21).
> Handled editing adherent profile

- app/Resources/translations/messages.fr.yml
- app/Resources/views/adherent/pin_interests.html.twig
- src/AppBundle/Controller/AdherentController.php
- src/AppBundle/Form/AdherentInterestsFormType.php
- tests/AppBundle/Controller/AdherentControllerTest.php
Closes [EM-22](http://jira.sensiolabs.net/browse/EM-22).
> Handled editing adherent interests

- app/Resources/translations/messages.fr.yml
- app/Resources/translations/validators.fr.yml
- app/Resources/views/adherent/change_password.html.twig
- app/config/services/membership.xml
- src/AppBundle/Controller/AdherentController.php
- src/AppBundle/Entity/Adherent.php
- src/AppBundle/Form/AdherentChangePasswordType.php
- src/AppBundle/Membership/AdherentChangePasswordHandler.php
- tests/AppBundle/Controller/AdherentControllerTest.php
Closes [EM-23](http://jira.sensiolabs.net/browse/EM-23).
> Handled adherent changing password

- app/Resources/translations/messages.fr.yml
- app/Resources/views/adherent/set_email_notifications.html.twig
- src/AppBundle/Controller/AdherentController.php
- src/AppBundle/Entity/Adherent.php
- src/AppBundle/Form/AdherentEmailSubscriptionType.php
- src/AppBundle/Membership/AdherentEmailSubscription.php
- tests/AppBundle/Controller/AdherentControllerTest.php
Closes [EM-24](http://jira.sensiolabs.net/browse/EM-24).
> Handled adherent's emails subscriptions

- app/Resources/views/committee/add_event.html.twig
- src/AppBundle/Committee/CommitteePermissions.php
- src/AppBundle/Committee/Voter/CreateCommitteeVoter.php
- src/AppBundle/Committee/Voter/HostCommitteeVoter.php
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Repository/CommitteeMembershipRepository.php
- tests/AppBundle/Committee/Voter/CreateCommitteeVoterTest.php
- tests/AppBundle/Committee/Voter/HostCommitteeVoterTest.php
- tests/AppBundle/Repository/CommitteeMembershipRepositoryTest.php
Closes [EM-42](http://jira.sensiolabs.net/browse/EM-42).
> Added controller and template skeletons for the add event page.

- app/Resources/views/committee/add_event.html.twig
- app/Resources/views/committee/hosts.html.twig
- app/config/services/committee.xml
- src/AppBundle/Committee/CommitteeManager.php
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Entity/Adherent.php
- src/AppBundle/Entity/CommitteeMembership.php
- src/AppBundle/Repository/AdherentRepository.php
- src/AppBundle/Repository/CommitteeMembershipRepository.php
- tests/AppBundle/Committee/CommitteeManagerTest.php
- tests/AppBundle/Entity/AdherentTest.php
Closes [EM-44](http://jira.sensiolabs.net/secure/RapidBoard.jspa?rapidView=39&projectKey=EM&view=detail&selectedIssue=EM-44).
> Added committee hosts blocks in the add event pages.

- app/Resources/translations/messages.fr.yml
- app/Resources/views/committee/show.html.twig
- app/config/services/committee.xml
- src/AppBundle/Committee/CommitteeManager.php
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Entity/Committee.php
- src/AppBundle/Twig/CommitteeExtension.php
- tests/AppBundle/Committee/CommitteeManagerTest.php
- tests/AppBundle/Controller/CommitteeControllerTest.php
Closes [EM-40](http://jira.sensiolabs.net/browse/EM-40).
> Handled committee page

- app/Resources/views/committee/show.html.twig
- app/config/services/committee.xml
- src/AppBundle/Committee/Voter/ShowCommitteeVoter.php
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Entity/Adherent.php
- src/AppBundle/Twig/CommitteeExtension.php
- tests/AppBundle/Committee/Voter/AbstractCommitteeVoterTest.php
- tests/AppBundle/Committee/Voter/ShowCommitteeVoterTest.php
- tests/AppBundle/Controller/CommitteeControllerTest.php
Closes [EM-32](http://jira.sensiolabs.net/browse/EM-32).
> Handled committee page blocks per authorization

- app/Resources/translations/validators.fr.yml
- app/config/services/committee.xml
- src/AppBundle/Committee/CommitteeFeedHandler.php
- src/AppBundle/Committee/Feed/CommitteeMessage.php
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Entity/CommitteeFeedItem.php
- src/AppBundle/Entity/CommitteeFeedMessage.php
- tests/AppBundle/Committee/CommitteeFeedHandlerTest.php
- tests/AppBundle/TestHelperTrait.php
Closes [EM-46](http://jira.sensiolabs.net/browse/EM-46).
> Added a CommitteeFeedMessage entity

- app/Resources/views/search/committees.html.twig
- app/Resources/views/search/layout.html.twig
- src/AppBundle/Controller/SearchController.php
- tests/AppBundle/Controller/SearchControllerTest.php
Closes [EM-49](http://jira.sensiolabs.net/browse/EM-49).
> Implements the search controller and view

- app/Resources/translations/messages.fr.yml
- app/Resources/views/committee/show.html.twig
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Form/CommitteeFeedMessageType.php
- tests/AppBundle/Controller/CommitteeControllerTest.php
Closes [EM-47](http://jira.sensiolabs.net/browse/EM-47).
> Handled host creating committee message

- app/config/config.yml
- app/config/services/asset.xml
- src/AppBundle/Asset/GoogleMapsStaticProvider.php
- src/AppBundle/Controller/AssetsController.php
- tests/AppBundle/Controller/AssetsControllerTest.php
- tests/AppBundle/Controller/ControllerTestTrait.php
Closes [EM-41](http://jira.sensiolabs.net/browse/EM-41).
> Implements the static maps delivery

- app/AppKernel.php
- app/config/config.yml
- app/config/config_dev.yml
- app/config/config_prod.yml
- app/config/services/cache.xml
- app/config/services/geocoder.xml
- app/config/services/media.xml
- composer.json
- composer.lock
- docker-compose.yml
This reverts commit 479ffabd73fb31759b254c6135a1947d11e19d8c as the Docker build is broken. To be investigatd more.
> Revert "Wire Redis for cache and sessions (#201)"

- app/Resources/views/search/committees.html.twig
- app/Resources/views/search/events.html.twig
- app/Resources/views/search/layout.html.twig
- app/config/config.yml
- app/config/services/doctrine.xml
- app/config/services/search.xml
- src/AppBundle/Committee/Event/CommitteeEventFactory.php
- src/AppBundle/Controller/SearchController.php
- src/AppBundle/DataFixtures/ORM/LoadCommitteeEventData.php
- src/AppBundle/Search/SearchParametersFilter.php
- src/AppBundle/Search/SearchResultsProvider.php
- tests/AppBundle/Controller/SearchControllerTest.php
Closes [EM-52](http://jira.sensiolabs.net/browse/EM-52).
> Provides data to display committees and events in the search

- app/AppKernel.php
- app/config/config.yml
- app/config/config_dev.yml
- app/config/config_prod.yml
- app/config/services/cache.xml
- app/config/services/geocoder.xml
- app/config/services/media.xml
- composer.lock
- prod.dockerfile
> Wire Redis for cache and sessions

- app/Resources/views/security/adherent_login.html.twig
- app/Resources/views/security/admin_login.html.twig
- front/style/_buttons.scss
- front/style/_forms.scss
- front/style/_layout.scss
- tests/AppBundle/Controller/Security/AdherentSecurityControllerTest.php
- tests/AppBundle/Controller/Security/AdminSecurityControllerTest.php
J'ai fait des petites modifications au niveau de la copie aussi. À valider bien sur! 🙌
> Improve the ui of the login form

- front/app.js
- front/listeners/external-links.js
> Implement opening of external links in new windows (66)

- app/Resources/translations/messages.fr.yml
- app/Resources/views/adherent/create_committee.html.twig
- app/Resources/views/committee/_form.html.twig
- app/Resources/views/committee/edit.html.twig
- app/Resources/views/committee/show.html.twig
- app/config/services/committee.xml
- src/AppBundle/Committee/CommitteeCommand.php
- src/AppBundle/Committee/CommitteeCreationCommand.php
- src/AppBundle/Committee/CommitteeUpdateCommandHandler.php
- src/AppBundle/Controller/AdherentController.php
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Entity/Committee.php
- src/AppBundle/Form/CommitteeCommandType.php
- src/AppBundle/Form/CreateCommitteeCommandType.php
- src/AppBundle/Validator/UniqueCommitteeValidator.php
- tests/AppBundle/Controller/AdherentControllerTest.php
- tests/AppBundle/Controller/CommitteeControllerTest.php
> Edit committee information

- app/Resources/views/committee/show.html.twig
- app/config/config.yml
- src/AppBundle/Asset/GoogleMapsStaticProvider.php
- src/AppBundle/Geocoder/DummyGeocoder.php
- tests/AppBundle/Controller/AssetsControllerTest.php
> Improves the static maps feature

- app/Resources/views/events/show.html.twig
- app/config/config.yml
- src/AppBundle/Committee/Event/CommitteeEventFactory.php
- src/AppBundle/Controller/CommitteeEventController.php
- src/AppBundle/DataFixtures/ORM/LoadCommitteeEventData.php
- src/AppBundle/Entity/CommitteeEvent.php
- src/AppBundle/Repository/CommitteeEventRepository.php
- tests/AppBundle/Controller/CommitteeControllerTest.php
> Implemented event details page.

- app/Resources/views/committee/members.html.twig
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Entity/Adherent.php
- src/AppBundle/Repository/CommitteeMembershipRepository.php
Closes [EM-60](http://jira.sensiolabs.net/browse/EM-60).
> Display the members list for a committee

- app/Resources/views/committee/show.html.twig
- app/Resources/views/committee/timeline/_event.html.twig
- app/Resources/views/committee/timeline/_message.html.twig
- app/Resources/views/committee/timeline/feed.html.twig
- src/AppBundle/Committee/Feed/CommitteeFeedManager.php
- src/AppBundle/DataFixtures/ORM/LoadAdherentData.php
- src/AppBundle/DataFixtures/ORM/LoadCommitteeEventData.php
- src/AppBundle/Entity/Committee.php
- src/AppBundle/Mailjet/Message/CommitteeMessageNotificationMessage.php
- src/AppBundle/Repository/CommitteeEventRepository.php
- src/AppBundle/Repository/CommitteeFeedItemRepository.php
- tests/AppBundle/Controller/CommitteeControllerTest.php
> Hide committee timeline message body for non authenticated users.

- app/Resources/views/committee/members.html.twig
- src/AppBundle/Committee/CommitteeManager.php
- src/AppBundle/Committee/CommitteeUtils.php
- src/AppBundle/Committee/Serializer/AdherentCsvSerializer.php
- src/AppBundle/Controller/CommitteeController.php
Closes [EM-61](http://jira.sensiolabs.net/browse/EM-61).
> Implements the members list export for a committee

- app/Resources/views/events/_event_header.html.twig
- app/Resources/views/events/attend.html.twig
- app/Resources/views/events/attend_confirmation.html.twig
- app/Resources/views/events/show.html.twig
- src/AppBundle/Controller/CommitteeEventController.php
> Implemented controllers and views skeletons for committee event registration.

- app/Resources/translations/messages.fr.yml
- app/Resources/views/committee/timeline/_event.html.twig
- app/Resources/views/events/attend.html.twig
- app/Resources/views/events/show.html.twig
- app/config/services/committee.xml
- app/config/services/doctrine.xml
- src/AppBundle/Committee/Event/CommitteeEventRegistrationCommand.php
- src/AppBundle/Committee/Event/CommitteeEventRegistrationCommandHandler.php
- src/AppBundle/Committee/Event/CommitteeEventRegistrationFactory.php
- src/AppBundle/Committee/Event/CommitteeEventRegistrationManager.php
- src/AppBundle/Controller/CommitteeEventController.php
- src/AppBundle/Entity/CommitteeEvent.php
- src/AppBundle/Entity/CommitteeEventRegistration.php
- src/AppBundle/Form/CommitteeEventRegistrationType.php
- src/AppBundle/Repository/CommitteeEventRegistrationRepository.php
> Implemented committee event registration.

- app/Resources/views/form_theme.html.twig
- app/Resources/views/membership/choose_nearby_committee.html.twig
- app/Resources/views/membership/complete.html.twig
- src/AppBundle/Controller/MembershipController.php
- tests/AppBundle/Controller/MembershipControllerTest.php
Closes [EM-57](http://jira.sensiolabs.net/browse/EM-57).
> Implements the landing page after user registration

- app/Resources/translations/messages.fr.yml
- app/Resources/views/committee/contact.html.twig
- app/Resources/views/committee/members.html.twig
- app/config/services/committee.xml
- src/AppBundle/Committee/CommitteeContactMembersCommand.php
- src/AppBundle/Committee/CommitteeContactMembersCommandHandler.php
- src/AppBundle/Committee/CommitteeUtils.php
- src/AppBundle/Controller/CommitteeController.php
- src/AppBundle/Form/ContactMembersType.php
- src/AppBundle/Mailjet/Message/CommitteeContactMembersMessage.php
- src/AppBundle/Repository/CommitteeMembershipRepository.php
Closes [EM-67](http://jira.sensiolabs.net/browse/EM-67).
> Implements the contact members feature for a committee

- app/Resources/views/search/search.html.twig
- app/config/services/membership.xml
- src/AppBundle/Committee/CommitteeManager.php
- src/AppBundle/Controller/Admin/AdminAdherentController.php
- src/AppBundle/Controller/MembershipController.php
- src/AppBundle/Membership/AdherentAccountActivationHandler.php
- src/AppBundle/Membership/AdherentManager.php
- src/AppBundle/Security/AuthenticationUtils.php
- tests/AppBundle/Controller/MembershipControllerTest.php
This PR must be merged after #278 has been merged.
> Auto authenticate adherent when he\she completes his\her account activation

- src/AppBundle/Entity/MailjetEmail.php
- src/AppBundle/Mailjet/EventSubscriber/MailjetEmailDoctrineBackupEventSubscriber.php
- src/AppBundle/Mailjet/MailjetTemplateEmail.php
- src/AppBundle/Mailjet/MailjetUtils.php
- src/AppBundle/Mailjet/Message/MailjetMessage.php
- src/AppBundle/Repository/MailjetEmailRepository.php
- tests/AppBundle/Mailjet/EventSubscriber/MailjetEmailDoctrineBackupEventSubscriberTest.php
Database schema must be updated and fixtures must be reloaded on the staging server.
> Closes issue #284.

- app/Resources/translations/messages.fr.yml
- app/Resources/translations/validators.fr.yml
- app/Resources/views/referent/users/list.html.twig
- app/Resources/views/referent/users/message-selected.html.twig
- app/config/services/referent.xml
- front/pages/referent_users.js
- front/style/_forms.scss
- front/style/_referent.scss
- src/AppBundle/Controller/ReferentController.php
- src/AppBundle/Form/ReferentMessageType.php
- src/AppBundle/Mailjet/Message/AdherentAccountActivationMessage.php
- src/AppBundle/Mailjet/Message/AdherentAccountConfirmationMessage.php
- src/AppBundle/Mailjet/Message/AdherentResetPasswordMessage.php
- src/AppBundle/Mailjet/Message/CommitteeApprovalConfirmationMessage.php
- src/AppBundle/Mailjet/Message/CommitteeContactMembersMessage.php
- src/AppBundle/Mailjet/Message/CommitteeCreationConfirmationMessage.php
- src/AppBundle/Mailjet/Message/CommitteeEventNotificationMessage.php
- src/AppBundle/Mailjet/Message/CommitteeMessageNotificationMessage.php
- src/AppBundle/Mailjet/Message/DonationMessage.php
- src/AppBundle/Mailjet/Message/InvitationMessage.php
- src/AppBundle/Mailjet/Message/MailjetMessage.php
- src/AppBundle/Mailjet/Message/ReferentMessage.php
- src/AppBundle/Referent/ManagedUser.php
- src/AppBundle/Referent/ManagedUserExporter.php
- src/AppBundle/Referent/ManagedUserFactory.php
- src/AppBundle/Referent/ReferentMessage.php
- src/AppBundle/Referent/ReferentMessageFactory.php
- src/AppBundle/Referent/ReferentMessageHandler.php
- tests/AppBundle/Controller/ReferentControllerTest.php
> Implement message sending from the referent area for selected users	

- app/Resources/views/committee/contact.html.twig
- app/Resources/views/committee/show.html.twig
> Add text to explain mail copy on committees

- app/Resources/views/committee/timeline/_event.html.twig
- app/Resources/views/committee/timeline/_message.html.twig
- app/Resources/views/events/show.html.twig
- front/style/_committee.scss
- front/style/_text.scss
@ngrilly I created a new PR (somehow wasn't able to just add work to your fork, or PR into it).
This closes the PR #581 and fixes #521.
> Ngrilly 521 fix list css

- Makefile
- app/config/config_test_mysql.yml
- app/config/parameters.yml.dist
- docker-compose.override.yml.dist
- docker-compose.yml
- docker/dev/Dockerfile
- docker/dev/supervisord.conf
- tests/bootstrap.php
```
$ make
start:           Install and start the project
stop:            Remove docker containers
reset:           Reset the whole project
db:              Reset the database and load fixtures
:---------------------------------------------------------------------------:
new-migration:   Generate a migration by comparing your current database to your mapping information.
watch:           Watch the assets and build their development version on change
clear:           Remove all the cache, the logs, the sessions and the built assets
clean:           Clear and remove dependencies
:---------------------------------------------------------------------------:
test:            Run the PHP and the Javascript tests
tu:              Run the PHP unit tests
tf:              Run the PHP functional …
```
> rewrite makefile & docker-compose

- app/Resources/views/procuration_manager/request.html.twig
- src/AppBundle/Entity/ProcurationRequest.php
- src/AppBundle/Mailjet/Message/ProcurationProxyFoundMessage.php
- src/AppBundle/Mailjet/Message/ProcurationProxyReminderMessage.php
- tests/AppBundle/Controller/ProcurationManagerControllerTest.php
- tests/AppBundle/Procuration/ProcurationProxyMessageFactoryTest.php
Can't use it in [`app/Resources/views/procuration_manager/_requests_list.html.twig`](https://github.com/EnMarche/en-marche.fr/blob/master/app/Resources/views/procuration_manager/_requests_list.html.twig#L22-L36) since it is an array.
> add elections dates in producration mails

- src/AppBundle/Repository/ProcurationProxyRepository.php
- src/AppBundle/Repository/ProcurationRequestRepository.php
- src/AppBundle/Search/ProcurationParametersFilter.php
Based on https://github.com/EnMarche/en-marche.fr/pull/881#discussion_r111247876
> clean procuration filter

- app/config/config_test.yml
- app/config/parameters.yml.dist
- app/config/routing.yml
- src/AppBundle/Controller/Legislatives/CandidateController.php
- src/AppBundle/Controller/Legislatives/HomeController.php
- src/AppBundle/Controller/Legislatives/MapController.php
> Added controllers for legislatives website

- app/Resources/views/admin/committee_members.html.twig
- src/AppBundle/Controller/Admin/AdminCommitteeController.php
- src/AppBundle/Exception/CommitteeMembershipException.php
> add flash message on committee page

- src/AppBundle/Committee/CommitteeManager.php
- tests/AppBundle/Committee/CommitteeManagerTest.php
https://sentry.io/en-marche-i7/en-marchefr/issues/258922798/
> Fixes Sentry issue #258922798.

- src/AppBundle/Entity/Committee.php
https://sentry.io/en-marche-i7/en-marchefr/issues/226663790/
> Fixes Sentry issue #226663790

- src/AppBundle/Entity/Event.php
- src/AppBundle/Event/EventCommand.php
- tests/AppBundle/Controller/CommitteeControllerTest.php
https://sentry.io/en-marche-i7/en-marchefr/issues/256049124/
> Fixes Sentry issue #256049124.

- src/AppBundle/Mailjet/Message/CommitteeNewFollowerMessage.php
https://sentry.io/en-marche-i7/en-marchefr/issues/239916469/
https://sentry.io/en-marche-i7/en-marchefr/issues/229385444/
> Fixes sentry issues #239916469 & #229385444

- app/data/circonscriptions.csv
- src/AppBundle/Admin/LegislativeCandidateAdmin.php
- src/AppBundle/Admin/LegislativeDistrictZoneAdmin.php
- src/AppBundle/Command/LegislativesLoadDistrictZonesCommand.php
- src/AppBundle/DataFixtures/ORM/LoadLegislativesData.php
- src/AppBundle/Entity/LegislativeDistrictZone.php
- src/AppBundle/Repository/LegislativeCandidateRepository.php
- src/AppBundle/Repository/LegislativeDistrictZoneRepository.php
- tests/AppBundle/Entity/LegislativeDistrictZoneTest.php
https://sentry.io/en-marche-i7/stagingen-marchefr/issues/259291665/
> Fixes Sentry issue #259291665.

- app/Resources/views/components/newsletter_footer.html.twig
- app/Resources/views/home/index.html.twig
- app/Resources/views/procuration/_layout.html.twig
- front/listeners/algolia-search.js
- front/style/_search-global.scss
* Fix algolia bug
* Add new homepage video
* Remove blocking footer on procuration pages
> Various small things

- app/Resources/translations/messages.fr.yml
- app/Resources/views/ton_macron/_fill_info.html.twig
- app/Resources/views/ton_macron/_fill_interests.html.twig
- app/Resources/views/ton_macron/_fill_project.html.twig
- src/AppBundle/Form/TonMacronInvitationType.php
This reverts commit 07cd850abe161fc51fb23d2845eb8bf80168a2e4.
> Revert "Update TonMacron for the second round"

- front/components/AlgoliaSearch.js
- src/AppBundle/Command/AlgoliaSynchronizeCommand.php
- src/AppBundle/Entity/EntityCrudTrait.php
- src/AppBundle/Entity/Event.php
https://sentry.io/en-marche-i7/en-marchefr/issues/260843273/
> fix search & events with algolia

- app/Resources/translations/validators.fr.yml
- app/Resources/views/adherent/_membership_form.html.twig
- src/AppBundle/Form/DataTransformer/FloatToStringTransformer.php
- src/AppBundle/Form/DonationRequestType.php
- tests/AppBundle/Controller/MembershipControllerTest.php
- tests/AppBundle/Form/DataTransformer/FloatToStringTransformerTest.php
https://sentry.io/en-marche-i7/en-marchefr/issues/268887245/
> fix donate

- src/AppBundle/Address/Address.php
https://sentry.io/en-marche-i7/en-marchefr/issues/268897125/
> fix profile form

- src/AppBundle/Entity/ManagedArea.php
https://sentry.io/en-marche-i7/en-marchefr/issues/270630570/
> fix admin adherent

- app/Resources/views/base.html.twig
Probably useless but, hey, it's class 🤓
> Updated schema

- docs/1-Installer-le-projet-en-local.md
> Add domain config to the local install doc + remove broken slack link

- src/AppBundle/Form/ContactMessageType.php
Fix https://sentry.io/en-marche-i7/en-marchefr/issues/282296237/
> Fix incorrect string value in committee feed item

- app/config/services/system.xml
- src/Logging/CurrentUserProcessor.php
Replaces https://github.com/EnMarche/en-marche.fr/pull/1105.
> Used a service locator for CurrentUserProccessor

- app/Resources/views/base.html.twig
When copy/paste text from a microsoft software, the quots are not simple quot.
> Remove Microsoft Word characters

- docker/prod/php.ini
See https://github.com/symfony/symfony/pull/23091
> Enable APCu in CLI to create a proper cache on warmup

- src/Validator/UniqueMembershipValidator.php
https://sentry.io/en-marche-i7/en-marchefr/issues/294592520/
> Fix unique email validator

- templates/admin/committee/list_actions.html.twig
- templates/admin/committee/list_status.html.twig
- templates/admin/committee/show.html.twig
- templates/admin/event/list_actions.html.twig
- templates/admin/event/list_status.html.twig
https://sentry.io/en-marche-i7/stagingen-marchefr/issues/299829974/
> Fix admin booleans

- templates/adherent/events.html.twig
Closes [#667](https://app.clubhouse.io/enmarche/story/667/ic-page-d-affichage-des-%C3%A9v%C3%A9nements-donner-une-couleur-diff%C3%A9rente-aux-ic-pour-les-distinguer-des-%C3%A9v%C3%A9nements-d-al)
> Highlight IC events

- app/migrations/Version20170731164115.php
- app/migrations/Version20170905110626.php
- src/Admin/CitizenInitiativeAskingHelpAdmin.php
- src/CitizenInitiative/CitizenInitiativeCommand.php
- src/DataFixtures/ORM/LoadCitizenInitiativeCategoryData.php
- src/DataFixtures/ORM/LoadCitizenInitiativeData.php
- src/Entity/CitizenInitiative.php
- src/Event/EventFactory.php
- src/Form/CitizenInitiativeType.php
- templates/citizen_initiative/add.html.twig
- templates/citizen_initiative/expert_assistance.html.twig
- tests/Controller/EnMarche/CitizenInitiativeControllerTest.php
- tests/Controller/EnMarche/CitizenInitiativeManagerControllerTest.php
@illusionOfParadise You'll see, I broke everything ;)
I tried to make the backend changes but couldn't resolve the db issue. I'm guessing a change has to be made somewhere in the db itself? Wondering if you or Remi could help me (and I'd love to learn).
> Copy updates on the IC

- tests/Controller/EnMarche/CitizenInitiativeControllerTest.php
Test suite broke after 7f68ff71b59c75df7e0f9ce64e8a76057e6f5a80, tests need theses changes
> Fixed event tests button label

- templates/amp/_layout.html.twig
I'm really not sure if what I did was right, almost sent it back to you @illusionOfParadise and @Remg, but thought I'd try. 
Here is the [card for reference](https://app.clubhouse.io/enmarche/story/539/tag-gtm-sur-pages-amp).
> Update analytics on AMP pages

- app/migrations/Version20170929155932.php
- src/DataFixtures/ORM/LoadAdherentData.php
- src/DataFixtures/ORM/LoadReferentManagedUserData.php
- src/Entity/Projection/ReferentManagedUser.php
- src/Entity/Projection/ReferentManagedUserFactory.php
- src/Referent/ManagedUsersFilter.php
- src/Repository/Projection/ReferentManagedUserRepository.php
- templates/referent/users_list.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
> [REFERENT] Create 2 filters (hosts and supervisors) instead of one 'hosts'

- src/Admin/AdherentAdmin.php
https://app.clubhouse.io/enmarche/story/1175/admin-territoires-adhérents-dans-editer-supprimer-la-rubrique-candidat-aux-législatives
> BO - Drop field candidate for the legislative elections

- src/DataFixtures/ORM/LoadEventData.php
- templates/events/_event_header.html.twig
- tests/Controller/EnMarche/EventControllerTest.php
- tests/Controller/EnMarche/MapControllerTest.php
- tests/Repository/EventRepositoryTest.php
Work in progress
To do : tests
> Issue #1507 Event title with special chars in Google calendar

- src/Admin/ArticleAdmin.php
- src/Admin/ClarificationAdmin.php
- src/Admin/OrderArticleAdmin.php
- src/Admin/PageAdmin.php
- src/Admin/ProposalAdmin.php
- src/Command/BuildAmpContentCommand.php
- src/Command/ImportBoardMemberCommand.php
- src/Command/ImportReferentNominationCommand.php
- src/Command/LegislativesLoadDistrictZonesCommand.php
- src/Consumer/ReferentMessageDispatcherConsumer.php
- src/Controller/EnMarche/AdherentController.php
- src/DataFixtures/ORM/LoadEventData.php
- src/Entity/Adherent.php
- src/Entity/ArticleCategory.php
- src/Entity/BaseEvent.php
- src/Entity/Donation.php
- src/Entity/MailjetEmail.php
- src/Entity/ReferentArea.php
- src/Mailjet/Message/CommitteeCitizenInitiativeNotificationMessage.php
- src/Mailjet/Message/CommitteeContactMembersMessage.php
- src/Mailjet/Message/CommitteeMessageNotificationMessage.php
- src/Repository/TonMacronChoiceRepository.php
- src/Storage/FilesystemAdapterFactory.php
- src/Twig/AssetRuntime.php
- var/SymfonyRequirements.php
https://styleci.readme.io/docs/change-log#section-28102017-october-updates
> Fix new styleci presets

- circle.yml
https://circleci.com/docs/1.0/build-image-trusty/#php
> Fix circleci php version

- composer.lock
- src/Entity/AdherentActivationToken.php
- src/Entity/TonMacronChoice.php
- src/Entity/TonMacronFriendInvitation.php
```
[Symfony\Component\Debug\Exception\UndefinedMethodException]                                                                      
Attempted to call an undefined method named "getCustomTemplate" of class "Doctrine\DBAL\Migrations\Configuration\Configuration". 
```
=> https://github.com/doctrine/DoctrineMigrationsBundle/issues/207#issuecomment-341052916
```
Package operations: 0 installs, 1 update, 0 removals
- Updating doctrine/doctrine-migrations-bundle (v1.3.0 => v1.3.1): Downloading (100%)  
```
> Entities should not be final & update doctrine-migrations-bundle

- composer.lock
```
Package operations: 0 installs, 14 updates, 0 removals
- Updating symfony/symfony (v3.3.10 => v3.3.13): Downloading (100%)         
- Updating doctrine/doctrine-bundle (1.7.2 => 1.8.0): Downloading (100%)         
- Updating symfony/monolog-bundle (v3.1.1 => v3.1.2): Downloading (100%)         
- Updating sentry/sentry (1.8.0 => 1.8.1): Downloading (100%)         
- Updating ramsey/uuid-doctrine (1.4.1 => 1.4.3): Downloading (100%)         
- Updating sonata-project/core-bundle (3.5.1 => 3.6.0): Downloading (100%)         
- Updating php-amqplib/rabbitmq-bundle (v1.13.0 => v1.14.0): Downloading (100%)         
- Updating doctrine/migrations (v1.5.0 => v1.6.0): Downloading (100%)         
- Updating giggsey/locale (1.3 => 1.4): Downloading (100%)         
- Updating …
```
> Update dependencies - fix security:check

- src/Entity/BaseSkill.php
- src/Entity/Skill.php
- src/Entity/SkillTrait.php
This `BaseSkill` abstract class will be also used by the `CitizenProjectSkill` entity.
> Refacto Skill Entity

- app/config/config.yml
- app/config/routing.yml
- app/config/security.yml
- app/config/services/system.xml
- src/Security/LogoutSuccessHandler.php
- templates/components/_dropdown_user_desktop.html.twig
- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
- tests/Security/LogoutSuccessHandlerTest.php
Link to https://github.com/EnMarche/auth.en-marche.fr/pull/169
> [1954] Logout redirect to auth

- app/config/services/admin.xml
- app/migrations/Version20171217185611.php
- src/Admin/CitizenProjectAdmin.php
- src/Admin/CitizenProjectDatagrid.php
- src/CitizenProject/CitizenProjectCommand.php
- src/CitizenProject/CitizenProjectManager.php
- src/Controller/Admin/AdminCitizenProjectController.php
- src/DataFixtures/ORM/LoadCitizenProjectData.php
- src/Entity/CitizenProject.php
- src/Form/CitizenProjectCommandType.php
- src/Repository/CitizenActionRepository.php
- src/Repository/CitizenProjectRepository.php
- templates/adherent/create_citizen_project.html.twig
- templates/admin/citizen_project/list_creator.html.twig
- templates/admin/citizen_project/list_name.html.twig
- templates/admin/citizen_project/list_next_citizen_action.html.twig
- templates/admin/citizen_project/list_status.html.twig
- templates/admin/citizen_project/members.html.twig
- templates/citizen_project/_form.html.twig
- templates/citizen_project/_sidebar.html.twig
- templates/citizen_project/edit.html.twig
- tests/CitizenProject/CitizenProjectManagerTest.php
- tests/Controller/EnMarche/CitizenActionManagerControllerTest.php
CP admin:
- add `featured` tag
- add `matchedSkills` tag
- add `adminComment` editable text
- change columns & filters on list view
CP front:
- add counter on `assistance_content` field
- change `phone` field place
> [CP] Admin & form UI

- src/CitizenInitiative/Voter/OrganizerCitizenInitiativeVoter.php
- src/CitizenProject/Voter/CreateCitizenProjectVoter.php
- src/Committee/Voter/CreateCommitteeVoter.php
- src/Membership/Voter/MembershipVoter.php
- tests/CitizenProject/Voter/CreateCitizenProjectVoterTest.php
- tests/Committee/Voter/CreateCommitteeVoterTest.php
This PR updates voters by extending the `Voter` class instead of implementing directly `VoterInterface`.
> Refactoring Voters

- README.md
- composer.json
- composer.lock
Symfony recently introduced https://github.com/symfony/thanks, a Composer plugin to say thanks in the form of Github stars to open-source projects used in your project. I think this is a great way to promote the great packages we used in this project :) .
> Add thanks command to the project and README

- composer.lock
- src/Controller/Api/StatsController.php
- src/Controller/EnMarche/MapController.php
- src/Repository/AdherentRepository.php
- src/Repository/CommitteeRepository.php
- src/Repository/EventRepository.php
- tests/Repository/EventRepositoryTest.php
**Update Symfony 3.3.13 to Symfony 3.3.14 :**
https://github.com/symfony/symfony/releases/tag/v3.3.14
**Package operations: 1 install, 42 updates, 1 removal :**
>  - Removing jms-serializer/serializer (1.3.3)
>   - Updating ocramius/package-versions (1.1.3 => 1.2.0): Downloading (100%)         
>   - Updating symfony/symfony (v3.3.13 => v3.3.14): Downloading (100%)         
>   - Updating doctrine/annotations (v1.5.0 => v1.6.0): Downloading (100%)         
>   - Updating doctrine/dbal (v2.6.2 => v2.6.3): Downloading (100%)         
>   - Updating doctrine/doctrine-bundle (1.8.0 => 1.8.1): Downloading (100%)         
>   - Updating sentry/sentry (1.8.1 => 1.8.2): Downloading (100%)         
>   - Updating stof/doctrine-extensions-bundle (v1.2.2 => v1.3.0): Downloading (100%)         
>   - …
> Updated Symfony 3.3.13 to 3.3.14 and all dependencies

- templates/base.html.twig
To avoid problems with bots including facebook
> Fix close tag on meta referrer

- Dockerfile
- app/AppKernel.php
- app/config/config.yml
- composer.json
- composer.lock
- docker/dev/Dockerfile
- front/style/pages/_committee.scss
- src/Controller/EnMarche/EventManagerController.php
- src/Controller/PrintControllerTrait.php
- src/Event/EventRegistrationExporter.php
- src/Form/EventRegistrationType.php
- templates/base_print.html.twig
- templates/events/_member_list.html.twig
- templates/events/members.html.twig
- templates/events/print_members.html.twig
- tests/Controller/EnMarche/EventManagerControllerTest.php
- web/css/print.css
It's the same PR as https://github.com/EnMarche/en-marche.fr/pull/2024 which was not merged on master
> Add event registration list print 

- app/config/services/services.xml
basically replace tabs by spaces in this file.
> Fix services.xml indentation

- features/bootstrap/SecurityContext.php
- features/oauth.feature
- src/Controller/OAuth/OAuthServerController.php
- tests/Entity/OAuth/AccessTokenTest.php
403 them if they try to use OAuth
> Admin should not use OAuth

- src/Entity/Adherent.php
- src/Membership/AdherentFactory.php
- tests/Entity/AdherentTest.php
Same as https://github.com/EnMarche/en-marche.fr/pull/2077 but with the good target branche
> [2550] Disabled CP subscription radius if com email is disabled

- app/config/services/system.xml
- src/Form/CommitteeCommandType.php
- src/Form/TypeExtension/PhoneNumberTypeExtension.php
- templates/adherent/create_committee.html.twig
- templates/citizen_project/show_base.html.twig
- templates/committee/show.html.twig
- tests/Controller/EnMarche/AdherentControllerTest.php
- translations/messages.fr.yml
The country by default on the committee form will be taken from local in another PR.
> Change wording and add default phone number country on the committee page

- templates/admin/citizen_project/list_actions.html.twig
- templates/admin/committee/list_actions.html.twig
These bad titles made functional tests behavior pretty weird \o/
> [ADMIN] Fix members link title

- src/CitizenProject/CitizenProjectManager.php
- src/Controller/EnMarche/CitizenProjectController.php
- src/Repository/CitizenProjectCommitteeSupportRepository.php
- tests/Controller/EnMarche/CitizenProjectControllerTest.php
**TODO** : Update and add some tests to coverage added and deleted supports.
> Ensure the right committee (un)supports a citizen project

- front/style/mixins/_text.scss
- templates/citizen_project/_layout.html.twig
- templates/committee/show.html.twig
- tests/Controller/EnMarche/CitizenProjectControllerTest.php
- tests/Controller/EnMarche/CommitteeControllerTest.php
- Update button message to subscribe to CP
- Update button message to subscribe to committee
> Simple user can subscripbe to CP

- src/Entity/Committee.php
- src/Form/CommitteeCommandType.php
- fix display description in committee when there are apostrophe
- fix description edition in BO
> Fix some problemes with committee description

- app/migrations/Version20180206104452.php
- src/Admin/ArticleCategoryAdmin.php
- src/DataFixtures/ORM/LoadArticleData.php
- src/Entity/ArticleCategory.php
- templates/article/article.html.twig
- tests/Admin/ArticleCategoryAdminTest.php
- tests/Controller/ControllerTestTrait.php
- tests/Controller/EnMarche/ArticleControllerTest.php
- add fields (ctaLink ctaLabel) in categories to display it at the end of each article in the category
- add database test creation in makefile on db rule to run test through phpstorm easily
> CTA in articles categories to display in article

- templates/citizen_project/_form.html.twig
- add some examples in citizen project form
> [ch2673] Add some examples in citizen project form

- src/Entity/CitizenProject.php
https://sentry.io/en-marche-i7/en-marchefr/issues/454817374/
> Bugfix - Assistance text is optional

- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
https://app.clubhouse.io/enmarche/story/2735/rajouter-comit%C3%A9s-dans-la-navigation-entre-evenements-et-projets-citoyens
> [ch2735] Add link "Comités" in nav bar

- src/Twig/AdherentExtension.php
- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
https://app.clubhouse.io/enmarche/story/2781/etq-que-utilisateur-ou-animateur-sur-mobile-je-me-vois-referent-la-classe
> Hotfix - user level should be consistent between mobile and desktop

- features/oauth.feature
- src/OAuth/Store/ClientStore.php
https://sentry.io/en-marche-i7/en-marchefr/issues/460183490/
> Bugfix - Malformed Client Id for OAuth should 401

- tests/Admin/ArticleCategoryAdminTest.php
- tests/Committee/CommitteeManagementAuthorityTest.php
This PR fixes the group annotation and the `make tu` command test suite.
> Fixed functional group

- app/config/services/services.xml
- src/Command/FixTitleCaseCommand.php
- src/Doctrine/DBAL/BatchedConnection.php
- tests/Doctrine/DBAL/BatchedConnectionTest.php
https://app.clubhouse.io/enmarche/story/2751/command-to-fix-title-case
> Add command 'app:fix-title-case' to fix some text case

- composer.json
- composer.lock
following this issue -> https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3536
> Downgrade php-cs-fixer

- app/config/services/admin.xml
- src/Admin/CommitteeAdmin.php
- src/Entity/PostAddress.php
- add setter in PostAddress.
- Add fields in admin form
- Dispatch event for committee update to update geocod
https://app.clubhouse.io/enmarche/story/2793/admin-territoires-comit%C3%A9-pouvoir-modifier-le-code-postal-ville-pays-d-un-comit%C3%A9-valid%C3%A9
> [ch2793] Make possible to change committee address in admin.

- front/app.js
- front/pages/citizen_project_image_generator.js
- front/style/pages/_image-generator.scss
- templates/citizen_project/media_generator_tract_form.html.twig
- templates/form_theme.html.twig
https://app.clubhouse.io/enmarche/story/2796/feedback-about-image-maker-tool
> adds preview of file uploads to projets citoyens

- app/config/config.yml
- app/config/services/services.xml
- app/config/services/system.xml
- src/Admin/ArticleAdmin.php
- src/DataFixtures/ORM/LoadArticleData.php
- src/DataFixtures/ORM/LoadOrderArticleData.php
- src/Entity/Article.php
- src/Entity/Redirection.php
- src/EntityListener/ArticleListener.php
- src/EntityListener/RedirectionListener.php
- src/Redirection/Dynamic/RedirectToAdminPanelHandler.php
- src/Redirection/Dynamic/RedirectionManager.php
- src/Repository/RedirectionRepository.php
- tests/Admin/ArticleAdminTest.php
- tests/Redirection/Dynamic/RedirectionManagerTest.php
- Creation of doctrine listener to handle all object modifications
- Creation of Redirection Manager to handle redirect with cache for performances
- add some test to trigger and test redirection
https://app.clubhouse.io/enmarche/story/2705/pouvoir-modifier-les-url-des-articles-apr%C3%A8s-publication
> [ch2705] Dynamic modification of articles URL after publications.

- src/Admin/CitizenProjectAdmin.php
- src/Entity/CitizenProject.php
- src/Entity/CitizenProjectCommitteeSupport.php
- templates/admin/citizen_project/list_committee_supports.html.twig
For the Citizen Project Admin list view :
- Added category filter
- Updated export fields
- Fix a bug in the committee supports template (added getter for status property)
> CP Admin : Added category filter and updated export fields

- templates/citizen_project/media_generator.html.twig
- templates/citizen_project/media_generator_image_form.html.twig
> Fix wording

- tests/Controller/EnMarche/EventManagerControllerTest.php
> Remove debug statement

- templates/citizen_project/_layout.html.twig
- templates/citizen_project/show_base.html.twig
- change h1 to h2 and h2 to h1
https://app.clubhouse.io/enmarche/story/2612/modifier-le-h1-sur-les-pages-projets-citoyens
> [ch2612] Seo optimisation

- app/migrations/Version20180219104140.php
- src/Admin/CitizenActionCategoryAdmin.php
- src/Admin/CitizenProjectCategoryAdmin.php
- src/Admin/EventCategoryAdmin.php
- src/Controller/EnMarche/SearchController.php
- src/Entity/BaseEventCategory.php
- src/Entity/CitizenActionCategory.php
- src/Entity/CitizenProjectCategory.php
- src/Entity/EventCategory.php
- templates/search/_filters.html.twig
- tests/Controller/EnMarche/SearchControllerTest.php
https://app.clubhouse.io/enmarche/story/2846/on-aimerait-pouvoir-faire-ca-https-en-marche-fr-evenements-category-grandemarche
> Add pre-selected category filter from URL on the events page

- src/Committee/Feed/CommitteeFeedManager.php
- src/Committee/Feed/CommitteeMessage.php
- src/Form/CommitteeFeedItemMessageType.php
- src/Form/CommitteeFeedMessageType.php
- templates/committee/_form_theme.html.twig
- templates/committee/_host_header.html.twig
- tests/Committee/Feed/CommitteeFeedManagerTest.php
- Add checkbox in committee form and validation
https://app.clubhouse.io/enmarche/story/2849/sur-la-page-d-envoi-de-message-pour-les-comit%C3%A9s-je-veux-rajouter-un-checkbox-pour-l-envoi-de-mails
> [ch2849] Add checkbox to send notification to followers

- src/Entity/Adherent.php
- src/Form/EventListener/CoordinatorManagedAreaListener.php
https://app.clubhouse.io/enmarche/story/2672/etq-admin-si-je-mets-une-zone-r%C3%A9f%C3%A9rent-a-un-adh%C3%A9rent-qui-est-d%C3%A9j%C3%A0-coordinateur-son-r%C3%B4le-coordinateur-saute
> [ADMIN][ch2672] Fix disappearing of coordinator managed area while Adherent edition

- front/style/pages/_committee.scss
- templates/committee/_layout.html.twig
- templates/committee/demote_host.html.twig
- templates/committee/promote_host.html.twig
- templates/committee_manager/list_members.html.twig
https://app.clubhouse.io/enmarche/story/2848/int%C3%A9grer-une-balise-h1-sur-toutes-les-pages-de-comit%C3%A9s
> [ch2848] Change h2 to h1 and move svg outside h1

- templates/events/show.html.twig
https://app.clubhouse.io/enmarche/story/2618/modification-des-meta-description-des-%C3%A9v%C3%A9nements
> [ch2618] Modify meta-description for events

- src/Form/WebHookType.php
It does not bring anything in the context of an OAuth client
> Delete client dropbox input from webhook admin

- src/CitizenProject/CitizenProjectAuthority.php
- src/CitizenProject/CitizenProjectManager.php
- src/Controller/Admin/AdminCitizenProjectController.php
- src/Entity/CitizenProjectMembership.php
- src/Repository/CitizenProjectMembershipRepository.php
- templates/admin/citizen_project/members.html.twig
- Implementation of changePrivilege method
- Remove organisator transformation button
https://app.clubhouse.io/enmarche/story/2787/pc-etq-admin-je-dois-pouvoir-changer-un-organisateur-en-follower-et-et-un-follower-en-organisateur
> [ch2787] Finish implementation of switching follower to organisator.

- templates/article/actualites.html.twig
> [SEO] Add GTM on article filters

- templates/components/_footer.html.twig
https://app.clubhouse.io/enmarche/story/2946/footer-remplacer-nos-offres-par-nos-offres-d-emploi
> Change 'Nos offres' to 'Nos offres d'emploi' in the footer

- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
https://app.clubhouse.io/enmarche/story/2928/etq-membre-du-conseil-je-ne-veux-plus-voir-le-lien-espace-membre-du-conseil-dans-la-navigation\#activity\=2994
> Hide Board member space link

- src/Controller/EnMarche/ProcurationManagerController.php
- src/DataFixtures/ORM/LoadAdherentData.php
- src/DataFixtures/ORM/LoadProcurationData.php
- src/Procuration/Filter/ProcurationFilters.php
- src/Repository/ElectionRoundRepository.php
- templates/procuration_manager/_filters.html.twig
- tests/Controller/EnMarche/ProcurationControllerTest.php
- tests/Controller/EnMarche/ProcurationManagerControllerTest.php
https://app.clubhouse.io/enmarche/story/2470/procuration-etq-respo-procuration-d-une-%C3%A9lection-sur-le-filtre-tour-concern%C3%A9-je-ne-veux-voir-appara%C3%AEtre-que-les-tours-de
> [PROCURATION][ch2470] Show only datas concerning upcoming elections

- app/config/services/cms.xml
- features/sitemap.feature
- src/Command/ImportReferentBioPictureCommand.php
- src/Command/ImportReferentNominationCommand.php
- src/Controller/Amp/AmpController.php
- src/Controller/EnMarche/HomeController.php
- src/DataFixtures/ORM/LoadArticleData.php
- src/DataFixtures/ORM/LoadCustomSearchData.php
- src/DataFixtures/ORM/LoadHomeBlockData.php
- src/DataFixtures/ORM/LoadLiveLinkData.php
- src/DataFixtures/ORM/LoadOrderArticleData.php
- src/DataFixtures/ORM/LoadPageData.php
- src/DataFixtures/ORM/LoadProposalData.php
- src/DataFixtures/ORM/LoadSocialShareData.php
- src/Exception/SitemapException.php
- src/Sitemap/SitemapFactory.php
- tests/Controller/EnMarche/HomeControllerTest.php
- tests/Sitemap/SitemapFactoryTest.php
- Remove videos site maps
- Create an exception on empty data to put in sitemap
- Catch SitemapException to redirect 301 to sitemap_index
https://app.clubhouse.io/enmarche/story/1701/correction-des-erreurs-dans-les-sitemaps
> [ch1701] Sitemap error fix

- app/config/services/admin.xml
- features/admin/adherent.feature
- features/registration.feature
- src/Admin/AdherentAdmin.php
https://app.clubhouse.io/enmarche/story/2990/une-modification-de-l-user-sur-l-admin-n-entraine-pas-une-modification-du-user-sur-l-api
> Update of Adherent with Admin must trigger RabbitMQ events

- src/CitizenAction/CitizenActionManager.php
- src/CitizenAction/CitizenActionParticipantsExporter.php
https://app.clubhouse.io/enmarche/story/2857/pc-dans-l-export-xls-je-veux-rajouter-la-colonne-d%C3%A9partement-avec-juste-les-2-premiers-chiffres-du-genre-59
> [CA] Add department to CA participants csv export

- templates/javascript.js.twig
https://app.clubhouse.io/enmarche/story/3023/hotfix-ramener-la-fonctionnalite-qui-permet-d-ajouter-une-image-dans-les-mails-de-referent-et-d-al-sorry-olga
> Add Image button to CKEditor

- front/components/AmountChooser.js
- src/Form/DonationRequestType.php
Revert mensual donation [ch2794]
Paybox production config problem
(revert commit 1b89a2ab2e761c0274446058c4960c2e4d37950b)
https://app.clubhouse.io/enmarche/story/2794/pouvoir-visualiser-le-don-mensuel-sur-develop-pour-voir-ce-qu-il-reste-%C3%A0-faire-sur-le-don
> [ch2794] revert activation mensual donation

- docker-compose.override.yml.dist
- src/Repository/CommitteeMembershipRepository.php
- templates/admin/committee/list_hosts.html.twig
- tests/Controller/EnMarche/CommitteeManagerControllerTest.php
- change order by adding privilege order first
- upgrade makefile to use dorkerize for waiting mysql up
https://app.clubhouse.io/enmarche/story/2223/admin-territoires-comit%C3%A9s-bug-d-affichage-de-l-ordre-des-al-puis-co-al
> [ch2223] AL CoAl Order display change to by privilege first

- src/CitizenAction/CitizenActionManager.php
- src/CitizenAction/CitizenActionParticipantsExporter.php
This reverts commit 128b68e3be6fa6f5736e0010cd5cee2e2b781a0e.
> Revert "[CA] Add department to CA participants csv export"

- app/migrations/Version20180308143058.php
- features/article_not_displayed.feature
- features/sitemap.feature
- src/Admin/ArticleAdmin.php
- src/Admin/ArticleCategoryAdmin.php
- src/Controller/EnMarche/ArticleController.php
- src/DataFixtures/ORM/LoadArticleData.php
- src/Entity/ArticleCategory.php
- src/Repository/ArticleRepository.php
- tests/Command/AlgoliaSynchronizeCommandTest.php
https://app.clubhouse.io/enmarche/story/3109/etq-qu-editor-je-veux-creer-une-categorie-d-article-qui-ne-s-affiche-pas-sur-la-page-d-actualit%C3%A9s-et-dont-les-articles-ne
> [ch3109] Have an option to not display an category and all articles linked

- front/pages/citizen_project_image_generator.js
- templates/citizen_project/cover_image.html.twig
- templates/citizen_project/media_generator_tract_form.html.twig
- templates/citizen_project/tract_pdf.html.twig
- tests/Controller/EnMarche/CitizenProjectMediaGeneratorControllerTest.php
https://app.clubhouse.io/enmarche/story/3096/quelques-modifications-sur-l-outil
>  [ch3096] Media generator modification

- templates/committee/_form.html.twig
https://app.clubhouse.io/enmarche/story/2951/formulaire-de-cr%C3%A9ation-de-comit%C3%A9-wording-%C3%A0-changer
> [ch2951] Wording change in committee creation form

- front/app.js
- front/pages/grande_marche_europe.js
- front/style/app.scss
- front/style/mixins/_colors.scss
- front/style/pages/_grande-marche-europe.scss
- src/Controller/EnMarche/PageController.php
- templates/page/grande-marche-europe/grande-marche-europe.html.twig
https://app.clubhouse.io/enmarche/story/2873/create-la-grande-marche-de-l-europe-landing-page
> Create landing grande marche de l europe

- front/services/api/ReqwestApiClient.js
- front/style/pages/_search.scss
- src/Controller/EnMarche/SearchController.php
- src/Repository/CitizenProjectRepository.php
- src/Repository/CitizenProjectSkillRepository.php
- src/Search/SearchParametersFilter.php
- templates/search/_filters_radius.html.twig
- templates/search/_filters_radius_citizen_projects.html.twig
- templates/search/search.html.twig
- tests/Controller/EnMarche/SearchControllerTest.php
This reverts commit 88e4fb3773387da0710fffe63f8a7ad6c416e659, reversing
changes made to f682316e28291ef6f673e728b7c97e2a4ef118d1.
https://app.clubhouse.io/enmarche/story/3184/revert-https-app-clubhouse-io-enmarche-story-2077-page-recherche-des-pc-https-staging-en-marche-fr-projets-citoyens-permettre
> Revert "Merge pull request #1939 from EnMarche/ch2077/cp-skills-search"

- app/config/routing.yml
- features/oauth.feature
- features/redirect.feature
- features/registration.feature
- src/Controller/EnMarche/MembershipController.php
- src/Redirection/LegacyRedirectionsSubscriber.php
- tests/Controller/EnMarche/MembershipControllerTest.php
- tests/Controller/RedirectingControllerTest.php
https://app.clubhouse.io/enmarche/story/3188/transf%C3%A9rer-le-contenu-de-inscription-vers-inscription-utilisateur-pour-permettre-ensuite-une-redirection-301-de-inscription
>  [ch3188] Redirect old registration to adhesion with 301

- app/config/security.yml
- app/config/services/services.xml
- features/registration.feature
- src/Controller/EnMarche/Security/SecurityController.php
- src/DataFixtures/ORM/LoadUserData.php
- src/Exception/AccountNotValidatedException.php
- src/Repository/AdherentRepository.php
- src/Security/UserChecker.php
- templates/security/adherent_login.html.twig
- tests/Controller/EnMarche/AdherentControllerTest.php
- tests/Controller/EnMarche/Security/AdherentSecurityControllerTest.php
- tests/Controller/EnMarche/Security/AdminSecurityControllerTest.php
- tests/Repository/AdherentRepositoryTest.php
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/3176/mettre-un-message-d-erreur-avec-proposition-de-renvoi-d-e-mail-lorsqu-un-nouvel-adh%C3%A9rent-n-a-pas-valid%C3%A9-son-adresse-mail
> [ch3176] Resend email validation and notify the user to check his mailbox

- templates/TwigBundle/Exception/error404.html.twig
• Add Home Button 
• Add Header
• Add Footer
> improve 404

- templates/referent/_layout.html.twig
https://app.clubhouse.io/enmarche/story/3206/ajouter-un-lien-dans-l-espace-r%C3%A9f%C3%A9rent
> [ch3206] Add a lien in referent space

- app/config/config.yml
- app/config/services/system.xml
- src/Consumer/AbstractConsumer.php
- src/Consumer/MailerConsumer.php
- src/Mailer/Message/Message.php
- tests/Consumer/AbstractConsumerTest.php
- tests/Consumer/AbstractMailerConsumerTest.php
- tests/Consumer/MailerConsumerTest.php
- tests/Consumer/ProjectCitizenCreationNotificationConsumerTest.php
- tests/Consumer/ReferentMessageDispatcherConsumerTest.php
> Add Mailer consumer for scheduled mails

- front/style/layout/_base.scss
- templates/events/_header.html.twig
https://app.clubhouse.io/enmarche/story/2291/comit%C3%A9s-evenements-je-veux-ajouter-le-formulaire-de-signalement-comme-sur-les-pc-ac
> [ch2291] Fix button position in event page

- app/migrations/Version20180314145201.php
- front/style/layout/_buttons.scss
- src/Entity/Adherent.php
- src/Membership/AdherentEmailSubscription.php
- templates/user/set_email_notifications.html.twig
- tests/Controller/EnMarche/AdherentControllerTest.php
- translations/messages.fr.yml
Add a few visual and language tweaks to the notification page
Add a canary
https://app.clubhouse.io/enmarche/story/3011/am%C3%A9liorations-de-la-gestion-des-notifications
> [ch3011] Fix button visual and text and Canary part of the feature

- front/style/layout/_buttons.scss
Remove !important on .btn--small
> remove important

- front/components/AmountChooser.js
- src/Form/DonationRequestType.php
https://app.clubhouse.io/enmarche/story/2794/pouvoir-visualiser-le-don-mensuel-sur-develop-pour-voir-ce-qu-il-reste-%C3%A0-faire-sur-le-don
> [ch2794] Active mensual donnation

- features/registration.feature
- front/style/mixins/_text.scss
- front/style/pages/_join.scss
- templates/membership/join.html.twig
https://app.clubhouse.io/enmarche/story/3324/modifier-les-messages-d-erreur-sur-la-page-d-adh%C3%A9sion
> [ch3324] Modify errors message in adhesion page.

- Makefile
This PR removes duplicated targets and adds colors for the `help` target.
> Makefile : Added colors and removed duplicated targets

- app/config/services/admin.xml
- features/referent-organizational-chart.feature
- src/Admin/OrganizationalChartItemAdmin.php
- src/Admin/ReferentAdmin.php
- src/Entity/ReferentOrganizationalChart/GroupOrganizationalChartItem.php
- src/Entity/ReferentOrganizationalChart/PersonOrganizationalChartItem.php
- src/Exporter/ReferentPersonLinkExport.php
- src/Form/ReferentPersonLinkType.php
- templates/admin/referent/export_team_xlsx_button.html.twig
- templates/referent/_layout.html.twig
- templates/referent/organizational_chart.html.twig
- translations/SonataAdminBundle.fr.yml
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/3212/cr%C3%A9er-dans-l-espace-r%C3%A9f%C3%A9rent-une-nouvelle-tab-%C3%A9quipe-d%C3%A9partementale-qui-pr%C3%A9sentera-l-organigramme
> [ch3212] Some wording change about organizational chart PR

- src/Entity/ReferentOrganizationalChart/PersonOrganizationalChartItem.php
- src/Form/ReferentPersonLinkType.php
- templates/admin/organizational_chart/admin_list.html.twig
- templates/referent/edit_referent_person_link.html.twig
- templates/referent/organizational_chart_macros.html.twig
- translations/SonataAdminBundle.fr.yml
- translations/messages.fr.yml
- web/css/organizational_chart.css
https://app.clubhouse.io/enmarche/story/3212/cr%C3%A9er-dans-l-espace-r%C3%A9f%C3%A9rent-une-nouvelle-tab-%C3%A9quipe-d%C3%A9partementale-qui-pr%C3%A9sentera-l-organigramme
> [ch3212] fix display + wording + link admin

- src/Sitemap/SitemapFactory.php
Indexed pages were missing in the sitemap.
This PR adds registration pages and inviation pages for events.
> Sitemap : Added invitation and event registration pages

- app/config/services/repositories.xml
- features/user_controller_donation.feature
- front/style/pages/_profile.scss
- src/Controller/EnMarche/UserController.php
- src/DataFixtures/ORM/LoadDonationData.php
- src/Entity/Donation.php
- src/Repository/DonationRepository.php
- templates/adherent/_profile_menu.html.twig
- templates/user/my_donation.html.twig
A user:
- from everywhere can click on "mes dons" in "mon compte"
- can see his donation in a table recap with following fields (date, amount, paiements mode)
- can see since when have done his latest donation
- have a CTA for a new monthly or unique donation
https://app.clubhouse.io/enmarche/story/2834/etq-utilisateur-adh%C3%A9rent-je-veux-avoir-acc%C3%A8s-%C3%A0-un-onglet-mes-dons-sur-mon-compte
> WIP: [ch2834] A user can see his own donation

- Makefile
Example usage : `BEHAT_ARGS=--tags=wip make behat`
> Makefile : Added Behat args

- src/Admin/CitizenActionAdmin.php
- src/Admin/EventAdmin.php
> [Admin] Fix choice labels

- features/api/adherents.feature
- src/Controller/Api/AdherentsController.php
- src/Repository/AdherentRepository.php
https://app.clubhouse.io/enmarche/story/3634/1%C3%A8re-partie-section-adh%C3%A9rents-box-kpis-adh%C3%A9rents-managed-area-name
> Create endpoint for managed adherent count + by gender

- src/Membership/MembershipRequestHandler.php
I highly recommend to refactor `AppBundle\Membership\MembershipRequestHandler` asap.
We don't allow simple registration anymore.
> Assign tags on adherent registration

- src/Entity/Adherent.php
avoid to store 3km of data in session for user who will be re selected from DB on the second request:
<details>
[2018-04-20 18:11:58] snc_redis.INFO: Executing command "SET sessiona5qrajpnjqrrjcsktsinov7ran _sf2_attributes|a:5:{s:18:"_csrf/authenticate";s:43:"r2T9VXp6w5UwehdC4bmAHD7xWKXOBPGHnxW6nl9psdI";s:22:"_security_main_context";s:9571:"C:74:"Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken":9482:{a:3:{i:0;N;i:1;s:4:"main";i:2;s:9441:"a:4:{i:0;O:25:"AppBundle\Entity\Adherent":34:{s:35:"AppBundle\Entity\Adherentpassword";s:60:"$2y$13$7kJdjxadGBYHBBlq4CoOter60n20AWa1RyyIAJh7iFqiS./G2GvaG";s:38:"AppBundle\Entity\AdherentoldPassword";N;s:33:"AppBundle\Entity\Adherentgender";s:4:"male";s:39:"AppBundle\Entity\AdherentemailAddress";s:25:"referent@en-marche-dev.fr";s: …
> Limit User serialized data

- templates/base.html.twig
- templates/committee/show.html.twig
- templates/referent/users_message.html.twig
https://app.clubhouse.io/enmarche/story/4049/bug-le-compteur-de-caract%C3%A8res-qui-buggue
> Include jQuery in head block for some page with char counter

- app/config/services/services.xml
- front/app.js
- front/pages/board_member_list.js
- front/pages/donation_informations.js
- front/pages/join.js
- front/pages/registration.js
- front/validator/formValidator.js
- src/Controller/Api/FormController.php
- src/Controller/EnMarche/DonationController.php
- src/Donation/DonationRequestUtils.php
- src/Exception/InvalidPayboxPaymentSubscriptionValueException.php
- src/Form/AdherentRegistrationType.php
- src/Form/AdherentType.php
- src/Form/DonationRequestType.php
- src/Form/TypeExtension/FormTypeExtension.php
- templates/donation/informations.html.twig
- templates/form_theme.html.twig
- templates/membership/join.html.twig
- templates/membership/register.html.twig
- tests/Controller/Api/FormControllerTest.php
- tests/Controller/EnMarche/DonationControllerTest.php
- create a route api to dynamicly validate form send
- create js to hand any form and display errors
https://app.clubhouse.io/enmarche/story/3092/int%C3%A9grer-l-instant-field-validation-sur-les-formulaires-de-don-et-d-adh%C3%A9sion
> [ch3092] Create an instant validation for multiple form

- front/style/mixins/_text.scss
- front/style/pages/_citizen-projects.scss
Reverts EnMarche/en-marche.fr#2385
> Revert "Charles/improve citizen project"

- app/config/services/community.xml
- app/config/services/services.xml
- app/migrations/Version20180418150006.php
- features/user_controller_donation.feature
- src/Controller/EnMarche/DonationController.php
- src/Controller/EnMarche/UserController.php
- src/Controller/OAuth/OAuthServerController.php
- src/DataFixtures/ORM/LoadDonationData.php
- src/Donation/DonationRequestUtils.php
- src/Donation/PayboxFormFactory.php
- src/Donation/PayboxPaymentUnsubscription.php
- src/Donation/PayboxPaymentUnsubscriptionErrorEnum.php
- src/Entity/Donation.php
- src/Exception/PayboxPaymentUnsubscriptionException.php
- src/Form/ConfirmActionType.php
- src/Mailer/Message/PayboxPaymentUnsubscriptionConfirmationMessage.php
- src/Repository/DonationRepository.php
- templates/base.html.twig
- templates/user/donation_subscription_cancel_confirmation.html.twig
- templates/user/my_donation.html.twig
- tests/Controller/EnMarche/DonationControllerTest.php
- tests/Donation/PayboxPaymentUnsubscriptionTest.php
- tests/Entity/DonationTest.php
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/3088/mettre-une-option-de-d%C3%A9sengagement-du-don-mensuel-sur-l-onglet-mes-dons-du-profil
> [ch3088] Donation Unsubscription

- .gitignore
- app/config/services/community.xml
- app/config/services/platform.xml
- app/config/services/repositories.xml
- app/config/services/services.xml
- features/donation.feature
- features/user_controller_donation.feature
- front/components/AmountChooser.js
- src/Controller/EnMarche/DonationController.php
- src/DataFixtures/ORM/LoadDonationData.php
- src/Donation/DonationRequest.php
- src/Donation/DonationRequestUtils.php
- src/Donation/PayboxPaymentUnsubscription.php
- src/Entity/PostAddress.php
- src/Form/TypeExtension/FormTypeExtension.php
- src/Repository/DonationRepository.php
- src/Validator/UniqueDonationSubscription.php
- src/Validator/UniqueDonationSubscriptionValidator.php
- templates/donation/informations.html.twig
- templates/form_theme.html.twig
- translations/validators.fr.yml
https://app.clubhouse.io/enmarche/story/3751/emp%C3%AAcher-les-personnes-qui-font-d%C3%A9j%C3%A0-un-don-mensuel-d-en-faire-un-second
> [ch3751] Don t allow user to donate multiple monthly donations

- app/migrations/Version20180502192812.php
- src/Entity/UserDocument.php
`application/vnd.openxmlformats-officedocument.presentationml.presentation`
> Increase length of mimetype column

- app/config/services/platform.xml
- app/config/services/services.xml
- features/bootstrap/FeatureContext.php
- features/registration.feature
- front/style/layout/_buttons.scss
- src/Committee/CommitteeManager.php
- src/Controller/EnMarche/DonationController.php
- src/Controller/EnMarche/MembershipController.php
- src/Donation/DonationRequestUtils.php
- src/Entity/PostAddress.php
- src/Form/CommitteeAroundAdherentType.php
- src/Form/DonationRequestType.php
- src/Geocoder/CoordinatesFactory.php
- src/Membership/MembershipRegistrationPermissions.php
- src/Membership/MembershipRegistrationProcess.php
- src/Membership/MembershipRequestHandler.php
- src/Repository/CommitteeRepository.php
- src/Security/Voter/MembershipRegistrationVoter.php
- templates/donation/result.html.twig
- templates/form_theme.html.twig
- templates/membership/choose_committees.html.twig
- templates/membership/donation.html.twig
- tests/Controller/EnMarche/DonationControllerTest.php
- tests/Security/Voter/MembershipRegistrationVoterTest.php
This PR adds 3 new steps during the registration process :
> Added new steps during the registration process : interests, committees and donations

- app/config/services/services.xml
- front/style/layout/_forms.scss
- src/CitizenAction/CitizenActionCommand.php
- src/Event/EventCommand.php
- src/Form/BaseEventCommandType.php
- src/Validator/DateRange.php
- src/Validator/DateRangeValidator.php
- templates/citizen_action_manager/_layout.html.twig
- templates/committee_manager/add_event.html.twig
- tests/Validator/DateRangeValidatorTest.php
- translations/validators.fr.yml
https://app.clubhouse.io/enmarche/story/4097/etq-cr%C3%A9ateur-d-%C3%A9v%C3%A9nement-je-dois-avoir-mon-calendrier-qui-ajouter-la-date-de-fin-%C3%A0-2h-du-m%C3%AAme-jour-et-je-dois-%C3%AAtre-limit%C3%A9
> Add new DateRange validator and use it for Event & Action forms

- features/donation.feature
- features/user_controller_donation.feature
- src/Controller/EnMarche/UserController.php
- src/Repository/DonationRepository.php
- src/Validator/UniqueDonationSubscription.php
- src/Validator/UniqueDonationSubscriptionValidator.php
- templates/user/donation_subscription_cancel_confirmation.html.twig
- templates/user/my_donation.html.twig
- translations/messages.fr.yml
- translations/validators.fr.yml
https://app.clubhouse.io/enmarche/story/3751/emp%C3%AAcher-les-personnes-qui-font-d%C3%A9j%C3%A0-un-don-mensuel-d-en-faire-un-second
> [ch3751] Fix wording in my donation page

- src/Controller/UploadDocumentController.php
https://sentry.io/en-marche-i7/en-marchefr/issues/476004096/?query=is:unresolved
> Replace non-ascii char in file name for http header

- app/config/services/platform.xml
- app/config/services/services.xml
- app/migrations/Version20180425145459.php
- composer.json
- composer.lock
- src/Admin/AdherentAdmin.php
- src/BoardMember/BoardMemberManager.php
- src/Command/InitializeEmailSubscriptionHistoryCommand.php
- src/Controller/EnMarche/UserController.php
- src/DataFixtures/ORM/LoadEmailSubscriptionHistoryData.php
- src/Entity/Reporting/EmailSubscriptionHistory.php
- src/Entity/Reporting/EmailSubscriptionHistoryAction.php
- src/Form/AdherentEmailSubscriptionType.php
- src/History/EmailSubscriptionHistoryHandler.php
- src/Membership/AdherentRegistry.php
- src/Membership/MembershipRequestHandler.php
- src/Referent/ReferentTagManager.php
- tests/Controller/EnMarche/AdherentControllerTest.php
- tests/Referent/ReferentTagManagerTest.php
- tests/TestHelperTrait.php
https://app.clubhouse.io/enmarche/story/3660/stocker-l-historique-des-choix-de-notification-des-utilisateurs
> Create user email subscription history

- templates/committee/all_committees.html.twig
- templates/events/all_events.html.twig
https://app.clubhouse.io/enmarche/story/3774/modifier-les-meta-descriptions-des-pages-tous-les-comit%C3%A9s-et-tous-les-%C3%A9v%C3%A9nements
> [ch3774] Add custom meta description in all events and committes page

- templates/committee/all_committees.html.twig
- templates/events/all_events.html.twig
https://app.clubhouse.io/enmarche/story/3661/modifier-les-h1-des-pages-tous-les-%C3%A9v%C3%A9nements-et-tous-les-comit%C3%A9s
> [ch3661] Add page number in all events and committes page

- templates/committee/_layout.html.twig
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/3749/modifier-les-meta-descriptions-des-pages-de-comit%C3%A9s-locaux
> [ch3749] Customise meta description for committee

- features/api/committees.feature
- src/Controller/Api/CommitteesController.php
- src/DataFixtures/ORM/LoadAdherentData.php
- src/Repository/AdherentRepository.php
https://app.clubhouse.io/enmarche/story/3616/2e-partie-section-comit%C3%A9s-box-kpis-comit%C3%A9s
> Create endpoint for managed committee members count by gender

- features/api/committees.feature
- features/donation.feature
- src/Controller/Api/CommitteesController.php
- src/DataFixtures/ORM/LoadEventData.php
- src/Repository/CommitteeRepository.php
https://app.clubhouse.io/enmarche/story/3617/2e-partie-section-comit%C3%A9s-graph-top-5-comit%C3%A9s-les-plus-actifs
https://app.clubhouse.io/enmarche/story/3639/2e-partie-section-comit%C3%A9s-graph-top-5-comit%C3%A9s-les-moins-actifs
> Create endpoints to get the most/least active committees in the referent managed area

- src/Adherent/AdherentRoleEnum.php
- src/Admin/AdherentAdmin.php
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/2473/admin-adh%C3%A9rents-je-veux-pouvoir-filtrer-tous-les-r%C3%B4les
> Add filter by adherent role

- features/registration.feature
- src/Membership/MembershipRequest.php
- tests/Controller/EnMarche/AdherentControllerTest.php
https://app.clubhouse.io/enmarche/story/3204/rendre-le-champ-t%C3%A9l%C3%A9phone-optionnel-sur-le-formulaire-d-adh%C3%A9sion
> [ch3204] Phone number on registration can be null

- features/donation.feature
- src/Donation/DonationRequestUtils.php
- src/Form/DonationRequestType.php
https://app.clubhouse.io/enmarche/story/3751/emp%C3%AAcher-les-personnes-qui-font-d%C3%A9j%C3%A0-un-don-mensuel-d-en-faire-un-second
> [ch3751] Add test to confirm we can donate with a subscription running

- front/style/layout/_buttons.scss
- front/style/layout/_layout.scss
https://app.clubhouse.io/enmarche/story/3145/supprimer-l-attribut-important-des-pages-amp
> [ch3145] Delete all important in amp css

- src/Entity/Donation.php
Fix https://sentry.io/en-marche-i7/en-marchefr/issues/563774029/
> Phone number for donation is nullable

- Makefile
- app/config/services/community.xml
- app/config/services/services.xml
- app/migrations/Version20180502142950.php
- src/Controller/EnMarche/DonationController.php
- src/Controller/EnMarche/UserController.php
- src/DataFixtures/ORM/LoadDonationData.php
- src/Donation/DonationFactory.php
- src/Donation/DonationRequestUtils.php
- src/Donation/PayboxFormFactory.php
- src/Donation/PayboxPaymentUnsubscription.php
- src/Donation/TransactionCallbackHandler.php
- src/Donation/TransactionSubscriber.php
- src/Entity/Donation.php
- src/Entity/Transaction.php
- src/Mailer/Message/DonationMessage.php
- src/Repository/DonationRepository.php
- src/Repository/TransactionRepository.php
- templates/user/my_donation.html.twig
- tests/Controller/EnMarche/DonationControllerTest.php
- tests/Donation/DonationFactoryTest.php
- tests/Entity/DonationTest.php
- tests/Entity/TransactionTest.php
- tests/TestHelperTrait.php
https://app.clubhouse.io/enmarche/story/3967/etq-enmarche-je-souhaite-avoir-l-historique-de-toutes-les-transactions-paybox
> [ch3967] Refactor donations to register transactions.

- app/config/services/platform.xml
- app/migrations/Version20180523160911.php
- src/Committee/CommitteeCreationCommandHandler.php
- src/Committee/CommitteeManager.php
- src/DataFixtures/ORM/LoadCommitteeMembershipHistoryData.php
- src/Entity/CommitteeMembership.php
- src/Entity/Reporting/CommitteeMembershipAction.php
- src/Entity/Reporting/CommitteeMembershipHistory.php
- src/Repository/CommitteeMembershipRepository.php
- src/Repository/ReferentTagRepository.php
- tests/Committee/CommitteeManagerTest.php
- tests/TestHelperTrait.php
https://app.clubhouse.io/enmarche/story/3659/stocker-l-historique-du-nombre-de-membres-de-comités
> Store history of join/leave of committees

- src/Validator/FrenchZipCodeValidator.php
- tests/Validator/FrenchZipCodeValidatorTest.php
- translations/validators.fr.yml
https://app.clubhouse.io/enmarche/story/3092/int%C3%A9grer-l-instant-field-validation-sur-les-formulaires-de-don-et-d-adh%C3%A9sion
> [ch3092] Add test and default text for repeat type and french zip code error message

- app/migrations/Version20180502142950.php
https://app.clubhouse.io/enmarche/story/3967/etq-enmarche-je-souhaite-avoir-l-historique-de-toutes-les-transactions-paybox
> [ch3967] Fix sql migration for time format

- app/migrations/Version20180524165445.php
- src/Command/InitializeEmailSubscriptionHistoryCommand.php
- src/DataFixtures/ORM/LoadEmailSubscriptionHistoryData.php
- src/Entity/Reporting/EmailSubscriptionHistory.php
- src/History/EmailSubscriptionHistoryHandler.php
- src/Repository/EmailSubscriptionHistoryRepository.php
- tests/Controller/EnMarche/AdherentControllerTest.php
https://app.clubhouse.io/enmarche/story/3660/stocker-l-historique-des-choix-de-notification-des-utilisateurs
> Many-to-Many relationship for email subscription history

- app/config/config.yml
- features/api/events.feature
- features/api/referent.feature
- src/Controller/Api/EventsController.php
- src/Controller/Api/ReferentController.php
- src/Entity/ReferentManagedArea.php
- src/Repository/AdherentRepository.php
- src/Repository/CommitteeRepository.php
- src/Repository/EmailSubscriptionHistoryRepository.php
- src/Repository/EventRepository.php
- src/Repository/Projection/ReferentManagedUserRepository.php
- src/Repository/ReferentTrait.php
- src/Statistics/StatisticsParametersFilter.php
https://app.clubhouse.io/enmarche/story/3612/2e-partie-section-comit%C3%A9s-scroll-down-double-graphique-choisir-un-comit%C3%A9-1
> Add endpoint for filtered events count by month + search bar with autocomplete

- features/donation.feature
- templates/adherent/_profile_menu.html.twig
- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
- templates/user/my_donation.html.twig
https://app.clubhouse.io/enmarche/story/4244/ajouter-un-lien-vers-mes-dons-dans-le-menu-utilisateur
> [ch4244] Add my donations link in user menu and fix wording

- features/api/events.feature
- src/Controller/Api/EventsController.php
- src/DataFixtures/ORM/LoadCitizenActionData.php
- src/DataFixtures/ORM/LoadEventData.php
- src/Entity/BaseEvent.php
- src/Repository/EventRepository.php
https://app.clubhouse.io/enmarche/story/3645/3e-partie-section-evenements-graph-histogramme-4-barres-cr%C3%A9ation-evenements
> Create endpoint for events count in the referent managed zone

- app/migrations/Version20180529102348.php
- src/Entity/Transaction.php
- templates/user/my_donation.html.twig
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/4192/ajouter-le-moyen-de-paiement-dans-l-historique-des-dons-sur-l-onglet-mes-dons
> [ch4192] Add payment method in historic donation

- features/api/events.feature
- src/Controller/Api/EventsController.php
- src/DataFixtures/ORM/LoadEventData.php
- src/Event/EventFactory.php
- src/Repository/EventRepository.php
- tests/Command/AlgoliaSynchronizeCommandTest.php
- tests/Command/ApiScheduleEventCreationCommandTest.php
- tests/Controller/Api/EventsControllerTest.php
- tests/Controller/Api/StatsControllerTest.php
- tests/Controller/ApiControllerTestTrait.php
- tests/Controller/EnMarche/MapControllerTest.php
- tests/Controller/EnMarche/SearchControllerTest.php
- tests/Repository/EventRepositoryTest.php
https://app.clubhouse.io/enmarche/story/3646/3e-partie-section-evenements-box-kpi-nb-events
> Add count events for current month to endpoint

- app/config/services/services.xml
- features/api/adherents.feature
- src/Controller/Api/AdherentsController.php
- src/DataFixtures/ORM/LoadAdherentData.php
- src/DataFixtures/ORM/LoadCommitteeMembershipHistoryData.php
- src/History/CommitteeMembershipHistoryHandler.php
- src/History/EmailSubscriptionHistoryHandler.php
- src/Membership/AdherentManager.php
- src/Repository/AdherentRepository.php
- src/Repository/CommitteeMembershipHistoryRepository.php
https://app.clubhouse.io/enmarche/story/3552/1ère-partie-section-adhérents-graph-double-histogramme-adherents-membres-de-comités
> Add route to count adherent by referent area

- app/migrations/Version20180531172925.php
- features/api/committees.feature
- features/api/events.feature
- src/Controller/Api/CommitteesController.php
- src/Controller/Api/EventsController.php
- src/DataFixtures/ORM/LoadEventData.php
- src/Entity/EventRegistration.php
- src/Event/EventRegistrationFactory.php
- src/History/CommitteeMembershipHistoryHandler.php
- src/Repository/AdherentRepository.php
- src/Repository/CommitteeMembershipHistoryRepository.php
- src/Repository/EventRegistrationRepository.php
- src/Repository/EventRepository.php
- src/Utils/RepositoryUtils.php
- tests/Command/AlgoliaSynchronizeCommandTest.php
- tests/Command/ApiScheduleEventCreationCommandTest.php
- tests/Controller/Api/StatsControllerTest.php
- tests/Controller/EnMarche/AdherentControllerTest.php
- tests/Controller/EnMarche/MapControllerTest.php
- tests/Repository/EventRepositoryTest.php
https://app.clubhouse.io/enmarche/story/4121/2e-partie-section-comit%C3%A9s-scroll-down-double-graphique-choisir-un-comit%C3%A9-2
> Add event participants count and committees members count by month with filtering 

- features/api/adherents.feature
- src/Controller/Api/UserController.php
- src/Entity/Adherent.php
https://app.clubhouse.io/enmarche/story/4335/faire-un-end-point-pour-le-user-courant
> [ch4335] current user endpoint

- app/config/services/services.xml
- features/donation.feature
- src/Donation/DonationRequest.php
- src/Repository/TransactionRepository.php
- src/Validator/MaxFiscalYearDonation.php
- src/Validator/MaxFiscalYearDonationValidator.php
- tests/Repository/TransactionRepositoryTest.php
- tests/Validator/MaxFiscalYearDonationValidatorTest.php
- translations/validators.fr.yml
https://app.clubhouse.io/enmarche/story/2795/introduire-une-limite-annuelle-de-7-500-euros-de-don-par-compte-utilisateur
>  [ch2795] Create a donation limit per year 

- src/Command/InitializeEmailSubscriptionHistoryCommand.php
https://app.clubhouse.io/enmarche/story/3660/stocker-l-historique-des-choix-de-notification-des-utilisateurs
> [ch3660] Speed init command

- features/api/events.feature
- src/Controller/Api/EventsController.php
- src/Repository/EventRegistrationRepository.php
https://app.clubhouse.io/enmarche/story/3637/1ère-partie-section-adhérents-graph-double-histogramme-emails-subscription
> [ch3637] count should be done on adherent and total

- src/Event/EventMessageNotifier.php
- templates/committee/timeline/_event.html.twig
https://app.clubhouse.io/enmarche/story/4275/supprimer-les-param%C3%A8tres-uuid-sur-les-liens-%C3%A9v%C3%A9nements-depuis-les-pages-comit%C3%A9s
(cherry picked from commit 2498aa6)
> [HOTFIX][ch4275] Remove UUID in the events links

- templates/search/search_committees.html.twig
- templates/search/search_events.html.twig
https://app.clubhouse.io/enmarche/story/3779/modifier-les-meta-descriptions-des-pages-comites-et-evenements
> [ch3779] Change meta descriptions for /comites and /evenements

- app/config/services/admin.xml
- app/config/services/twig.xml
- features/api/mooc.feature
- src/Admin/MoocElementAdmin.php
- src/DataFixtures/ORM/LoadMoocChapterData.php
- src/DataFixtures/ORM/LoadMoocQuizData.php
- src/Entity/Mooc/AttachmentFile.php
- src/Entity/Mooc/BaseMoocElement.php
- src/Entity/Mooc/Quiz.php
- src/Entity/Mooc/Video.php
- src/Normalizer/MoocNormalizer.php
- src/Twig/MoocElementExtension.php
- templates/admin/mooc/list_type.html.twig
- Renames Quizz for Quiz
- Adds Twig Test extension for Element type
- Removes `BaseMoocElement` issers and uses `instanceof` and a twig extension instead
- Removes type folder for the `AttachmentFile`
> [MOOC] Added Twig test extension and Refacto elements

- src/Entity/Adherent.php
- templates/admin/adherent/list_status.html.twig
https://app.clubhouse.io/enmarche/story/4325/etq-adh%C3%A9rent-d%C3%A9put%C3%A9-je-suis-taggu%C3%A9-dans-l-admin-avec-le-r%C3%B4le-depute
> Add deputy tag to adherent admin

- front/pages/donation_informations.js
- front/services/address/GooglePlaceAutocomplete.js
- templates/donation/informations.html.twig
https://app.clubhouse.io/enmarche/story/4194/int%C3%A9grer-le-place-autocomplete-au-formulaire-de-don
> [ch4294] Add autocomplete address via google maps api

- src/Admin/MoocElementAdmin.php
- templates/admin/layout.html.twig
Cherry picked from #2527 .
**commit:**  `49b0321102d97f33dbaef32426412c4dd51ba1c0`
> [MOOC] Added source button and advanced CKEditor instance

- app/config/config.yml
Cherry picked from #2527 
**commit:** 49b0321102d97f33dbaef32426412c4dd51ba1c0
> [MOOC] Allowed class and target attributes for editors

- src/Adherent/AdherentRoleEnum.php
- src/Admin/AdherentAdmin.php
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/4438/dans-l-admin-rajouter-dans-le-filtre-r%C3%B4le-celui-de-d%C3%A9put%C3%A9
> Add deputy role to adherent role filter in admin

- app/config/services/services.xml
- src/Command/BindDeputiesToDistrictsCommand.php
https://app.clubhouse.io/enmarche/story/4328/etq-adh%C3%A9rent-avec-le-r%C3%B4le-depute-j-ai-une-managed-area-qui-correspond-%C3%A0-ma-circonscription-d%C3%A9partement
> Bind deputies to districts

- app/config/config.yml
- app/config/services/services.xml
- app/migrations/Version20180619112308.php
- features/deputy.feature
- src/Controller/EnMarche/DeputyController.php
- src/Deputy/DeputyMessage.php
- src/Deputy/DeputyMessageNotifier.php
- src/Entity/Adherent.php
- src/Entity/District.php
- src/Form/DeputyMessageType.php
- src/Mailer/Message/DeputyMessage.php
- src/Repository/AdherentRepository.php
- src/Twig/AdherentExtension.php
- templates/components/_nav_desktop.html.twig
- templates/deputy/_layout.html.twig
- templates/deputy/users_message.html.twig
- translations/messages.fr.yml
- translations/validators.fr.yml
https://app.clubhouse.io/enmarche/story/4437/etq-d%C3%A9put%C3%A9-dans-la-section-envoyer-un-message-pas-de-filtre-affichage-du-nb-d-adh%C3%A9rents-recevant-le-message-dans-destinataire
> Add mail sending to adherents of deputy district

- app/config/services/platform.xml
- app/config/services/services.xml
- front/app.js
- front/pages/managed_list.js
- src/Controller/EnMarche/DeputyController.php
- src/Controller/EnMarche/ReferentController.php
- src/DataFixtures/ORM/LoadAdherentData.php
- src/Repository/CommitteeRepository.php
- templates/deputy/committees_list.html.twig
- templates/referent/committees_list.html.twig
https://app.clubhouse.io/enmarche/story/4436/etq-d%C3%A9put%C3%A9-dans-la-section-comit%C3%A9s-je-ne-vois-que-les-events-de-ma-zone-g%C3%A9r%C3%A9e-circonscription
> Add page listing committees in the deputy district

- features/admin/adherent.feature
- features/api/adherents.feature
- features/deputy.feature
- features/republican_silence.feature
- src/DataFixtures/ORM/LoadAdherentData.php
- src/DataFixtures/ORM/LoadDistrictData.php
- src/DataFixtures/ORM/LoadRepublicanSilenceData.php
- src/RepublicanSilence/CheckRepublicanSilenceListener.php
- src/RepublicanSilence/ReferentTagExtractorFactory.php
- src/RepublicanSilence/TagExtractor/DistrictReferentTagExtractor.php
- src/RepublicanSilence/TagExtractor/ReferentTagExtractorInterface.php
- src/Utils/AreaUtils.php
- tests/BoardMember/BoardMemberManagerTest.php
- tests/CitizenProject/CitizenProjectManagerTest.php
- tests/Controller/Api/StatsControllerTest.php
- tests/Controller/EnMarche/BoardMemberControllerTest.php
- tests/Controller/EnMarche/MapControllerTest.php
- tests/Repository/AdherentRepositoryTest.php
- tests/RepublicanSilence/TagExtractor/DistrictReferentTagExtractorTest.php
https://app.clubhouse.io/enmarche/story/4440/int%C3%A9grer-l-espace-d%C3%A9put%C3%A9-dans-le-silence-r%C3%A9publicain
> Add republican silence for deputy space

- src/Admin/EmailAdmin.php
https://app.clubhouse.io/enmarche/story/4541/ajouter-une-recherche-par-destinataire-dans-les-logs-mailer
> Add recipients filter to mails admin

- src/Admin/EmailAdmin.php
- src/Entity/Email.php
https://app.clubhouse.io/enmarche/story/4541/ajouter-une-recherche-par-destinataire-dans-les-logs-mailer
> Add recipients column to mails admin

- templates/citizen_action/attend.html.twig
- templates/events/attend.html.twig
- templates/events/invitation.html.twig
https://app.clubhouse.io/enmarche/story/4607/modifier-les-canonicals-des-pages-invitation-et-inscription-pour-les-%C3%A9v%C3%A9nements
> Change canonical links on event invitation and registration pages

- src/Controller/EnMarche/DonationController.php
- src/Donation/DonationRequest.php
- src/Donation/DonationRequestUtils.php
- src/Form/DonationRequestType.php
- templates/donation/informations.html.twig
- templates/donation/result.html.twig
- templates/form_theme.html.twig
> [Donation] Added alert feature for high amount

- features/donation.feature
- front/style/pages/_donation.scss
- src/Admin/DonationAdmin.php
- src/DataFixtures/ORM/LoadDonationData.php
- src/Donation/DonationFactory.php
- src/Donation/DonationRequest.php
- src/Entity/Donation.php
- src/Form/DonationRequestType.php
- src/ValueObject/Genders.php
- templates/donation/informations.html.twig
- tests/Controller/EnMarche/DonationControllerTest.php
- tests/Donation/DonationFactoryTest.php
- tests/Donation/DonationRequestTest.php
- tests/Entity/DonationTest.php
- translations/messages.fr.yml
- Updated gender status `Madame`, `Monsieur` instead of `Femme`, `Homme`, but keep the same values in bdd
- Removed phone fields
> [Donation] Updated civility and removed phone fields

- templates/article/actualites.html.twig
https://app.clubhouse.io/enmarche/story/4608/modifier-les-h1-des-pages-de-pagination-des-r%C3%A9pertoires-articles
> Add page number to the header on the articles list pages

- templates/donation/informations.html.twig
- templates/events/attend.html.twig
- templates/form_theme.html.twig
- templates/home/index.html.twig
- templates/invitation/form.html.twig
https://app.clubhouse.io/enmarche/story/4632/modifier-les-mentions-d-informations-sur-certains-formulaires-du-site
> Change GDPR and checkbox position on the forms

- templates/events/_header.html.twig
- tests/Controller/EnMarche/CommitteeManagerControllerTest.php
- tests/Controller/EnMarche/EventManagerControllerTest.php
https://app.clubhouse.io/enmarche/story/4618/ajouter-le-lieu-et-la-date-dans-le-h1-des-%C3%A9v%C3%A9nements
> Add city and date to the event header

- front/services/address/GooglePlaceAutocomplete.js
Set the default value for country and replace `.bind(this)` by `() => `, thanks @HeahDude
> Set FR as default country for autocomplete google place

- templates/citizen_action/_layout.html.twig
- templates/citizen_action/_participants_list.html.twig
- templates/citizen_action/list_participants.html.twig
- templates/citizen_action/show.html.twig
- templates/citizen_action_manager/print_participants.html.twig
- templates/citizen_project/_layout.html.twig
- templates/citizen_project/_sidebar.html.twig
- templates/citizen_project/list_actors.html.twig
- templates/citizen_project/show_base.html.twig
> Execute runManageParticipants only if host to avoid JS error

- src/Admin/AdministratorAdmin.php
Fixed CS and removed useless var
> Removed useless var

- front/components/AmountChooser.js
https://app.clubhouse.io/enmarche/story/4772/retirer-le-texte-de-don-r%C3%A9current-sur-le-form-de-don-de-la-home
> Remove text about monthly don

- src/Command/MigrateSubscriptionTypeCommand.php
> Improve subscription type migration command

- app/config/security.yml
- app/config/services/admin.xml
- app/migrations/Version20180705144501.php
- app/migrations/Version20180718152912.php
- features/bootstrap/RabbitMqContext.php
- features/bootstrap/SyncWithAPIContext.php
- features/registration.feature
- features/sync_with_api.feature
- features/webhook.feature
- src/Admin/AdministratorAdmin.php
- src/Admin/SubscriptionTypeAdmin.php
- src/Controller/EnMarche/UserController.php
- src/DataFixtures/ORM/LoadClientData.php
- src/DataFixtures/ORM/LoadSubscriptionTypeData.php
- src/DataFixtures/ORM/LoadWebHookData.php
- src/Entity/Adherent.php
- src/Entity/SubscriptionType.php
- src/Entity/WebHook/WebHook.php
- src/Form/WebHookType.php
- src/Membership/EventListener/UserSubscriber.php
- src/Membership/UserEvent.php
- src/Membership/UserEvents.php
- src/Repository/WebHookRepository.php
- src/WebHook/Event.php
- src/WebHook/Service.php
- templates/user/set_email_notifications.html.twig
https://app.clubhouse.io/enmarche/story/3687/step-2-a-webhooks-notifs-vers-mailchimp-ou-mailjet-etq-adh%C3%A9rent-si-je-modifie-mes-notifications-cela-doit-se-r%C3%A9percuter-sur
It's ok that I change an old migration https://github.com/EnMarche/en-marche.fr/pull/2599/files#diff-72c8fe2840e5ed19a45b93778c5c3644R40, confirmed with @Remg.
>  Add webhook for mailchimp when user change email subscriptions

- front/style/layout/_layout.scss
- templates/home/index.html.twig
> Change background color of newsletter block

- front/style/pages/_committee.scss
- src/Controller/EnMarche/EventController.php
- src/Repository/EventRepository.php
- templates/events/show.html.twig
- tests/Controller/EnMarche/EventControllerTest.php
- translations/messages.fr.yml
Adds a three closest events module on the event page.
> [Events] Added the three closest events

- src/Command/ImportDistrictsCommand.php
- src/Deputy/DistrictLoader.php
basically it will allow us to specify url for files in arguments.
> Change the way files are checked

- templates/events/_header.html.twig
- templates/events/show.html.twig
- translations/messages.fr.yml
Deplacer "Signaler cet événement" et le mettre en bleu clair
> [Event] move report event link

- src/CitizenProject/CitizenProjectManagementAuthority.php
https://sentry.io/en-marche-i7/en-marchefr/issues/699173001/?referrer=slack
> Fix CP variable name

- app/config/security.yml
- app/config/services/admin.xml
- app/config/services/services.xml
- app/migrations/Version20180921151801.php
- front/style/content/_movement.scss
- src/Admin/AdministratorAdmin.php
- src/Admin/ExecutiveOfficeMemberAdmin.php
- src/Biography/BiographyManager.php
- src/Collection/ExecutiveOfficeMemberCollection.php
- src/Controller/EnMarche/BiographyController.php
- src/Controller/EnMarche/PageController.php
- src/DataFixtures/ORM/LoadAdminData.php
- src/DataFixtures/ORM/LoadExecutiveOfficeMemberData.php
- src/Entity/Biography/AbstractBiography.php
- src/Entity/Biography/ExecutiveOfficeMember.php
- src/Repository/Biography/ExecutiveOfficeMemberRepository.php
- src/Storage/ImageStorage.php
- src/Validator/UniqueExecutiveOfficer.php
- src/Validator/UniqueExecutiveOfficerValidator.php
- templates/components/_footer.html.twig
- templates/page/le-mouvement/layout.html.twig
- templates/page/le-mouvement/notre-organisation.html.twig
- templates/referent/nomination/homepage.html.twig
- templates/social_share/profile_share.html.twig
- tests/Controller/EnMarche/BiographyControllerTest.php
- tests/Controller/EnMarche/PageControllerTest.php
- translations/validators.fr.yml
This PR improves the old organization page and allows to manage the members via the BO.
> [Biography] Added organization

- front/style/content/_movement.scss
- templates/page/le-mouvement/notre-organisation.html.twig
> [Biography] Updated social networks block position

- .circleci/config.yml
- features/admin/adherent.feature
- features/admin/citizen_project.feature
- features/admin/committee_merge.feature
- features/api/adherents.feature
- features/api/committees.feature
- features/api/events.feature
- features/api/mooc.feature
- features/api/referent.feature
- features/api/statistics.feature
- features/api/subscription.feature
- features/api/turnkey_projects.feature
- features/donation.feature
- features/oauth.feature
- features/user_controller_donation.feature
before:
behat ~ 8-9min
after 
behat ~ 5-6min
> Split behat tests on 2 containers

- Makefile
In order to pass phpunit args like --filter
> Add args on phpunit in makefile

- app/config/config.yml
- app/config/services/services.xml
- app/migrations/Version20181008161616.php
- features/api/mooc.feature
- src/Admin/MoocAdmin.php
- src/DataFixtures/ORM/LoadMoocData.php
- src/Entity/Biography/AbstractBiography.php
- src/Entity/ImageTrait.php
- src/Entity/Mooc/Mooc.php
- src/Mooc/MoocManager.php
- src/Serializer/MoocSerializerSubscriber.php
- templates/admin/list/list_image_miniature.html.twig
- templates/form_theme_admin.html.twig
- templates/page/le-mouvement/notre-organisation.html.twig
Permettre l'upload d'une vignette lors de la création d'un MOOC
> Add thumbnail image on mooc

- features/deputy.feature
- src/Mailer/Message/DeputyMessage.php
Story details: https://app.clubhouse.io/enmarche/story/5669
> Add territory mail as new recipient for Deputy message

- src/Collection/ExecutiveOfficeMemberCollection.php
- src/Controller/EnMarche/DeputyController.php
- src/Deputy/DeputyMessage.php
- src/Deputy/DeputyMessageNotifier.php
- src/Entity/Adherent.php
- src/Repository/AdherentRepository.php
- src/RepublicanSilence/TagExtractor/ReferentTagExtractor.php
1) https://sentry.io/en-marche-i7/en-marchefr/issues/703118106/
2) https://sentry.io/en-marche-i7/en-marchefr/issues/667961909/
3) https://sentry.io/en-marche-i7/staging-en-marchefr/issues/736240485/
> [Deputy] Fix adherents selection query

- web/apps/projets-citoyens/.env.sample
- web/apps/projets-citoyens/package-lock.json
- web/apps/projets-citoyens/package.json
- web/apps/projets-citoyens/src/App.scss
- web/apps/projets-citoyens/src/js/actions/citizen-projects.js
- web/apps/projets-citoyens/src/js/components/Sidebar.js
- web/apps/projets-citoyens/src/js/containers/CitizenProjectSearch.js
- web/apps/projets-citoyens/src/js/utils/api.js
- web/apps/projets-citoyens/src/style/containers/citizen-project/_citizen-project.scss
- web/apps/projets-citoyens/src/style/containers/citizen-project/_nav-dropdown.scss
- web/apps/projets-citoyens/yarn.lock
[ch5472]
adds a mobile nav to turnkey projects
filter city input against back end 
Note that there is some nasty logic in the version of `react-select` that we're using, which prevents a typed value from being displayed after clicking off the dropdown. I've explored a few ways to make it work. Maybe @Charlesdoiron has some ideas?
> Front update Brian Turnkey projects [ch5472]

- templates/membership/join.html.twig
https://sentry.io/en-marche-i7/en-marchefr/issues/564871757
> Do not send the first email field if empty

- src/Redirection/Dynamic/RedirectionsSubscriber.php
> Check URL before try to redirect

- app/migrations/Version20181026113721.php
- features/popup_chart.feature
- front/style/layout/_layout.scss
- src/Controller/EnMarche/UserController.php
- src/DataFixtures/ORM/LoadAdherentData.php
- src/Entity/Adherent.php
- templates/chart_dialog.html.twig
- templates/deputy/_layout.html.twig
- templates/javascript.js.twig
- templates/referent/_layout.html.twig
- translations/messages.fr.yml
no tests to check if user chartAccepted has been changed, is there any doctrine context ?
!important in scss is because <object> add css on element
> Popup to let deputy and referent be informed of the new chart

- front/style/mixins/_text.scss
- src/Controller/EnMarche/ReferentController.php
- src/Referent/SurveyExporter.php
- src/Repository/SurveyRepository.php
- templates/referent/surveys/list.html.twig
> [Jecoute] Added publish icons and unanonymize the creator

- web/apps/projets-citoyens/src/js/containers/CitizenProjectTurnKey.js
> only render the dropdown if there's data

- front/style/pages/_referent.scss
- src/Controller/EnMarche/ReferentController.php
- src/Entity/Jecoute/Question.php
- src/Entity/Jecoute/SuggestedQuestion.php
- src/Entity/Jecoute/Survey.php
- src/Entity/Jecoute/SurveyQuestion.php
- src/Repository/SuggestedQuestionRepository.php
- templates/referent/surveys/_form.html.twig
- templates/referent/surveys/create.html.twig
- templates/referent/surveys/suggested_questions_dialog.html.twig
Popin to choose a suggested question :
New question with the suggested question values :
> [Jecoute] Front : Added suggested questions in the surveys form

- front/style/pages/_referent.scss
- templates/referent/surveys/_form.html.twig
> [Jecoute] Survey form : Added question number in the label

- app/migrations/Version20181112221158.php
- features/api/surveys.feature
- src/Admin/JecouteSuggestedQuestionAdmin.php
- src/DataFixtures/ORM/LoadJecouteSurveyData.php
- src/Entity/Jecoute/SurveyQuestion.php
- src/Form/Jecoute/SurveyQuestionFormType.php
- templates/admin/jecoute/suggested_question_choices.html.twig
- templates/referent/_form_theme.html.twig
- templates/referent/surveys/_form.html.twig
- templates/referent/surveys/create.html.twig
This PR adds the suggested question flag and locks theses questions in the survey form.
> [Jecoute] Added suggested question flag

- front/style/pages/_referent.scss
- templates/referent/surveys/create.html.twig
> [Jecoute] Updated CSS render for locked questions

- front/style/pages/_register.scss
- src/Form/AdherentType.php
- templates/adherent/profile.html.twig
- templates/membership/join.html.twig
- translations/messages.fr.yml
Spec :
- Les 2 barres en mode gris clair pour encadrer la partie optionnel
- Sur la checkbox, “oui” devient "je suis elu"
- Le dropdwon à droite
Form d'adhésion
Form d'édition de profil
> Update elected checkbox ergo

- front/pages/committees_map.js
- front/services/map/MapFactory.js
- package.json
- yarn.lock
> [GMap] Add clusters to committee map

- templates/referent/surveys/_form.html.twig
- templates/referent/surveys/create.html.twig
> [Jecoute] Updated custom button and added text

- app/migrations/Version20181122103334.php
- features/mandate.feature
- front/style/pages/_register.scss
- src/Admin/AdherentAdmin.php
- src/Entity/Adherent.php
- src/Form/AdherentType.php
- src/Membership/AdherentFactory.php
- src/Membership/MembershipRequest.php
- templates/adherent/profile.html.twig
- templates/admin/adherent/_mandate.html.twig
- templates/admin/adherent/_mandates.html.twig
- templates/admin/adherent/list_mandates.html.twig
- templates/admin/adherent/show_mandates.html.twig
- templates/membership/_mandates_script.html.twig
- templates/membership/join.html.twig
- translations/messages.fr.yml
Update mandate choice in join and profil edition to mulitple choices
> Update mandate to array

- front/style/pages/_register.scss
- src/Admin/AdherentAdmin.php
- src/Form/AdherentType.php
- templates/adherent/profile.html.twig
- templates/admin/adherent/_mandates.html.twig
- templates/membership/join.html.twig
- translations/messages.fr.yml
> Update admin and responsivity

- .php_cs.dist
- src/Admin/ArticleAdmin.php
- src/Admin/CitizenProjectAdmin.php
- src/Admin/CommitteeAdmin.php
- src/Admin/EventAdmin.php
- src/Admin/OrderArticleAdmin.php
- src/Admin/ProposalAdmin.php
- src/Doctrine/Hydrators/EventHydrator.php
- src/Exception/AccountNotValidatedException.php
- src/Form/CommitteeAroundAdherentType.php
- src/Form/DataTransformer/ReferentAreaTransformer.php
- src/Form/EventListener/SkillListener.php
- src/Form/Jecoute/QuestionType.php
- src/Form/Jecoute/SurveyFormType.php
- src/Form/MonthChoiceType.php
- src/Routing/RemoteUrlGenerator.php
- src/Twig/MarkdownExtension.php
- src/Validator/Address.php
- src/Validator/UnitedNationsCountry.php
- src/Validator/WasNotInvitedRecently.php
- tests/Controller/EnMarche/SummaryManagerControllerTest.php
This PR fix somes short array syntax and adds the `array_syntax` rule.
> Fixed short array syntax and added PHP CS rule

- app/config/config.yml
- app/config/services/admin.xml
- src/Admin/JecouteSuggestedQuestionAdmin.php
- templates/admin/CRUD/list/array_list.html.twig
- templates/admin/CRUD/show/array_list.html.twig
- templates/admin/jecoute/suggested_question_edit.html.twig
> [Jecoute] Admin : Disallowed edit suggested questions

- composer.lock
- src/Controller/EnMarche/MapController.php
- templates/map/events.html.twig
- templates/search/search_committees.html.twig
```
Package operations: 0 installs, 1 update, 0 removals
- Updating symfony/symfony (v3.4.14 => v3.4.20)
```
> Disable map of committees in production

- src/Admin/MoocChapterAdmin.php
- src/Admin/MoocElementAdmin.php
> fix selector MOOC/chapiter [ch5943]

- src/Deputy/Subscriber/BindAdherentDistrictSubscriber.php
- src/Repository/DistrictRepository.php
- tests/Deputy/Subscriber/BindAdherentDistrictSubscriberTest.php
add condition bind district by adherent country
> add condition bind district by adherent country

- features/adherent_dashboard.feature
- front/style/layout/_nav.scss
- src/Controller/EnMarche/AdherentController.php
- src/Repository/CommitteeMembershipRepository.php
- templates/adherent/list_my_committees_al.html.twig
Fix bug display dropdown for single committee and CSS push right arrown of dropdown [ch6198]
> dev query find committee by privilege [ch6198]

- web/apps/atelier-des-idees/src/pages/Propose/PreProposal/_style.scss
- web/apps/atelier-des-idees/src/pages/Propose/PreProposal/index.jsx
- web/apps/atelier-des-idees/src/pages/Propose/ProposalCriteria/_style.scss
- web/apps/atelier-des-idees/src/pages/Propose/ProposalCriteria/index.jsx
- web/apps/atelier-des-idees/src/pages/Propose/ProposalSteps/_style.scss
- web/apps/atelier-des-idees/src/pages/Propose/index.jsx
- web/apps/atelier-des-idees/src/pages/ThreeTabs/_style.scss
> [ADI] css fixes on "proposer" page

- web/apps/atelier-des-idees/src/components/Header/_style.scss
- web/apps/atelier-des-idees/src/components/IdeaFilters/_style.scss
- web/apps/atelier-des-idees/src/pages/ThreeTabs/_style.scss
ajout du sticky header sur la nav (homepage + tabs)
> [ADI] add sticky header

- web/apps/atelier-des-idees/src/components/IdeaCard/_style.scss
- web/apps/atelier-des-idees/src/containers/ModalRoot/_style.scss
- fix homepage zindex
- add hover to cards
> [ADI] css fixes

- web/apps/atelier-des-idees/src/components/IdeaCard/_style.scss
- web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
- web/apps/atelier-des-idees/src/components/IdeaCardList/_style.scss
- web/apps/atelier-des-idees/src/components/IdeaFilters/_style.scss
- web/apps/atelier-des-idees/src/components/Modal/FlagModal/_style.scss
- web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/FirstForm/_style.scss
- web/apps/atelier-des-idees/src/components/Modal/PublishIdeaFormModal/SecondForm/_style.scss
- web/apps/atelier-des-idees/src/components/Select/_style.scss
- web/apps/atelier-des-idees/src/components/TextArea/_style.scss
- web/apps/atelier-des-idees/src/containers/ModalRoot/_style.scss
- web/apps/atelier-des-idees/src/pages/Consult/_style.scss
- web/apps/atelier-des-idees/src/pages/Contribute/_style.scss
- web/apps/atelier-des-idees/src/pages/IdeaPageBase/IdeaPageTitle/_style.scss
> [ADI] css fixes on submit forms

- composer.json
- composer.lock
```
Package operations: 0 installs, 1 update, 0 removals
- Updating api-platform/core (v2.2.9 => v2.2.10)
```
> Upgrade api-platform/core 2.2.10

- front/components/AmountChooser.js
- front/style/layout/_forms.scss
- front/style/pages/_donation.scss
- src/Controller/EnMarche/DonationController.php
'add choices during time "don"'
>  'add choices during time "don"'

- features/donation.feature
- src/DataFixtures/ORM/LoadDonationData.php
- src/Donation/DonationFactory.php
- src/Donation/DonationRequest.php
- src/Entity/Donation.php
- src/Form/DonationRequestType.php
- templates/donation/informations.html.twig
- tests/Controller/EnMarche/DonationControllerTest.php
modifie integration field nationality
> modifie integration field nationality

- src/Entity/IdeasWorkshop/Theme.php
Formulaire d'ajout
Liste des thèmes
> [ADI] Fix error on theme creation

- app/migrations/Version20190118142342.php
- features/admin/adherent_tags.feature
- src/DataFixtures/ORM/LoadAdherentTagData.php
- src/Entity/AdherentTagEnum.php
- src/Security/Voter/IdeaQGVoter.php
Ajout du tag dans l'édition d'un Adhérent
Visible dans la liste
Et filtrable
> [ADI] Add LaREM tag for ideas-workshop

- features/search/events.feature
- templates/citizen_action/show.html.twig
- templates/events/_header.html.twig
- templates/search/_events.html.twig
- tests/Controller/EnMarche/AbstractEventControllerTest.php
- tests/Controller/EnMarche/CitizenActionControllerTest.php
- tests/Controller/EnMarche/EventControllerTest.php
hide participants if not logged
> hide participants if not logged

- app/migrations/Version20190124141525.php
- src/Entity/Donation.php
> set field nationality to null

- src/Form/Jecoute/ChoiceFormType.php
- src/Form/Jecoute/SurveyQuestionFormType.php
- src/Repository/Jecoute/SurveyRepository.php
- templates/referent/_form_theme.html.twig
- templates/referent/surveys/create.html.twig
- templates/referent/surveys/stats.html.twig
This PR:
- Fixes the choices positions
- Allow the stats page for disable surveys
- Updates the stats render with empty data
> [Jecoute] Updated form and stats

- features/api/report.feature
- src/Admin/IdeasWorkshopIdeaAdmin.php
- src/Admin/ReportAdmin.php
- src/Controller/Api/ReportController.php
- src/DataFixtures/ORM/LoadReportData.php
- src/Entity/Report/Report.php
- src/Entity/Report/ReportReasonEnum.php
- src/Entity/Report/ReportStatusEnum.php
- src/Form/ReportCommandType.php
- src/Report/ReportCommand.php
- templates/admin/ideas_workshop/idea/list_deadline.html.twig
- templates/admin/ideas_workshop/idea/list_show_page.html.twig
- templates/admin/ideas_workshop/list_action_moderate.html.twig
- tests/Controller/EnMarche/ReportControllerTest.php
- tests/Entity/ReportTest.php
- translations/reports.fr.yml
Several updates on the admin part. 
The "Show on website" button has been removed due to front implementation delay.
> [ADI] Update admin reports and idea

- web/apps/atelier-des-idees/src/redux/thunk/threads.js
https://app.clubhouse.io/enmarche/story/6733/modifier-le-front-du-commentaire-approuv%C3%A9-pour-permettre-l-envoi-d-un-mail
> [ADI] update threads and comments approval endpoint call

- src/Admin/JecouteSurveyAdmin.php
change filter to ModelAutocomplete
> change filter to ModelAutocomplete

- src/Controller/EnMarche/ReferentController.php
- src/DataFixtures/ORM/LoadJecouteDataSurveyData.php
- src/Entity/Jecoute/Choice.php
- src/Entity/Jecoute/Question.php
- src/Entity/Jecoute/Survey.php
- src/Entity/Jecoute/SurveyQuestion.php
- src/Referent/SurveyExporter.php
- templates/referent/surveys/list.html.twig
- translations/messages.fr.yml
> [Jecoute] Added surveys duplication

- tests/OAuth/PersistentTokenFactoryTest.php
> [Test] Store Token date into variable

- src/Controller/EnMarche/ReferentController.php
- src/Jecoute/StatisticsExporter.php
edit download file stat question
> edit download file stat question

- app/migrations/Version20190205173350.php
> [ADI] Fix position

- app/migrations/Version20190204134057.php
- src/Admin/AdherentAdmin.php
- src/Entity/Adherent.php
- src/Form/Admin/ReferentManagedAreaType.php
- tests/Admin/AdherentAdminTest.php
- translations/messages.fr.yml
refacto adherent admin
Fusion between Adherent, Referent, Depute
[story](https://app.clubhouse.io/enmarche/story/6787/optimiser-la-fiche-adh%C3%A9rent-sur-l-admin)
> refacto adherent admin

- src/Admin/ReportAdmin.php
- templates/admin/ideas_workshop/list_action_moderate.html.twig
- templates/admin/report/list_actions.html.twig
- templates/admin/report/list_enabled.html.twig
> [ADI] Update report admin

- src/Admin/Extension/DoctrineEnabledFilterConfigurationAdminExtension.php
- src/Admin/Extension/DoctrineSoftdeleteableFilterConfigurationAdminExtension.php
- src/Admin/IdeasWorkshopThreadAdmin.php
- src/Admin/ReportAdmin.php
- src/Entity/Article.php
- src/Entity/Clarification.php
- src/Entity/EntitySoftDeletedInterface.php
- src/Entity/IdeasWorkshop/BaseComment.php
- src/Entity/NewsletterSubscription.php
- src/Entity/OAuth/Client.php
- src/Entity/OrderArticle.php
- src/Entity/Page.php
- src/Entity/Proposal.php
- src/Twig/InstanceOfExtension.php
- templates/admin/ideas_workshop/details_column.html.twig
- templates/admin/ideas_workshop/list_action_moderate.html.twig
- templates/admin/partial/_details.html.twig
- templates/admin/report/details_column.html.twig
> Admin fix soft deleted view

- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
Reverts EnMarche/en-marche.fr#3325
> Revert "[ADI] Remove canary for link in header"

- features/admin/ideas_workshop_ideas.feature
- src/Admin/IdeasWorkshopIdeaAdmin.php
- templates/admin/ideas_workshop/idea/_status.html.twig
- templates/admin/ideas_workshop/idea/list_author_category.html.twig
- translations/messages.fr.yml
- Hide Committee and countributors count columns :heavy_check_mark: 
- Add AuthorCategory in list and filter :heavy_check_mark: 
- Filter on statuses in french :heavy_check_mark:
> [ADI] Update idea admin

- src/Security/LegacyMigrationListener.php
https://sentry.io/en-marche-i7/en-marchefr/issues/873509681/?referrer=slack
> Fix old password migration

- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
Reverts EnMarche/en-marche.fr#3328
> Revert "Revert "[ADI] Remove canary for link in header""

- src/Mailer/Message/AdherentChangeEmailMessage.php
- src/Membership/AdherentChangeEmailHandler.php
adherent change email is send on new email
> adherent change email is send on new email

- app/config/services/admin.xml
Admin Create Archives field and put useless field
> Admin Create Archives field and put useless field

- web/apps/atelier-des-idees/src/App.scss
- web/apps/atelier-des-idees/src/components/CommentsList/Comment/_style.scss
- web/apps/atelier-des-idees/src/components/IdeaCard/_style.scss
- web/apps/atelier-des-idees/src/components/IdeaCard/index.jsx
- web/apps/atelier-des-idees/src/components/IdeaCardList/index.jsx
- web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyContributions/_style.scss
- web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyContributions/index.jsx
- web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/_style.scss
- web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/MyIdeas/index.jsx
- web/apps/atelier-des-idees/src/components/Modal/MyIdeasModal/index.jsx
- web/apps/atelier-des-idees/src/components/Pagination/_style.scss
- web/apps/atelier-des-idees/src/components/Pagination/index.jsx
- web/apps/atelier-des-idees/src/containers/MyIdeas/index.jsx
- web/apps/atelier-des-idees/src/redux/actions/myIdeas.js
- web/apps/atelier-des-idees/src/redux/reducers/myContributions.js
- web/apps/atelier-des-idees/src/redux/reducers/myIdeas.js
- web/apps/atelier-des-idees/src/redux/selectors/myContributions.js
- web/apps/atelier-des-idees/src/redux/selectors/myIdeas.js
- web/apps/atelier-des-idees/src/redux/thunk/ideas.js
Story details: https://app.clubhouse.io/enmarche/story/6535
> Put a pagination on modal "Mes propositions" and "Mes contributions"

- templates/admin/organizational_chart/admin_list.html.twig
- templates/admin/organizational_chart/chart_macros.html.twig
- templates/admin/referent/organization_chart.html.twig
refacto design admin referent organigramme
> refacto design admin referent organigramme

- app/config/services/services.xml
- front/components/AmountChooser.js
- front/components/DonationAmountChooser.js
- src/Donation/DonationRequest.php
- src/Validator/MaxMonthDonation.php
- src/Validator/MaxMonthDonationValidator.php
- tests/Validator/MaxMonthDonationValidatorTest.php
- translations/validators.fr.yml
dev display limit amount while 'abonnement'
> dev display limit amount while 'abonnement'

- .circleci/config.yml
- bin/build-react-apps.js
- features/popup_chart.feature
- features/registration.feature
- features/republican_silence.feature
- features/surveys.feature
before:
after:
we won:
- ~45sec on the `build` job (because we don't build the `example` react app anymore)
- ~2mn on the `behat` job (because we use more containers)
> [Circle] More containers for behat & do not build example app

- front/app.js
- front/components/MessageStatusLoader.js
- front/pages/message_filters.js
- front/services/api/ReqwestApiClient.js
- front/style/app.scss
- front/style/pages/_adherent-messages.scss
- src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
- src/Command/MailchimpCreateTagFromReferentTagCommand.php
- src/Command/MailchimpSyncAllAdherentsCommand.php
- src/Command/MailchimpUpdateReferentTagExternalIdFromMailchimpCommand.php
- src/Controller/EnMarche/MessageController.php
- src/Entity/AdherentMessage/AbstractAdherentMessage.php
- templates/message/filter.html.twig
- templates/message/filter/referent.html.twig
- templates/message/preview.html.twig
> [AdherentMessage] Add Message action buttons if it was synchronized

- src/Entity/Adherent.php
https://sentry.io/en-marche-i7/staging-en-marchefr/issues/884962976/?referrer=slack
> Set collection instance to Adherent tags property

- templates/components/_footer.html.twig
- web/apps/atelier-des-idees/public/index.html
- web/apps/example/public/index.html
> Remove shop from EM

- front/pages/registration.js
- templates/membership/register.html.twig
display every-time captcha on register form
> display every-time captcha on register form

- src/Command/MailchimpSyncAllAdherentsCommand.php
> [AdherentMessage] Add RefTag filter to sync adherent command

- src/Admin/CitizenProjectAdmin.php
- src/Form/CoordinatorAreaType.php
- templates/coordinator/_citizen_project_list.html.twig
- templates/coordinator/_committee_list.html.twig
- templates/coordinator/committees.html.twig
- tests/Controller/EnMarche/CoordinatorControllerTest.php
> remove action comment

- templates/components/_footer.html.twig
- templates/home/index.html.twig
> add btn rss

- src/Controller/Api/UserController.php
https://sentry.io/en-marche-i7/en-marchefr/issues/855537175/?referrer=slack
> Use adherent role in showMe action

- app/migrations/Version20190222115015.php
- front/style/pages/_procuration.scss
- src/Entity/ProcurationProxy.php
- src/Form/Procuration/ProcurationProxyType.php
- templates/procuration/proposal.html.twig
- translations/validators.fr.yml
Add radio button to the proxy form to let user add a number of available proxy. 
Had to add jquery in form to implement specific condition :
- If user vote in France, it's 2 max (one in France and the other elsewhere)
- if user vote elsewhere than France, it's 3 max 
When France is chosen
When another country than France is chosen
> Add radio button to the proxy form

- app/config/services/services.xml
- app/migrations/Version20190221144312.php
- src/Admin/InstitutionalEventAdmin.php
- src/Controller/EnMarche/ReferentController.php
- src/Entity/InstitutionalEvent.php
- src/Event/EventFactory.php
- src/Form/DataTransformer/StringToArrayTransformer.php
- src/Form/InstitutionalEventCommandType.php
- src/InstitutionalEvent/InstitutionalEventCommand.php
- src/InstitutionalEvent/InstitutionalEventCommandHandler.php
- src/InstitutionalEvent/InstitutionalEventEvent.php
- src/InstitutionalEvent/InstitutionalEventMessageNotifier.php
- src/Mailer/EmailTemplate.php
- src/Mailer/Message/InstitutionalEventInvitationMessage.php
- src/Mailer/Message/Message.php
- src/Mailjet/EmailTemplate.php
- src/Referent/ManagedInstitutionalEventsExporter.php
- templates/referent/institutional_events/create.html.twig
- templates/referent/institutional_events/list.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
- translations/messages.fr.yml
> [Institutional events] Added invitations

- features/republican_silence.feature
- templates/procuration/_faq.html.twig
- templates/procuration/_layout.html.twig
- templates/procuration/choose_election.html.twig
- templates/procuration/landing.html.twig
- templates/procuration/proposal.html.twig
- tests/Controller/EnMarche/ProcurationControllerTest.php
Add faq link under header in procuration area
> Add faq link under header in procuration area

- src/Admin/AdherentAdmin.php
- src/ValueObject/Genders.php
- templates/adherent/profile.html.twig
- templates/membership/join.html.twig
- translations/messages.fr.yml
> fix wording input gender

- app/migrations/Version20190225135532.php
- src/DataFixtures/ORM/LoadElectionData.php
Update `renseignez-vous sur les dates` link
> Update information link

- templates/security/adherent_login.html.twig
> wording forget password

- app/config/services/services.xml
- app/migrations/Version20190305110130.php
- src/Admin/JecouteSurveyAdmin.php
- src/Controller/EnMarche/ReferentController.php
- src/Entity/Jecoute/Survey.php
- src/Form/Jecoute/SurveyFormType.php
- templates/admin/jecoute/survey_edit.html.twig
- templates/referent/surveys/_form.html.twig
- templates/referent/surveys/create.html.twig
- templates/referent/surveys/list.html.twig
- translations/messages.fr.yml
Department checked :
City checked :
> [Jecoute] Added Concerned area choice

- tests/Entity/EventTest.php
> fix test timezone EDT

- templates/security/adherent_login.html.twig
set lowercase the first letter on loginEmail input
> set lowercase the first letter on loginEmail input

- .php_cs.dist
- src/Fixer/DoctrineMigrationCleanFixer.php
Do the exact same thing as #3448 but with php_cs_fixer :) 
No need to update makefile, it will be apply with your `make phpcsfix`
> Add custom PHP CS Fixer rule to clean migration

- features/republican_silence.feature
- src/Controller/EnMarche/AdherentMessage/ReferentMessageController.php
- src/Controller/EnMarche/ReferentController.php
- src/RepublicanSilence/CheckRepublicanSilenceListener.php
- templates/referent/_layout.html.twig
- templates/referent/users_list.html.twig
- templates/referent/users_message.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
Reverts EnMarche/en-marche.fr#3376
> Revert "[AdherentMessage] Change old Referent space and fix some bugs"

- features/republican_silence.feature
- src/Controller/EnMarche/AdherentMessage/ReferentMessageController.php
- src/Controller/EnMarche/ReferentController.php
- src/RepublicanSilence/CheckRepublicanSilenceListener.php
- templates/referent/_layout.html.twig
- templates/referent/users_list.html.twig
- templates/referent/users_message.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
> Revert "[Adherent Message] enable referent message"

- src/Entity/BaseEvent.php
- src/Mailer/Message/EventNotificationMessage.php
- tests/Mailer/Message/AbstractEventMessageTest.php
- tests/Mailer/Message/EventNotificationMessageTest.php
Add event description in new event email
> Update event notification message

- composer.json
- composer.lock
- features/admin/adherent.feature
- src/Admin/AdherentAdmin.php
> [ADMIN] Add filter on adherents subscriptions

- features/api/surveys.feature
- features/surveys.feature
- front/style/pages/_referent.scss
- src/Command/ImportJecouteSurveysCommand.php
- src/Controller/Api/JecouteSurveyController.php
- src/Controller/EnMarche/ReferentController.php
- src/DataFixtures/ORM/LoadAdminData.php
- src/DataFixtures/ORM/LoadJecouteQuestionData.php
- src/DataFixtures/ORM/LoadJecouteSurveyData.php
- src/Entity/Jecoute/LocalSurvey.php
- src/Entity/Jecoute/NationalSurvey.php
- src/Entity/Jecoute/Survey.php
- src/Form/Jecoute/DataSurveyFormType.php
- src/Form/Jecoute/QuestionType.php
- src/Form/Jecoute/SurveyFormType.php
- src/Form/Jecoute/SurveyQuestionFormType.php
- src/Jecoute/StatisticsProvider.php
- src/Referent/SurveyExporter.php
- src/Repository/Jecoute/LocalSurveyRepository.php
- src/Repository/Jecoute/NationalSurveyRepository.php
- templates/referent/_form_theme.html.twig
- templates/referent/surveys/_form.html.twig
- templates/referent/surveys/local_surveys_list.html.twig
- templates/referent/surveys/national_surveys_list.html.twig
- templates/referent/surveys/show.html.twig
- templates/referent/surveys/stats.html.twig
- tests/Jecoute/StatisticsExporterTest.php
_Local Survey :_
_National Survey :_
> [Jecoute] Added national surveys on referent space

- src/RepublicanSilence/CheckRepublicanSilenceListener.php
> Apply Republican silence for referent message space

- app/migrations/Version20190416145936.php
- front/style/pages/_assessor.scss
- src/Assessor/AssessorRequestCommand.php
- src/Assessor/AssessorRequestFactory.php
- src/DataFixtures/ORM/LoadAssessorRequestData.php
- src/Entity/AssessorRequest.php
- src/Entity/VotePlace.php
- src/Form/AssessorRequestType.php
- templates/assessor/_fill_assessor_info.html.twig
- templates/assessor/_fill_personal_info.html.twig
- templates/assessor/_valid_summary.html.twig
- tests/Controller/EnMarche/AssessorControllerTest.php
> [Assessor] Added new checkboxes

- src/Command/ImportVotePlacesCommand.php
- src/Repository/AbstractAssessorRepository.php
- src/Repository/AssessorRequestRepository.php
- src/Repository/VotePlaceRepository.php
- templates/assessor_manager/_requests_list.html.twig
- Add SF Style in command
- Fix bug on matching foreign country
- Fix no display on foreign country
> [Assessor] Fix bug on matching foreign country

- templates/procuration/election_rounds.html.twig
- tests/Controller/EnMarche/ProcurationControllerTest.php
> [Procuration] Update procuration request legal mention

- templates/procuration/proposal.html.twig
- tests/Controller/EnMarche/ProcurationControllerTest.php
> [Procuration] Update procuration proxy legal mention

- composer.lock
In order to fix error on Vietnamian numbers, I had to update this lib to get new metadatas
> [Lib Phone Number] Update liphonenumber-for-php 

- app/config/config.yml
- src/Mailer/Message/ProcurationProxyCancelledMessage.php
- src/Procuration/ProcurationProxyMessageFactory.php
- templates/procuration_manager/_requests_list.html.twig
- templates/procuration_manager/associate.html.twig
- templates/procuration_manager/deassociate.html.twig
- templates/procuration_manager/request.html.twig
- tests/Procuration/ProcurationProxyMessageFactoryTest.php
- translations/messages.fr.yml
- Add state field in the manager area
- Fix a typo on flash messages 
- Change default email address
- Add referent in the BCC instead of CC
> [Procuration] Add state in procuration manager area

- app/AppKernel.php
- app/config/services/system.xml
- composer.json
- composer.lock
- src/Entity/AbstractTranslatableEntity.php
- src/Entity/Timeline/Measure.php
- src/Entity/Timeline/Profile.php
- src/Entity/Timeline/Theme.php
- src/Form/EventListener/EmptyTranslationRemoverListener.php
- src/Redirection/Dynamic/RedirectionManager.php
- tests/Entity/TranslatableEntityTest.php
vendors diffs, left side = master, right side this branch:
1. 
2.
3.
> Split symfony monolit package

- app/AppKernel.php
- app/config/config_dev.yml
- composer.json
- composer.lock
> [Dev] Add Doctrine stats bundle

- app/migrations/Version20190426110248.php
- src/Assessor/AssessorRequestCommand.php
- src/Entity/AssessorRequest.php
- src/Form/AssessorRequestType.php
- templates/assessor/_fill_assessor_info.html.twig
- templates/assessor/request.html.twig
- translations/validators.fr.yml
> [Assessor] Automatically filled the assessor city field by postal code

- src/Assessor/Filter/AssessorFilters.php
- src/Assessor/Filter/AssessorRequestFilters.php
- src/Assessor/Filter/VotePlaceFilters.php
- src/Controller/EnMarche/AssessorManagerController.php
- src/DataFixtures/ORM/LoadAdherentData.php
- src/DataFixtures/ORM/LoadAssessorRequestData.php
- templates/assessor_manager/_filters.html.twig
- templates/assessor_manager/_filters_assessor_requests.html.twig
- templates/assessor_manager/requests.html.twig
- templates/assessor_manager/vote_places.twig
- tests/Controller/EnMarche/AssessorManagerControllerTest.php
> [Assessor] Add filters on assessor request and vote places for the manager area

- features/referent-organizational-chart.feature
- front/components/MessageStatusLoader.js
- front/style/manager-space/_tables.scss
- front/style/pages/_committee.scss
- templates/citizen_project/list_actors.html.twig
- templates/committee/_layout.html.twig
- templates/committee/_sidebar.html.twig
- templates/committee/show.html.twig
- templates/committee_manager/list_members.html.twig
- templates/message/preview.html.twig
- templates/referent/edit_referent_person_link.html.twig
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/8004/espace-r%C3%A9f%C3%A9rent-mise-au-style-4
> [REFERENT SPACE] Update style #4

- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
https://app.clubhouse.io/enmarche/story/7925/changer-l-ordre-de-la-navigation-principale
> Change navigation order

- src/Assessor/AssessorRequestExporter.php
- src/Controller/EnMarche/AssessorManagerController.php
- src/Controller/EnMarche/CommitteeManagerController.php
- src/Entity/AssessorRequest.php
- src/Repository/AssessorRequestRepository.php
- templates/assessor_manager/_layout.html.twig
- tests/Controller/EnMarche/AssessorManagerControllerTest.php
> [Assessor] Added export for vote places

- src/Assessor/AssessorRequestHandler.php
- src/Entity/VotePlace.php
- src/Form/AssessorRequestType.php
- src/Repository/VotePlaceRepository.php
- src/VotePlace/VotePlaceManager.php
- templates/assessor/_valid_summary.html.twig
- templates/assessor/request.html.twig
This PR updates the behavior of the vote place name : if the name is empty, we use the vote place code
> [Assessor] Updated select values of the vote place wishes

- templates/procuration/_faq.html.twig
- templates/procuration/_layout.html.twig
- templates/procuration/landing.html.twig
- templates/procuration/proposal.html.twig
- tests/Controller/EnMarche/ProcurationControllerTest.php
https://app.clubhouse.io/enmarche/story/8054/logo-em-espacement-premier-texte-en-mobile
> [Procuration] Fixes logo and spacing

- features/referent-organizational-chart.feature
- front/style/manager-space/_forms.scss
- front/style/manager-space/_tables.scss
- front/style/pages/_org-chart.scss
- templates/citizen_project/_space_layout.html.twig
- templates/citizen_project/list_actors.html.twig
- templates/committee_manager/_space_layout.html.twig
- templates/committee_manager/list_members.html.twig
- templates/message/_layout.html.twig
- templates/message/committee_create.html.twig
- templates/message/create.html.twig
- templates/message/filter.html.twig
- templates/message/filter/referent.html.twig
- templates/message/list.html.twig
- templates/message/preview.html.twig
- templates/referent/edit_referent_person_link.html.twig
- templates/referent/organizational_chart.html.twig
- tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
- tests/Controller/EnMarche/CommitteeManagerControllerTest.php
- translations/messages.fr.yml
- web/images/icons/icn_no-result.svg
https://app.clubhouse.io/enmarche/story/8039/espace-r%C3%A9f%C3%A9rent-am%C3%A9liorations-int%C3%A9gration
> [REFERENT SPACE] Update style #6

- front/style/mixins/_text.scss
- front/style/pages/_donation.scss
- templates/donation/index.html.twig
- templates/membership/donation.html.twig
https://app.clubhouse.io/enmarche/story/8032/modifier-le-wording-sur-la-page-don
> Change wording on donation page

- templates/adherent/create_citizen_project.html.twig
- templates/events/attend.html.twig
- templates/events/invitation.html.twig
- templates/membership/join.html.twig
https://app.clubhouse.io/enmarche/story/7606/mettre-a-jour-les-formulaires-sur-en-marche-fr
> Update CGU on various forms

- front/pages/manage_participants.js
- src/Controller/EnMarche/CommitteeManagerController.php
- src/Repository/CommitteeMembershipRepository.php
- templates/committee_manager/_member_rows.html.twig
- templates/committee_manager/list_members.html.twig
> Add paginator to committee members list

- features/referent-organizational-chart.feature
- front/style/layout/_forms.scss
- templates/committee_manager/_space_layout.html.twig
- templates/committee_manager/contact.html.twig
- templates/message/preview.html.twig
- templates/referent/organizational_chart.html.twig
- tests/Controller/EnMarche/CommitteeManagerControllerTest.php
- translations/messages.fr.yml
https://app.clubhouse.io/enmarche/story/8039/espace-r%C3%A9f%C3%A9rent-am%C3%A9liorations-int%C3%A9gration
> [REFERENT SPACE] Update style #7

- app/config/config_dev.yml
- composer.json
- composer.lock
> Update doctrine bundle

- templates/citizen_project/list_actors.html.twig
- templates/message/filter/referent.html.twig
- templates/referent/users_list.html.twig
https://app.clubhouse.io/enmarche/story/8188/espace-r%C3%A9f%C3%A9rent-hotfixes-1
> [REFERENT SPACE] Various hotfixes #9

- app/config/services/mailchimp.yaml
- front/app.js
- front/components/Loader.js
- front/components/MessageStatisticsWidget.js
- front/components/MessageStatusLoader.js
- front/pages/message_list.js
- front/services/api/ReqwestApiClient.js
- front/style/app.scss
- front/style/layout/_modal.scss
- front/style/mixins/_text.scss
- front/style/pages/_adherent-space.scss
- src/AdherentMessage/StatisticsAggregator.php
- src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
- src/Controller/EnMarche/AdherentMessage/CitizenProjectMessageController.php
- src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
- src/Controller/EnMarche/AdherentMessage/CommonMessageController.php
- src/Entity/Adherent.php
- src/Entity/AdherentMessage/AbstractAdherentMessage.php
- templates/message/create.html.twig
- templates/message/filter.html.twig
- templates/message/list.html.twig
- templates/message/preview.html.twig
> [AdherentMessage] Add stats popin

- src/Controller/EnMarche/ReferentController.php
- src/Referent/ManagedUsersFilter.php
- src/Repository/Projection/ReferentManagedUserRepository.php
- templates/components/_modern_pagination.html.twig
- templates/message/list.html.twig
- templates/referent/users_list.html.twig
- templates/referent/users_message.html.twig
- tests/Repository/Projection/ReferentManagedUserRepositoryTest.php
> [ReferentSpace] improve pagination of user_list

- front/components/DataGrid.js
- front/components/MessageStatisticsWidget.js
- front/components/MessageStatusLoader.js
- front/utils/number.js
- src/Controller/EnMarche/CommitteeManagerController.php
- src/Entity/CommitteeMembership.php
- src/Serializer/XlsxEncoder.php
- templates/citizen_project/dashboard.html.twig
- templates/committee_manager/dashboard.html.twig
- templates/components/_modern_pagination.html.twig
- templates/message/list.html.twig
- templates/message/preview.html.twig
- templates/referent/users_list.html.twig
- tests/Serializer/XlsxEncoderTest.php
> Dimitri.gritsajuk/ch8150 improvements

- migrations/Version20190531150128.php
- src/Entity/Adherent.php
- src/Mailchimp/Synchronisation/RequestBuilder.php
- src/Mailchimp/Webhook/Handler/ProfileUpdateHandler.php
- src/Mailchimp/Webhook/Handler/SubscribeHandler.php
> [Mailchimp] Fix changing unsubscribe status

- src/Command/InitializeEmailSubscriptionHistoryCommand.php
- src/Entity/Adherent.php
- src/Entity/EntityPostAddressTrait.php
- src/Mailchimp/Webhook/Handler/ProfileUpdateHandler.php
- src/Mailchimp/Webhook/Handler/SubscribeHandler.php
- src/Mailchimp/Webhook/Handler/UnsubscribeHandler.php
- tests/Controller/EnMarche/AdherentControllerTest.php
> [Mailchimp] Fix synchro from Admin

- front/style/manager-space/_tables.scss
- templates/citizen_project/list_actors.html.twig
- templates/committee_manager/list_members.html.twig
- templates/referent/users_list.html.twig
https://app.clubhouse.io/enmarche/story/8375/espace-r%C3%A9f-hotfixes-int%C3%A9-11
> [REFERENT SPACE] Various hotfixes #11

- src/Mailchimp/Driver.php
> [Mailchimp] Fix URL for deleting a member

- src/Admin/AdherentAdmin.php
- tests/Admin/AdherentAdminTest.php
> [Admin] Add board member form to adherent page

- src/Mailchimp/Driver.php
> [Mailchimp] Replace HTTP verb for delete request

- migrations/Version20190607151409.php
- src/Entity/ReferentManagedUsersMessage.php
- src/Form/AdherentMessage/ReferentFilterType.php
- src/Referent/ManagedUsersFilter.php
- src/Repository/Projection/ReferentManagedUserRepository.php
- templates/message/filter.html.twig
- templates/message/filter/referent.html.twig
- templates/message/list.html.twig
- templates/referent/users_list.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
- tests/Referent/ManagedUsersFilterTest.php
> [ReferentSpace] Improve referent filters

- src/Mailchimp/Manager.php
- src/Mailchimp/Synchronisation/RequestBuilder.php
> [Mailchimp] Sync adherent roles

- migrations/Version20190605235511.php
- src/Entity/AdherentMessage/Filter/ReferentUserFilter.php
- src/Form/AdherentMessage/ReferentFilterType.php
- src/Mailchimp/Campaign/SegmentConditionsBuilder.php
- src/Mailchimp/Synchronisation/Request/MemberRequest.php
- src/Mailchimp/Synchronisation/RequestBuilder.php
- templates/message/filter/referent.html.twig
> [Mailchimp] Add adhesion date filter

- src/Mailchimp/MailchimpSubscriptionLabelMapping.php
> [McWebhook] Update SMS checkbox via webhook

- src/Form/AdherentMessage/ReferentFilterType.php
> [ReferentSpace] set optional adhesion date filter

- tests/Controller/EnMarche/ApplicationRequestControllerTest.php
Please consider this fix to have some real values for testing
> Fix some tests

- features/surveys.feature
- front/listeners/cookies-consent.js
- front/style/layout/_base.scss
- front/style/layout/_vendors.scss
https://app.clubhouse.io/enmarche/story/8699/int%C3%A9gration-de-la-banni%C3%A8re-des-cookies
> Change cookies's bar style

- migrations/Version20190621095409.php
- src/Admin/ApplicationRequestRunningMateRequestAdmin.php
- src/Admin/ApplicationRequestVolunteerRequestAdmin.php
- src/DataFixtures/ORM/LoadApplicationRequestRunningMateRequestData.php
- src/DataFixtures/ORM/LoadApplicationRequestVolunteerRequestData.php
- src/Entity/ApplicationRequest/ApplicationRequest.php
- src/Form/ApplicationRequest/ApplicationRequestType.php
- templates/application_request/_form.html.twig
- templates/assessor_manager/_layout.html.twig
- templates/citizen_project/_space_layout.html.twig
- templates/committee_manager/_space_layout.html.twig
- templates/deputy/_layout.html.twig
- templates/municipal_chief/_layout.html.twig
- templates/procuration_manager/_layout.html.twig
- templates/referent/_layout.html.twig
- tests/Controller/EnMarche/ApplicationRequestControllerTest.php
- translations/messages.fr.yml
> [ApplicationRequest] add gender field

- front/components/MessageStatusLoader.js
- front/pages/message_filters.js
- src/Controller/EnMarche/AdherentMessage/AbstractMessageController.php
- templates/message/filter/municipal_chief.html.twig
- templates/message/filter/referent.html.twig
> [AdherentMessage] add another reset  filter button

- features/municipal_chief_space.feature
- features/referent_space.feature
- front/components/MessageStatusLoader.js
- front/style/layout/_base.scss
- templates/application_request/municipal/_running_mate_row.js.twig
- templates/application_request/municipal/_volunteer_row.js.twig
- templates/municipal_chief/municipal/running_mate/list.html.twig
- templates/municipal_chief/municipal/volunteer/list.html.twig
- templates/referent/municipal/running_mate/list.html.twig
- templates/referent/municipal/volunteer/list.html.twig
> [CandidateList] Add gender and in_my_team columns

- front/style/pages/_committee.scss
> Fix css committee waiting for approval

- app/config/services/admin.xml
- src/Admin/Extension/ManageMediaExtension.php
- src/Admin/Formation/AxeAdmin.php
- src/Admin/Formation/ModuleAdmin.php
- src/Entity/EntityMediaTrait.php
- src/Entity/Media.php
- tests/Admin/ArticleAdminTest.php
> [Admin] make media optional field for formation admins

- app/config/services/services.xml
- src/Mailchimp/Campaign/CampaignRequestBuilder.php
- tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
> [AdherentMessage] Change FromName

- app/config/services/services.xml
- src/Command/MailchimpDeleteContactsFromCsvCommand.php
- src/Mailchimp/Manager.php
- src/Mailchimp/Synchronisation/Command/RemoveApplicationRequestCandidateCommand.php
- src/Mailchimp/Synchronisation/Handler/RemoveApplicationRequestCandidateCommandHandler.php
> [Mailchimp] Add command for removing MC contact

- features/municipal_chief_space.feature
- features/referent_space.feature
- src/Admin/ApplicationRequestRunningMateRequestAdmin.php
- src/Mailchimp/Webhook/Handler/AdherentUnsubscribeHandler.php
- templates/admin/citizen_project_category/list_status.html.twig
- templates/application_request/_form.html.twig
- templates/application_request/municipal/_running_mate_detail.html.twig
- templates/application_request/request.html.twig
> [MailchimpWebhook] dispatch event on unsubscribe call

- src/ApplicationRequest/ApplicationRequestRepository.php
- src/ApplicationRequest/Listener/UpdateAdherentRelationSubscriber.php
- src/Controller/EnMarche/ApplicationRequestCandidate/AbstractApplicationRequestController.php
- src/Controller/EnMarche/ApplicationRequestCandidate/MunicipalChiefSpaceController.php
- src/Controller/EnMarche/ApplicationRequestCandidate/ReferentSpaceController.php
- src/Controller/EnMarche/MunicipalChiefController.php
- src/Mailchimp/Synchronisation/Request/MemberRequest.php
- src/Mailchimp/Synchronisation/RequestBuilder.php
- src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
- templates/adherent/_list_my_sections.html.twig
- templates/application_request/space/detail.html.twig
- templates/application_request/space/edit_tags.html.twig
- templates/application_request/space/list.html.twig
- templates/application_request/space/my_team.html.twig
- templates/components/_nav_mobile.html.twig
- templates/municipal_chief/_application_request_datagrid.html.twig
- templates/municipal_chief/_layout.html.twig
- templates/referent/_application_request_datagrid.html.twig
- templates/referent/_layout.html.twig
> Chief my team

- front/style/manager-space/_base-layout.scss
- src/Entity/ApplicationRequest/ApplicationRequest.php
- src/Form/ApplicationRequest/ApplicationRequestTagsType.php
- templates/application_request/space/_running_mate_detail.html.twig
- templates/application_request/space/_running_mate_row.js.twig
- templates/application_request/space/_volunteer_row.js.twig
- templates/municipal_chief/adherent/list.html.twig
> [MunicipalChief] improve application request detail page

- src/Controller/EnMarche/ApplicationRequestCandidate/AbstractApplicationRequestController.php
- src/Controller/EnMarche/MunicipalChiefController.php
- templates/adherent/_list_my_sections.html.twig
- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
- templates/referent/_layout.html.twig
> Muni space remove canary

- src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
> [MunicipalChief] fix order by

- templates/referent/_layout.html.twig
> [ReferentSpace] add canary mode to municipal tab

- features/municipal_chief_space.feature
- features/referent_space.feature
- front/style/manager-space/_base-layout.scss
- src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
- templates/application_request/space/_running_mate_detail.html.twig
- templates/application_request/space/_running_mate_row.js.twig
- templates/application_request/space/_volunteer_detail.html.twig
- templates/application_request/space/_volunteer_row.js.twig
- templates/components/_nav_desktop.html.twig
- templates/municipal_chief/_application_request_datagrid.html.twig
- templates/referent/_application_request_datagrid.html.twig
> [MunicipalSpace] Add date columns

- .eslintrc
- front/components/DataGrid.js
- front/kernel.js
- front/utils/url.js
- templates/municipal_chief/_application_request_datagrid.html.twig
- templates/referent/_application_request_datagrid.html.twig
> [DataGrid] add sortable columns

- app/config/parameters.yml.dist
- app/config/services/services.xml
- front/components/MessageStatusLoader.js
- migrations/Version20190705103704.php
- src/Entity/AdherentMessage/Filter/MunicipalChiefFilter.php
- src/Form/AdherentMessage/MunicipalChiefFilterType.php
- src/Mailchimp/Campaign/MailchimpObjectIdMapping.php
- src/Mailchimp/Campaign/SegmentConditionsBuilder.php
- src/Mailchimp/Synchronisation/ApplicationRequestTagLabelEnum.php
- templates/application_request/space/list.html.twig
- templates/application_request/space/my_team.html.twig
- templates/message/filter/municipal_chief.html.twig
- tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
> [MunicipalChief] allow contact my team

- migrations/Version20190712133940.php
- src/Entity/AdherentMessage/Filter/MunicipalChiefFilter.php
- src/Form/AdherentMessage/MunicipalChiefFilterType.php
- src/Mailchimp/Campaign/SegmentConditionsBuilder.php
- templates/message/filter/municipal_chief.html.twig
> [MunicipalChief] Add 4 checkboxes of contact group

- migrations/Version20190712154749.php
- src/Entity/AdherentMessage/Filter/MunicipalChiefFilter.php
- src/Form/AdherentMessage/MunicipalChiefFilterType.php
- src/Mailchimp/Campaign/CampaignRequestBuilder.php
- src/Mailchimp/Campaign/Request/EditCampaignRequest.php
- src/Mailchimp/Campaign/SegmentConditionsBuilder.php
- templates/message/filter/municipal_chief.html.twig
> [MunicipalChief] Allow contact adherent of city

- features/referent_space.feature
- src/Controller/EnMarche/ApplicationRequestCandidate/AbstractApplicationRequestController.php
- src/Controller/EnMarche/ApplicationRequestCandidate/MunicipalChiefSpaceController.php
- src/Controller/EnMarche/ApplicationRequestCandidate/ReferentSpaceController.php
- templates/referent/_layout.html.twig
- tests/Controller/EnMarche/BoardMemberControllerTest.php
> [ReferentSpace] lock municipal tab for referent from Paris

- src/Entity/ApplicationRequest/ApplicationRequest.php
> [ApplicationRequest] Allow foreign address

- src/AdherentMessage/Listener/AdherentMessageChangeSubscriber.php
- src/AdherentMessage/MailchimpCampaign/Handler/MunicipalChiefMailchimpCampaignHandler.php
> [Mailchimp] Fix filter synchro process

- features/bootstrap/FeatureContext.php
- features/municipal_chief_space.feature
- front/components/DataGrid.js
- front/components/MessageStatusLoader.js
- front/style/layout/_base.scss
- front/style/layout/_utilities.scss
- front/style/manager-space/_base-layout.scss
- templates/application_request/space/list.html.twig
- templates/application_request/space/my_team.html.twig
- templates/citizen_project/edit.html.twig
- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
- templates/event_manager/event_create.html.twig
- templates/municipal_chief/_layout.html.twig
- templates/municipal_chief/adherent/list.html.twig
- templates/referent/institutional_events/list.html.twig
- templates/referent/organizational_chart.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
done: 
- "contacter mon équipe" btn style updated
- refacto alert modals
- add flag emoji on mobile
- fix menu display on responsive (small laptops)
- add picto "no result" in react empty table
- city and cp on 2 lines (instead of 1)
- "nouveau besoin..." size reduced and increased chezvous's url btn
- wording
> [MunicipalSpace] Various hotfixes #1

- src/Entity/AdherentMessage/AbstractAdherentMessage.php
- src/Mailchimp/Campaign/SegmentConditionBuilder/ReferentToCandidateConditionBuilder.php
- templates/message/filter/referent.html.twig
> [ReferentSpace] fix sync candidate filters

- features/municipal_chief_space.feature
https://51641-76485630-gh.circle-artifacts.com/3/screenshots/fail_1563802007_default__I_can_define_application_request_as_added_to_my_team.png
> [Municipal Space] Fixed random test fail

- src/Controller/EnMarche/EventManager/AbstractEventManagerController.php
- src/Controller/EnMarche/EventManager/EventManagerMunicipalChief.php
- src/Controller/EnMarche/EventManager/EventManagerReferent.php
- src/Entity/BaseEvent.php
- src/Entity/EntityPostAddressTrait.php
- src/Entity/MunicipalEvent.php
- src/Event/EventCommandHandler.php
- src/Event/EventFactory.php
- src/Repository/MunicipalEventRepository.php
> [MunicipalEvent] Expose event on API

- front/style/layout/_base.scss
- front/style/manager-space/_base-layout.scss
- src/ApplicationRequest/ApplicationRequestRepository.php
- src/Controller/EnMarche/MunicipalChiefController.php
- src/Repository/AdherentMessageRepository.php
- src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
- src/Repository/MunicipalEventRepository.php
- templates/adherent/_list_my_sections.html.twig
- templates/components/_nav_mobile.html.twig
- templates/municipal_chief/_layout.html.twig
- templates/municipal_chief/home.html.twig
> [MunicipalSpace] Add landing to municipal chief space

- app/config/services/services.xml
- src/Command/UnregisterAdherentsCommand.php
> Use CSV lib with storage service in unregisterAdherent command

- src/Controller/EnMarche/ApplicationRequestCandidate/AbstractApplicationRequestController.php
- src/Controller/EnMarche/ApplicationRequestCandidate/MunicipalChiefSpaceController.php
- src/Controller/EnMarche/ApplicationRequestCandidate/ReferentSpaceController.php
- templates/application_request/space/list.html.twig
- templates/referent/_layout.html.twig
> [ReferentSpace] open volunteers list for referent from Paris

- src/DataFixtures/ORM/LoadAdherentData.php
- templates/chart_dialog.html.twig
- templates/municipal_chief/_layout.html.twig
- translations/messages.fr.yml
> [MunicipalSpace] Add chart dialog

- src/AdherentMessage/Filter/FilterFormFactory.php
- src/Form/AdherentMessage/ReferentFilterType.php
- templates/message/filter/referent.html.twig
> [ReferentMessage] hide runningMate checkbox

- features/api/adherents.feature
- src/Entity/Adherent.php
- tests/Controller/Api/OAuthServerControllerTest.php
> [API] detail municipal chief role on API

- app/config/services/services.xml
- src/Normalizer/MunicipalEventNormalizer.php
- src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
- templates/application_request/space/list.html.twig
> [MunicipalEvent] Add url property to API response

- src/Admin/AdherentAdmin.php
- src/Entity/MunicipalChiefManagedArea.php
- src/Twig/AdherentRuntime.php
- templates/admin/adherent/list_status.html.twig
- templates/event_manager/_event_row.js.twig
- translations/messages.fr.yml
> Rename Municipal Chief role label

- front/style/manager-space/_base-layout.scss
- front/style/mixins/_colors.scss
- templates/message/_layout.html.twig
- templates/message/filter.html.twig
- templates/message/list.html.twig
> [Mailchimp] display service warning

- src/Form/ApplicationRequest/ApplicationRequestListFilterType.php
- src/Repository/ApplicationRequest/AbstractApplicationRequestRepository.php
- templates/application_request/space/list.html.twig
> [MunicipalSpace] Change isAdherent field type to select

- src/Controller/EnMarche/FormationController.php
- src/Entity/Adherent.php
- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
> Add new role for formation space access

- app/config/services/services.xml
- migrations/Version20190930215529.php
- src/Controller/EnMarche/CitizenActionController.php
- src/Controller/EnMarche/EventController.php
- src/Entity/NewsletterSubscription.php
- src/Event/EventListener/EventRegistrationNewsletterSubscriber.php
- src/Event/EventRegistrationFactory.php
- src/Mailchimp/Synchronisation/MemberRequest/NewsletterMemberRequestBuilder.php
- src/Mailchimp/Synchronisation/Request/MemberRequest.php
- src/Newsletter/NewsletterTypeEnum.php
- src/Newsletter/NewsletterValueObject.php
- templates/events/attend.html.twig
- tests/Controller/EnMarche/AbstractEventControllerTest.php
- tests/Controller/EnMarche/CitizenActionControllerTest.php
- tests/Controller/EnMarche/EventControllerTest.php
> Create newsletter from event registration if checked

- templates/events/attend.html.twig
> Change wording on Event registration page

- app/config/config_prod.yml
- app/config/services/system.xml
- composer.json
- composer.lock
- src/Logging/ActivationStrategy.php
> Revert "[Logger] mute http client error"

- front/style/manager-space/_base-layout.scss
- templates/municipal_chief/home.html.twig
- re-display bloc
- optimise css
> [ChefMun] Display "maisondesimpressions" bloc on space

- front/style/manager-space/_tables.scss
- src/AdherentMessage/Filter/FilterFormFactory.php
- src/Controller/EnMarche/CommitteeManagerController.php
- src/Event/Filter/ListFilterObject.php
- src/Form/AdherentMessage/CommitteeFilterType.php
- src/Form/CommitteeMemberFilterType.php
- src/Repository/CommitteeMembershipRepository.php
- templates/committee_manager/_member_rows.html.twig
- templates/committee_manager/list_members.html.twig
- templates/components/_modern_pagination.html.twig
- templates/form_theme.html.twig
- tests/Controller/EnMarche/CommitteeManagerControllerTest.php
> [Committee] Add filters to adherent list page

- app/config/config.yml
- src/AdherentMessage/MailchimpCampaign/Handler/CommitteeMailchimpCampaignHandler.php
- src/Event/Filter/ListFilterObject.php
- src/Form/AdherentMessage/CommitteeFilterType.php
- src/Form/CommitteeMemberFilterType.php
- src/Repository/CommitteeMembershipRepository.php
- templates/citizen_project/list_actors.html.twig
- templates/committee_manager/_member_rows.html.twig
- templates/committee_manager/list_members.html.twig
- templates/form_theme.html.twig
- templates/message/filter/committee.html.twig
- templates/referent/users_list.html.twig
- translations/messages.fr.yml
> [Committee] Add status filter to adherent list page

- src/Controller/EnMarche/AdherentMessage/CommitteeMessageController.php
> [CommitteMessage] Add default filtre on message creation

- front/style/pages/_donation.scss
- src/Command/MailchimpSignUpEmailsCommand.php
- src/Controller/EnMarche/DonationController.php
> [Don] Fix background image url

- src/Controller/EnMarche/UserController.php
- src/Entity/Adherent.php
- src/Form/AdherentEmailSubscriptionType.php
- src/Subscription/SubscriptionTypeEnum.php
- templates/user/set_email_notifications.html.twig
- tests/CitizenProject/CitizenProjectManagerTest.php
- tests/Controller/EnMarche/AdherentControllerTest.php
- tests/Controller/EnMarche/MembershipControllerTest.php
> Remove unused CP notif checkbox

- templates/jecoute/_form.html.twig
- templates/jecoute/create.html.twig
> [Jecoute] Change form wording

- templates/jecoute/_form_theme.html.twig
> Change label of suggested question

- front/app.js
- front/services/form/CKEditor.js
- front/style/app.scss
- front/style/manager-space/_forms.scss
- package.json
- src/Controller/UploadDocumentController.php
- src/Form/AdherentMessage/AdherentMessageType.php
- templates/message/create.html.twig
- yarn.lock
> Add new CKEditor5 for adherent message form

- src/Admin/ProgrammaticFoundation/ApproachAdmin.php
- src/Admin/ProgrammaticFoundation/MeasureAdmin.php
- src/Admin/ProgrammaticFoundation/ProjectAdmin.php
- src/Admin/ProgrammaticFoundation/SubApproachAdmin.php
- src/Entity/ProgrammaticFoundation/Project.php
- Project add 500
- Reorder columns
- Add missing tags field
> Programmatic foundation fixes

- src/Mailer/Message/DataSurveyAnsweredMessage.php
> [MailTransac] fix empty first name

- templates/message/create.html.twig
> [AdherentMessage] rollback CKEditor to v4

- src/Entity/Mooc/Mooc.php
- translations/validators.fr.yml
> [Mooc] add image/video validation

- composer.lock
- templates/referent/users_list.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
```
- Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0): Downloading (100%)         
- Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0): Downloading (100%)         
- Updating symfony/polyfill-util (v1.11.0 => v1.12.0): Downloading (100%)         
- Updating symfony/polyfill-php56 (v1.11.0 => v1.12.0): Downloading (100%)         
- Updating symfony/polyfill-intl-icu (v1.11.0 => v1.12.0): Downloading (100%)         
- Updating symfony/polyfill-apcu (v1.11.0 => v1.12.0): Downloading (100%)         
- Updating symfony/intl (v3.4.26 => v3.4.35): Downloading (100%)         
- Updating symfony/http-foundation (v3.4.26 => v3.4.35): Downloading (100%)         
- Updating symfony/event-dispatcher (v3.4.26 => v3.4.35): Downloading (100%)         
- Updating symfony/polyfill-php72 (v1.11.0 …
```
> [Referent] Always show phone number and display SMS/MMS preferences

- src/DataFixtures/ORM/LoadEventData.php
- src/Repository/EventRepository.php
- templates/programmatic_foundation/view_measure.html.twig
@Remg one test 👻 in less in our life (I hope)
> [Test] Update Event begin date for fixing randomly failed test

- front/style/content/_program.scss
- templates/program/index.html.twig
Story details: https://app.clubhouse.io/enmarche/story/10570
> Add reminder links on programme page

- src/Entity/BaseEvent.php
- src/Serializer/CitizenActionICalHandler.php
- src/Serializer/EventICalHandler.php
- tests/Controller/EnMarche/CitizenActionControllerTest.php
- tests/Controller/EnMarche/EventManagerControllerTest.php
- tests/Serializer/EventIcalHandlerTest.php
Reverts EnMarche/en-marche.fr#4097
> Revert "Add timezone to dates in Ical format"

- front/app.js
- front/components/AdherentCommitteeList.js
- front/pages/referent_user_list.js
- front/services/api/ReqwestApiClient.js
- front/style/layout/_modal.scss
- front/style/manager-space/_base-layout.scss
- migrations/Version20191129174907.php
- src/Collection/CommitteeMembershipCollection.php
- src/Controller/Api/AdherentController.php
- src/DataFixtures/ORM/LoadReferentManagedUserData.php
- src/Entity/Adherent.php
- src/Entity/CommitteeMembership.php
- src/Entity/EntityNameSlugTrait.php
- src/Entity/Projection/ReferentManagedUser.php
- src/Entity/Projection/ReferentManagedUserFactory.php
- src/Repository/Projection/ReferentManagedUserRepository.php
- templates/referent/users_list.html.twig
> [ReferentSpace] display adherent committee modal

- src/Controller/Api/CrmParisController.php
- tests/Controller/Api/CrmParisControllerTest.php
Reverts EnMarche/en-marche.fr#4144
> Revert "No content returned for CrmParis endpoint, just a test string"

- app/config/routing.yml
- app/config/security.yml
- composer.json
- composer.lock
- src/Entity/Administrator.php
- templates/security/admin_google_authenticator.html.twig
- tests/Controller/EnMarche/Security/AdminSecurityControllerTest.php
https://github.com/scheb/two-factor-bundle/blob/master/UPGRADE.md#2x-to-3x
+
https://github.com/scheb/two-factor-bundle/blob/master/UPGRADE.md#3x-to-4x
> Update scheb/two-factor-bundle from v2.* to v4.*

- front/components/ProgrammaticFoundation/Measure.js
- front/components/ProgrammaticFoundation/ProgrammaticFoundation.js
To be reverted once we want to highlight leading measures
> [SOCLE] Do not highlight leading measures

- front/components/AdherentCommitteeList.js
- migrations/Version20200106163511.php
- src/Entity/SenatorArea.php
- src/Security/Voter/ManagedUserVoter.php
> Fix senator area and committee modal

- src/Controller/EnMarche/InvitationController.php
- src/Form/InvitationType.php
- src/Form/SimpleInvitationType.php
- templates/committee_manager/list_members.html.twig
- templates/invitation/sent.html.twig
- templates/invitation/simple_form.html.twig
- templates/managed_users/list.html.twig
> [InvitationForm] add new simple form for connected users

- src/Controller/EnMarche/InvitationController.php
- templates/committee_manager/_space_layout.html.twig
- templates/committee_manager/list_members.html.twig
- templates/deputy/_layout.html.twig
- templates/invitation/_confirmation.html.twig
- templates/invitation/adherent_space/_base_deputy_space.html.twig
- templates/invitation/adherent_space/_base_referent_space.html.twig
- templates/invitation/adherent_space/_base_senator_space.html.twig
- templates/invitation/adherent_space/_base_supervisor_space.html.twig
- templates/invitation/adherent_space/_layout.html.twig
- templates/invitation/adherent_space/invitation_form.html.twig
- templates/invitation/adherent_space/sent.html.twig
- templates/invitation/form.html.twig
- templates/invitation/sent.html.twig
- templates/referent/_layout.html.twig
- templates/senator/_layout.html.twig
> Use Adherent space layouts for invitation page

- features/procuration_request.feature
- features/referent_space.feature
- features/surveys.feature
- front/style/layout/_forms.scss
- templates/base.html.twig
Reverts EnMarche/en-marche.fr#4212
> Revert "Use another class for the email issue banner"

- src/Donation/DonationRequest.php
- src/Validator/FrenchAddressOrNationalityDonation.php
- src/Validator/FrenchAddressOrNationalityDonationValidator.php
- translations/validators.fr.yml
> Do not accept donations from foreigners not living in France

- front/style/manager-space/_base-layout.scss
- templates/message/_message_limit_message.html.twig
- templates/message/list.html.twig
https://app.clubhouse.io/enmarche/story/10859/coup-de-pinceau-sur-la-limite-de-mails
> Various style

- front/style/manager-space/_tables.scss
- src/Controller/EnMarche/AssessorSpace/AbstractAssessorSpaceController.php
- src/Entity/VotePlace.php
- src/Entity/VoteResult.php
- templates/assessor_space/attribution_form.html.twig
- translations/messages.fr.yml
> Show results status for each vote place

- src/Intl/FranceCitiesBundle.php
post-deploy:
```
UPDATE procuration_requests
SET vote_city_name = 'Saint-Maur-des-Fossés'
WHERE vote_postal_code = '94210'
;
UPDATE procuration_proxies
SET vote_city_name = 'Saint-Maur-des-Fossés'
WHERE vote_postal_code = '94210'
;
```
> Fix city name for postalcode 94210

- migrations/Version20200224124920.php
- src/Committee/CommitteeManager.php
- src/Controller/EnMarche/AdherentController.php
- src/Controller/EnMarche/CommitteeController.php
- src/Entity/CommitteeMembership.php
- src/Repository/CommitteeMembershipRepository.php
- templates/adherent/activities.html.twig
- templates/adherent/committees.html.twig
- templates/adherent/events.html.twig
- Add enableVoting in CommitteeMembership
- Add repository method to check unicity
- Add migration
> Feature ETQM je peux indiquer où je vote

- src/Committee/CommitteeManager.php
- Atomic flush for disable/enable voting ops
> Hotfix - Flush voting committee

- migrations/Version20200304164953.php
- src/Committee/CommitteeManager.php
- src/Controller/EnMarche/CommitteeController.php
- src/Entity/Committee.php
- src/Entity/CommitteeCandidacy.php
- src/Entity/CommitteeElection.php
- src/Entity/CommitteeMembership.php
- src/Exception/CommitteeMembershipException.php
- src/Repository/CommitteeCandidacyRepository.php
- src/Repository/CommitteeElectionRepository.php
- src/Twig/CommitteeElectionExtension.php
- src/Twig/CommitteeRuntime.php
- templates/committee/show.html.twig
- Add basic db structure
- Add Voting action
> Feature Candidater

- front/style/app.scss
- front/style/layout/_forms-em.scss
- front/style/layout/_layout.scss
- front/style/layout/_modal.scss
- front/style/pages/_adherent-activities.scss
- templates/adherent/activities.html.twig
- templates/adherent/committees.html.twig
- templates/adherent/events.html.twig
- templates/components/_nav_desktop.html.twig
- templates/components/_nav_mobile.html.twig
- tests/Controller/EnMarche/AdherentControllerTest.php
Need someone to :
- dynamise tabs "Mes comités / Mes événements"
- dynamise sub-tabs  "Passés / A venir" (events)
> [AdherentBinome] Fix style on "Mes activités"

- migrations/Version20200305174710.php
- src/Committee/CommitteeFactory.php
- src/Entity/Committee.php
- src/Entity/CommitteeElection.php
- tests/Controller/EnMarche/AdherentControllerTest.php
post-deploy:
```
INSERT INTO committee_election (
committee_id
)
SELECT
c.id
FROM committees AS c
WHERE NOT EXISTS (
SELECT 1
FROM committee_election AS ce
WHERE ce.committee_id = c.id
LIMIT 1
)
;
```
> Create and assign CommitteeElection on CommitteeCreation

- app/config/services/services.xml
- migrations/Version20200319171717.php
- src/Controller/Admin/AdminElectedRepresentativeController.php
- src/DataFixtures/ORM/LoadZoneCategoryData.php
- src/DataFixtures/ORM/LoadZoneData.php
- src/Entity/ElectedRepresentative/Mandate.php
- src/Entity/ElectedRepresentative/PoliticalFunction.php
- src/Entity/ElectedRepresentative/Zone.php
- src/Entity/ElectedRepresentative/ZoneCategory.php
- src/Entity/Epci.php
- src/Form/ElectedRepresentative/MandateType.php
- src/Form/ElectedRepresentative/PoliticalFunctionType.php
- src/Form/ElectedRepresentative/ZoneType.php
- src/Repository/ElectedRepresentative/ZoneRepository.php
- templates/form_theme_admin.html.twig
After deploying this PR we should import EPCI data to `epci` using data from `data.en-marche.fr` project. 
And run this script:
```SQL
INSERT INTO enmarche.elected_representative_zone_category (id, name) VALUES 
(1, 'Ville'),
(2, 'EPCI'),
(3, 'Département'),
(4, 'Région'),
(5, 'Circonscription'),
(6, 'Corse'),
(7, 'FDE')
;
INSERT INTO elected_representative_zone (name, category_id) SELECT CONCAT(name,' (',postal_codes,')'), 1 FROM cities;
INSERT INTO elected_representative_zone (name, category_id) SELECT name, 2 FROM epci WHERE name != '';
INSERT INTO elected_representative_zone (name, category_id) SELECT CONCAT(name,' (',code,')'), 3 FROM department;
INSERT INTO elected_representative_zone (name, category_id) SELECT name, 4 FROM region;
INSERT INTO elected_representative_zone (name, …
```
> [ADMIN] Add ElectedRepresentative zones

- features/committee_vote.feature
- front/app.js
- front/listeners/confirm-modal.js
- templates/adherent/my_activity_committees.html.twig
- templates/committee/show.html.twig
> Add EM confirmation modal widget

- front/pages/profile_update.js
- front/services/address/AutocompletedAddressForm.js
- front/services/address/GooglePlaceAutocomplete.js
> Update adresse autocomplete on my-account page

- src/Admin/DonationAdmin.php
- src/Admin/DonatorAdmin.php
- src/Controller/Admin/AdminDonatorController.php
- src/Donation/DonatorExtractCommand.php
- src/Donation/DonatorExtractCommandHandler.php
- src/Form/Admin/DonatorExtractType.php
- src/Repository/AdherentRepository.php
- templates/admin/donator/extract/extract_button.html.twig
- templates/admin/donator/extract/request.html.twig
- translations/messages.fr.yml
> Create tool to extract data from list of emails

- src/Event/Filter/ListFilterObject.php
- src/Form/CommitteeMemberFilterType.php
- src/Repository/CommitteeMembershipRepository.php
- templates/committee_manager/_member_rows.html.twig
- templates/committee_manager/list_members.html.twig
- tests/Controller/EnMarche/CommitteeManagerControllerTest.php
> [CommitteeMembers] add Voters filter

- src/Command/ImportDonationsCommand.php
- src/Donation/DonatorManager.php
To execute AFTER executing the `app:donations:import` command:
```SQL
-- Etape 1: Supprimer les donateurs doublons (matching sur firstname + lastname + email)
-- creation d'une table temporaire des donateurs avec canonical
CREATE TABLE temp_donators_canonical(
donator_id INT(6) NOT NULL,
canonical VARCHAR(255) DEFAULT NULL,
original_donator_id INT(6) DEFAULT NULL
);
-- on insere une ligne par donateur en créant le canonical
INSERT INTO temp_donators_canonical(
donator_id,
canonical
)
SELECT
d.id,
CONCAT_WS(
'-',
d.first_name,
d.last_name,
d.email_address
)
FROM donators d
WHERE d.email_address IS NOT NULL
;
-- on index le canonical
CREATE INDEX temp_donators_canonical_canonical ON temp_donators_canonical(canonical)
;
-- on rempli les original_donator_id (en prenant l'id le plus bas) des …
```
> Fix import donations command

- composer.lock
```
Package operations: 0 installs, 42 updates, 0 removals
- Updating symfony/asset (v3.4.38 => v3.4.40): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
Downloading (100%)         
- Updating symfony/doctrine-bridge (v3.4.38 => v3.4.40): Downloading (100%)         
- Updating symfony/dotenv (v4.4.5 => v4.4.8): Loading from cache
- Updating symfony/intl (v4.4.5 => v4.4.8): Downloading (100%)         
- Updating symfony/cache (v3.4.38 => v3.4.40): Downloading (100%)         
- Updating symfony/expression-language (v3.4.38 => v3.4.40): Loading from cache
- Updating …
```
> Sf update to 3.4.40

- config/services/services.xml
- src/Entity/AdherentMessage/Filter/BasicUserFiltersTrait.php
- src/Form/AdherentMessage/AdherentZoneFilterType.php
- src/Form/EventListener/IncludeExcludeFilterRoleListener.php
- src/Form/FilterRoleType.php
- src/Mailchimp/Campaign/SegmentConditionBuilder/AbstractConditionBuilder.php
- src/Mailchimp/Campaign/SegmentConditionBuilder/AdherentInterestConditionBuilder.php
- templates/message/filter/_adherent_zone_filter.html.twig
- templates/message/filter/referent.html.twig
- tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
- translations/messages.fr.yml
[ch11418]
In the "exclude" select, the first row is disabled because it is selected in the "include" select
> Change role display in message adherent filter

- front/components/Modal.js
- front/services/utils/imageCropper.js
- front/style/app.scss
- front/style/content/_em-tooltip.scss
- templates/committee/_election_box.html.twig
> Dimitri/ch11442/ajouter un petit à côté de conseil territorial

- config/packages/old_sound_rabbit_mq.yaml
https://www.rabbitmq.com/heartbeats.html#false-positives
> Increase rabbitmq heartbeats config

- templates/message/filter/referent.html.twig
> Fix auto select checkboxes on page load

- package.json
- yarn.lock
and we will close this #4441 PR
> Remove unused macaddress JS package

- migrations/Version20200507124731.php
- src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
- src/Controller/EnMarche/ReferentController.php
- src/Entity/ReferentOrganizationalChart/ReferentPersonLink.php
- src/Entity/ReferentTag.php
- src/Entity/ReferentTeamMember.php
- src/EventListener/ManageReferentTeamMembersListener.php
- src/Form/ReferentPersonLinkType.php
- src/Intl/FranceCitiesBundle.php
- src/ManagedUsers/ManagedUsersFilter.php
- src/Repository/CommitteeRepository.php
- src/Repository/Projection/ManagedUserRepository.php
- templates/javascript.js.twig
- templates/referent/_form_theme.html.twig
- templates/referent/edit_referent_person_link.html.twig
- tests/Intl/FranceCitiesBundleTest.php
- translations/messages.fr.yml
Reverts EnMarche/en-marche.fr#4457
> Revert "Revert "Add restricted committees & cities to limited co-referents""

- config/services/services.xml
- src/Form/ManagedUsers/ManagedUsersFilterType.php
- src/ManagedUsers/ManagedUsersFilter.php
- src/Repository/Projection/ManagedUserRepository.php
- templates/managed_users/filter_form.html.twig
- templates/managed_users/list.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
the produced part of the request is:
```
WHERE ...
AND (isCommitteeMember = 0|1 OR (include1 OR include2))
AND exclude1 
AND exclude2
```
> role filter new style on adherent form

- src/Repository/CommitteeMembershipRepository.php
> Add null results for non subscribed filter

- templates/admin/donator/edit.html.twig
> [Admin] fix donator page and check phone number

- src/ManagedUsers/ManagedUsersFilter.php
> Fix : export does not handle inclusions and exclusions

- config/services/admin.xml
> Rename some admin menu entries

- src/Adherent/AdherentExtractCommand.php
- src/Adherent/AdherentExtractCommandHandler.php
- src/Admin/DonationAdmin.php
- src/Controller/EnMarche/UserController.php
- src/Donation/DonationManager.php
- src/Donation/DonationValueObject.php
- src/Donation/DonatorExtractCommand.php
- src/Donation/DonatorExtractCommandHandler.php
- src/Entity/Donation.php
- src/Extract/AbstractEmailExtractCommandHandler.php
- src/Repository/DonationRepository.php
- templates/admin/donator/extract/extract_button.html.twig
- templates/user/my_donation.html.twig
- translations/messages.fr.yml
> Crm dons v1.7

- config/services.yaml
- config/services/services.xml
- migrations/Version20200608134934.php
- migrations/Version20200608142421.php
- src/Adherent/Certification/CertificationAuthorityManager.php
- src/Adherent/Certification/CertificationManager.php
- src/Adherent/Certification/CertificationRequestBlockCommand.php
- src/Adherent/Certification/CertificationRequestDocumentManager.php
- src/Adherent/Certification/CertificationRequestProcessCommand.php
- src/Adherent/Certification/CertificationRequestProcessCommandHandler.php
- src/Adherent/Certification/CertificationRequestRefuseCommand.php
- src/Adherent/Certification/Handlers/CertificationRequestDuplicateHandler.php
- src/Adherent/Certification/Handlers/CertificationRequestHandlerInterface.php
- src/Command/CertificationRequestProcessTimeoutCommand.php
- src/DataFixtures/ORM/LoadCertificationData.php
- src/Entity/CertificationRequest.php
- src/Repository/AdherentRepository.php
- src/Repository/CertificationRequestRepository.php
- templates/admin/certification_request/_macros.html.twig
- templates/admin/certification_request/block.html.twig
- templates/admin/certification_request/refuse.html.twig
- templates/admin/certification_request/show.html.twig
- templates/certification_request/home.html.twig
- tests/Adherent/Certification/CertificationAuthorityManagerTest.php
- tests/Adherent/Certification/CertificationManagerTest.php
- translations/messages.fr.yml
> Add Handler for CertificationRequest process & detect duplicates

- src/Form/ApplicationRequest/ApplicationRequestType.php
- src/Form/CertificationRequestType.php
- src/Form/CitizenProjectCommandType.php
- src/Form/EventRegistrationType.php
- src/Form/RequiredCheckboxType.php
- templates/certification_request/form.html.twig
- tests/Controller/EnMarche/CertificationRequestControllerTest.php
> Add checkbox to accept certification requests cgu

- features/access_delegation.feature
- src/Entity/MyTeam/DelegatedAccess.php
> [My Team] Change predefined roles

- docker/prod/pool.conf
> Improve php config

- config/services.yaml
- src/Adherent/Certification/CertificationAuthorityManager.php
- src/Adherent/Certification/CertificationManager.php
- src/Adherent/Certification/CertificationRequestMessageNotifier.php
- src/Adherent/Certification/CertificationRequestNotifier.php
- src/Form/DonationRequestType.php
- src/Mailer/Message/CertificationRequestApprovedMessage.php
- src/Mailer/Message/CertificationRequestBlockedMessage.php
- src/Mailer/Message/CertificationRequestPendingMessage.php
- src/Mailer/Message/CertificationRequestRefusedMessage.php
- tests/Adherent/Certification/CertificationAuthorityManagerTest.php
- tests/Controller/EnMarche/CertificationRequestControllerTest.php
> Certification emails

- src/Adherent/Certification/CertificationRequestNotifier.php
- src/Entity/CertificationRequest.php
- templates/admin/certification_request/show.html.twig
- templates/certification_request/home.html.twig
> [Certification] translate reason in email

- docker/prod/pool.conf
Reverts EnMarche/en-marche.fr#4552
> Revert "Improve php config"

- migrations/Version20200623204535.php
- src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
- src/DataFixtures/ORM/LoadElectedRepresentativeData.php
- src/ElectedRepresentative/Filter/ListFilter.php
- src/Entity/ElectedRepresentative/ElectedRepresentative.php
- src/Entity/ElectedRepresentative/Mandate.php
- src/Entity/ElectedRepresentative/PoliticalFunction.php
- src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
- src/ValueObject/Genders.php
- templates/admin/elected_representative/list_type.html.twig
- templates/elected_representative/list.html.twig
- tests/Controller/EnMarche/ReferentControllerTest.php
- translations/messages.fr.yml
[ch11740]
[ch11736]
[ch11738]
[ch11735]
[ch11727]
> ElectedRepresentative list

- migrations/Version20200624175233.php
- src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
- src/ElectedRepresentative/UserListDefinitionHistoryManager.php
- src/Entity/ElectedRepresentative/Reporting/UserListDefinitionHistory.php
- src/UserListDefinition/UserListDefinitionManager.php
- templates/admin/elected_representative/list_type.html.twig
- tests/UserListDefinition/UserListDefinitionManagerTest.php
> Keep track of UserListDefinitions movements

- src/Controller/EnMarche/AdherentMessage/DelegatedDeputyMessageController.php
- src/Controller/EnMarche/AdherentMessage/DelegatedReferentMessageController.php
- src/Controller/EnMarche/AdherentMessage/DelegatedSenatorMessageController.php
- src/Controller/EnMarche/CitizenProjects/DelegatedReferentCitizenProjectsController.php
- src/Controller/EnMarche/Committee/DelegatedReferentCommitteeController.php
- src/Controller/EnMarche/DelegatedDeputyController.php
- src/Controller/EnMarche/DelegatedInvitationController.php
- src/Controller/EnMarche/Designation/DelegatedReferentDesignationController.php
- src/Controller/EnMarche/ElectedRepresentative/DelegatedReferentElectedRepresentativeController.php
- src/Controller/EnMarche/EventManager/DelegatedDeputyEventManagerController.php
- src/Controller/EnMarche/EventManager/DelegatedReferentEventManagerController.php
- src/Controller/EnMarche/EventManager/DelegatedSenatorEventManagerController.php
- src/Controller/EnMarche/Jecoute/DelegatedJecouteReferentController.php
- src/Controller/EnMarche/ManagedUsers/DelegatedDeputyManagedUsersController.php
- src/Controller/EnMarche/ManagedUsers/DelegatedReferentManagedUsersController.php
- src/Controller/EnMarche/ManagedUsers/DelegatedSenatorManagedUsersController.php
- tests/Controller/EnMarche/AdherentMessage/AbstractMessageControllerTest.php
merge after #4578 
these urls are not in prod yet, we can change them.
Set a proper url corresponding to the space on the page
> Change url from "espace-delegue" to "espace-partage"

- composer.lock
- src/Entity/Adherent.php
- src/Entity/MyTeam/DelegatedAccess.php
- symfony.lock
- templates/adherent/_list_my_sections.html.twig
An empty value in db, returns an array with one empty element (but the array is not)
> Fix empty accesses link

- src/Controller/EnMarche/ElectedRepresentative/SenatorElectedRepresentativeController.php
- templates/elected_representative/_base_senator.html.twig
- templates/senator/_layout.html.twig
> Add elected representative tabs to senators

- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
@ottaviano validated by Victor
> Show elected representative from department for deputy

- src/Controller/EnMarche/ElectedRepresentative/AbstractElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
- src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
- templates/elected_representative/list.html.twig
- templates/lre/_layout.html.twig
> Allow to filter by lre labels on LRE space + change social network column to phone

- src/AdherentMessage/Filter/FilterFactory.php
- src/AdherentMessage/MailchimpCampaign/Handler/ReferentElectedRepresentativeMailchimpCampaignHandler.php
- src/Controller/EnMarche/AccessDelegatorTrait.php
- src/Entity/AdherentMessage/Filter/ReferentElectedRepresentativeFilter.php
- src/Entity/AdherentMessage/MailchimpCampaign.php
- src/Form/AdherentMessage/ReferentElectedRepresentativeFilterType.php
- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
- src/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoter.php
- templates/message/filter/referent_elected_representative.html.twig
> [Referent] improve elected representative filter page

- src/Command/MailchimpCreateTagFromReferentTagCommand.php
Reverts EnMarche/en-marche.fr#4654
> Revert "Create all referents tags for newly added MailchimpSegment entity"

- front/style/pages/_territorial-council.scss
- src/Entity/TerritorialCouncil/Candidacy.php
- src/Entity/TerritorialCouncil/CandidacyInvitation.php
- src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
- src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitation.php
- src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitationValidator.php
- templates/territorial_council/candidacy_step2_invitation.html.twig
- translations/validators.fr.yml
> [TerritorialCouncil] Candidacy: validate invited membership

- src/Form/VotingPlatform/Candidacy/TerritorialCouncilCandidacyType.php
- templates/territorial_council/_election_box.html.twig
> [TerritorialCouncil] Candidacy: fix photo validation

- src/Controller/EnMarche/TerritorialCouncil/CandidatureController.php
- src/DataFixtures/ORM/LoadTerritorialCouncilCandidacyData.php
- src/DataFixtures/ORM/LoadTerritorialCouncilMembershipData.php
- src/Entity/TerritorialCouncil/Candidacy.php
- src/Entity/TerritorialCouncil/CandidacyInvitation.php
- src/Entity/TerritorialCouncil/TerritorialCouncilMembership.php
- src/Entity/TerritorialCouncil/TerritorialCouncilQualityEnum.php
- src/Form/TerritorialCouncil/CandidacyQualityType.php
- src/Security/Voter/TerritorialCouncil/AccessVoter.php
- src/Security/Voter/TerritorialCouncil/CandidatureVoter.php
- src/Validator/TerritorialCouncil/ValidTerritorialCouncilCandidacyInvitationValidator.php
- templates/form_theme.html.twig
- templates/territorial_council/_election_box.html.twig
- templates/territorial_council/_sidebar.html.twig
- templates/territorial_council/index.html.twig
- tests/Controller/EnMarche/TerritorialCouncil/CandidatureControllerTest.php
- tests/Controller/EnMarche/TerritorialCouncil/TerritorialCouncilControllerTest.php
> [TerritorialCouncil] Candidacy: improve candidacy voter

- src/ElectedRepresentative/Filter/ListFilter.php
- src/Entity/ElectedRepresentative/ElectedRepresentativeTypeEnum.php
- src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
- templates/elected_representative/list.html.twig
- templates/form_theme.html.twig
- tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
- translations/messages.fr.yml
[ch11910]
=====
**pre** deploy:
- make sure custom merge field `CONTACT_TYPE` exists on `elected_representative` mailchimp list
**post** deploy:
- sync all elected representatives again:
```
bin/console mailchimp:sync:all-elected-representatives --env=prod
```
> Elected representative filters

- src/Entity/ElectedRepresentative/ZoneCategory.php
> Assign circo & dpt to Euro Deputies

- src/Entity/ElectedRepresentative/ZoneCategory.php
> Regional councils are elected in a department

- src/Command/MailchimpSyncAllMembershipsCommand.php
> [TerritorialCouncil] sync all memberships with MC

- config/services.yaml
- config/services/http_client.yaml
- migrations/Version20200825164048.php
- src/Command/Geo/Helper/Persister.php
- src/Command/Geo/Helper/Summary.php
- src/Command/Geo/SyncZoneCommand.php
- src/Command/Geo/UpdateCantonCommand.php
- src/Command/Geo/UpdateFranceCommand.php
- src/Entity/ElectedRepresentative/Zone.php
- tests/Command/Geo/UpdateFranceCommandTest.php
Commands to update and harmonize french administrative divisions tables.
- entities: country, region, departement, city
- source: https://geo.api.gouv.fr/
- entity: canton
- source: https://www.insee.fr/fr/information/4316069
- entity: zone
- source: geo tables
- this command fills also the relation among zones (parent/child) 
```
Usage:
app:geo:update-france [options]
Options:
--dry-run         Execute the algorithm without persisting any data.
-h, --help            Display this help message
-q, --quiet           Do not output any message
-V, --version         Display this application version
--ansi            Force ANSI output
--no-ansi         Disable ANSI output
-n, --no-interaction  Do not ask any interactive question
-e, --env=ENV         The Environment name. [default: "dev"] …
```
> Commands to update and harmonize french administrative divisions tables

- migrations/Version20200819100824.php
- src/Command/RemindActivatedMembershipCommand.php
- src/Entity/Adherent.php
- src/Mailer/Message/AdherentMembershipReminderMessage.php
- src/Membership/MembershipRequestHandler.php
[ch11689]
post-deploy: 
```
- name: remind-activated-memberships
settings:
command: |
["php", "/app/bin/console", "app:membership:remind-activated", "--quiet", "-e", "prod", "48"]
schedule: "0 9 * * *"
```
> Send membership email reminder

- migrations/Version20200819100824.php
- src/Command/RemindActivatedMembershipCommand.php
- src/Entity/Adherent.php
- src/Mailer/Message/AdherentMembershipReminderMessage.php
- src/Membership/MembershipRequestHandler.php
Reverts EnMarche/en-marche.fr#4788
> Revert "Revert "Send membership email reminder""

- front/style/voting-platform/_candidacy.scss
- front/style/voting-platform/_results.scss
- src/DataFixtures/ORM/LoadElectionData.php
- src/DataFixtures/ORM/LoadVotingPlatformElectionData.php
- src/Entity/VotingPlatform/ElectionPool.php
- src/Repository/VotingPlatform/ElectionRepository.php
- src/Twig/VotingPlatformRuntime.php
- templates/committee/_election_box.html.twig
> [Committee] Display designed adherents in election box

- migrations/Version20200911155434.php
- src/Entity/EntityNullablePostAddressTrait.php
- src/Entity/ThematicCommunity/AdherentMembership.php
- src/Entity/ThematicCommunity/Contact.php
- src/Entity/ThematicCommunity/ContactMembership.php
- src/Entity/ThematicCommunity/ElectedRepresentativeMembership.php
- src/Entity/ThematicCommunity/ThematicCommunity.php
- src/Entity/ThematicCommunity/ThematicCommunityMembership.php
> Add thematic community entities

- src/Entity/BaseEvent.php
> Fix length constraint on event name

- migrations/Version20200928143320.php
- src/Entity/AdherentMandate/TerritorialCouncilAdherentMandate.php
- src/Entity/TerritorialCouncil/PoliticalCommitteeMembership.php
- src/Entity/VotingPlatform/ElectionPoolCodeEnum.php
- src/TerritorialCouncil/PoliticalCommitteeManager.php
- src/VotingPlatform/Handler/UpdateMandateForElectedAdherentCommandHandler.php
Execute this query to update `adherent_mandate` and to check that there is no more `additionally_elected` quality.
```sql
UPDATE adherent_mandate am
INNER JOIN voting_platform_candidate c ON c.adherent_id = am.adherent_id AND am.`type` = 'territorial_council'
INNER JOIN voting_platform_candidate_group cg ON cg.id = c.candidate_group_id
INNER JOIN voting_platform_election_pool ep ON cg.election_pool_id = ep.id
INNER JOIN voting_platform_election_entity ent ON ent.election_id = ep.election_id and ent.territorial_council_id = am.territorial_council_id
SET am.quality = ep.code, am.is_additionally_elected = 1
WHERE am.quality = 'additionally_elected'
;
SELECT * FROM adherent_mandate am
WHERE am.quality = 'additionally_elected'
;
```
> [CoPol][TerritorialCouncil] Add additionally elected

- features/api/surveys.feature
- features/referent_space.feature
- features/surveys.feature
- src/Admin/JecouteLocalSurveyAdmin.php
- src/Admin/JecouteNationalSurveyAdmin.php
- src/Controller/Admin/AdminJecouteController.php
- src/DataFixtures/ORM/LoadJecouteDataAnswerData.php
- src/DataFixtures/ORM/LoadJecouteDataSurveyData.php
- src/DataFixtures/ORM/LoadJecouteQuestionData.php
- src/DataFixtures/ORM/LoadJecouteSurveyData.php
- src/Entity/Jecoute/SurveyQuestion.php
- src/Exporter/SurveyExporter.php
- src/Repository/Jecoute/DataSurveyRepository.php
- templates/admin/jecoute/_exports.html.twig
> Export national survey data

- src/Controller/Admin/AdminJecouteController.php
- src/Controller/EnMarche/Jecoute/AbstractJecouteController.php
- src/Entity/Jecoute/SurveyQuestion.php
- src/Exporter/SurveyExporter.php
questions not answered by everyone questions where not added in the header row
> Do not export all data from front and fixes from questions not answered by everyone

- front/style/content/_em-tooltip.scss
- templates/thematic_community/members.html.twig
> Add tooltips on icons

- templates/certification_request/form.html.twig
> [Certification] Add preview on document choose + wording

- migrations/Version20201012113658.php
- src/Command/Geo/SyncZonesCommand.php
- src/Command/Geo/UpdateBoroughsCommand.php
- src/Entity/Geo/Borough.php
- src/Entity/Geo/Zone.php
~Enhance `app:geo:update-france` to handle boroughs.~
Create `app:geo:update-boroughs` to handle french boroughs.
Zones are updated as well.
No official data is used at this time.
> Add borough level to the geo mapping

- src/Adherent/Certification/CertificationRequestRefuseCommand.php
- src/Vision/IdentityDocumentParser.php
- src/Vision/ImageAnnotations.php
- tests/Vision/IdentityDocumentParserTest.php
- translations/messages.fr.yml
[ch12603]
[ch12593]
[ch12554]
[ch12592]
[ch12594]
[ch12596]
> Certifications ocr fixes 4

- src/Entity/AdherentCommitmentEnum.php
- templates/adherent_profile/commitment.html.twig
- translations/messages.fr.yml
> engagement fixes

- front/style/pages/_adherent-profile.scss
- front/style/pages/_join.scss
- src/AdherentProfile/AdherentProfile.php
- src/Entity/Adherent.php
- src/Form/AdherentProfileType.php
- templates/adherent/profile.html.twig
- templates/javascript.js.twig
- templates/membership/join.html.twig
> Add mandates in profile with help text

- config/services.yaml
- config/services/platform.xml
- config/services/services.xml
- migrations/Version20201028115643.php
- src/AdherentProfile/AdherentProfileHandler.php
- src/Entity/Adherent.php
- src/Entity/EntityZoneTrait.php
- src/Entity/ZoneableEntity.php
- src/Membership/MembershipRequestHandler.php
- src/Referent/ReferentZoneManager.php
- src/Utils/AreaUtils.php
```sql
INSERT INTO adherent_zone (adherent_id, zone_id)
SELECT a.id, z.id FROM adherents a, geo_zone z
WHERE a.address_country = 'FR' AND z.code = SUBSTRING(a.address_city_insee, 7, 5)
;
INSERT INTO adherent_zone (adherent_id, zone_id)
SELECT a.id, z.id FROM adherents a, geo_zone z
WHERE a.address_country != 'FR' AND z.code = a.address_country
;
```
> Add geo zone to adherents

- front/style/content/_em-tooltip.scss
- front/style/pages/_territorial-council.scss
- front/style/voting-platform/_candidacy.scss
- src/DataFixtures/ORM/LoadAdherentData.php
- src/DataFixtures/ORM/LoadCommitteeData.php
- src/Entity/EntityDesignationTrait.php
- src/Entity/VotingPlatform/Designation/Designation.php
- templates/adherent_profile/_layout.html.twig
- templates/committee/_sidebar.html.twig
- templates/committee/candidacy/candidacy_invitation.html.twig
- templates/committee/candidacy/candidacy_list.html.twig
- templates/committee/candidacy/form_committee_supervisor.html.twig
- templates/committee/election_box/_committee_supervisor.html.twig
[ch12675]
[ch12685]
[ch12694]
[ch12677]
[ch12675]
> [Committee] Update candidacy wording

- src/Controller/EnMarche/ElectedRepresentative/AbstractElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/DeputyElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/SenatorElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/SenatorialCandidateElectedRepresentativeController.php
- src/ElectedRepresentative/Filter/ListFilter.php
- src/Entity/Geo/City.php
- src/Entity/ReferentManagedArea.php
- src/Entity/ReferentTag.php
- src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
- src/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoter.php
- templates/elected_representative/list.html.twig
- tests/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeControllerTest.php
- tests/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoterTest.php
- translations/messages.fr.yml
> List elected in "espaces référent" and LRE using new geo zone system

- src/Entity/TerritorialCouncil/OfficialReportDocument.php
> [PoliticalCommittee] fix name of downloaded files

- composer.json
- composer.lock
- config/bundles.php
- config/packages/twig.yaml
- src/Controller/Api/ZoneController.php
- src/Controller/EnMarche/ElectedRepresentative/AbstractElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
- src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
- src/Repository/Geo/ZoneRepository.php
- symfony.lock
- templates/elected_representative/list.html.twig
- translations/messages.fr.yml
> Filter elected via geo zone in "espace référent" and LRE

- src/AdherentProfile/AdherentProfile.php
- src/Admin/AdherentAdmin.php
- src/Controller/EnMarche/UserController.php
- src/Entity/Adherent.php
- src/Form/EventListener/BoardMemberListener.php
- src/Repository/AdherentRepository.php
- src/Validator/UniqueMembershipValidator.php
> [Adherent] validate email address on update

- src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php
- src/Repository/Geo/ZoneRepository.php
This PR:
- Don't search in parent zone when searching for text (front)
- Honor zone filter in elected list (backoffice)
> Fix zone filter

- src/Repository/Geo/ZoneRepository.php
Doctrine QueryBuilder `setMaxResults()`'s method doesn't work properly with join.
This PR uses Paginator as a workaround.
> Use paginator to allow slice select with join

- features/adherent_candidate.feature
- templates/candidate/filter_form.html.twig
Fix remaining missed zone filter replacement in candidate space
> Fix zone filter in candidate space

- src/Controller/EnMarche/MyTeam/AbstractMyTeamController.php
- src/Entity/MyTeam/DelegatedAccess.php
- src/Repository/Projection/ManagedUserRepository.php
+ allow adding delegated access to the same adherent in different spaces
> Show adherents with delegated access for specific space

- src/Command/Geo/UpdateDistrictsCommand.php
Commands to run with-in the deployment:
```bash
app/console app:geo:update-districts
app/console app:geo:sync-zones
```
> Fix cities' INSEE code building in update districts command

- src/Controller/Admin/AdminZoneController.php
- src/Entity/ElectedRepresentative/MandateTypeEnum.php
- src/Repository/Geo/ZoneRepository.php
Update mapping between Mandate and Zone type to fit the new zone breakdown system.
This PR fixes special zone filtering for mandates in Corsica.
> Refactor zone filtering in mandate form

- src/Controller/Api/ZoneController.php
- src/Controller/EnMarche/ElectedRepresentative/DeputyElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/LreElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/ReferentElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/SenatorElectedRepresentativeController.php
- src/Controller/EnMarche/ElectedRepresentative/SenatorialCandidateElectedRepresentativeController.php
- src/Controller/EnMarche/ManagedUsers/CandidateManagedUsersController.php
- src/Controller/EnMarche/ManagedUsers/DeputyManagedUsersController.php
- src/Controller/EnMarche/ManagedUsers/LegislativeCandidateManagedUsersController.php
- src/Controller/EnMarche/ManagedUsers/ReferentManagedUsersController.php
- src/Controller/EnMarche/ManagedUsers/SenatorManagedUsersController.php
- src/Form/AdherentMessage/AdherentGeoZoneFilterType.php
- src/Form/AdherentMessage/ReferentElectedRepresentativeFilterType.php
- src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php
- src/Form/ManagedUsers/AbstractManagedUsersFilterType.php
- src/Geo/ManagedZoneProvider.php
- src/Validator/ManagedZone.php
- src/Validator/ManagedZoneValidator.php
- templates/message/filter/candidate.html.twig
This PR fix also a bug in the messaging area
https://github.com/EnMarche/en-marche.fr/pull/5094/files#diff-a229ac7f462f745c27baf5e382c75805deb1f33e94fd5bc8941634d55a1dd218
> Validate zone before filtering users

- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
- src/Repository/Projection/ManagedUserRepository.php
This PR fix searching for users outside of the boundary delineated by the managed zones.
> Take in account both managed and zones on filtering

- src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php
- src/Repository/Projection/ManagedUserRepository.php
Reverts EnMarche/en-marche.fr#5118
> Revert "Take in account both managed and zones on filtering"

- composer.lock
```
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "3.4.*"
Prefetching 32 packages 🎶 💨
- Downloading (100%)
Package operations: 0 installs, 47 updates, 0 removals
- Updating symfony/flex (v1.9.4 => v1.10.0): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
- Updating composer/package-versions-deprecated (1.3.0 => 1.8.0): Loading from cache
- Updating symfony/thanks (v1.2.9 => v1.2.10): Loading from cache
- Updating symfony/asset (v3.4.45 => …
```
> Update to sf 3.4.47

- migrations/Version20201202140626.php
- src/Command/Geo/UpdateCityReplacementsCommand.php
- src/Entity/Geo/City.php
Commands to call on deploy:
1. `app:geo:update-city-replacements`
2. `app:geo:sync-zone`
> Introduce association between city and its replacement

- migrations/Version20201210112852.php
- src/Admin/VotingPlatform/DesignationAdmin.php
- src/Entity/VotingPlatform/Designation/Designation.php
- templates/committee/election_box/_committee_supervisor.html.twig
- templates/voting_platform/_layout_base.html.twig
- templates/voting_platform/_layout_committee_supervisor.html.twig
- templates/voting_platform/confirmation.html.twig
- templates/voting_platform/finish.html.twig
- templates/voting_platform/index.html.twig
- templates/voting_platform/results.html.twig
- templates/voting_platform/results/_stats_block.html.twig
> [VotingPlatform] update designation/election wording

- templates/components/_dropdown_user_mobile.html.twig
- templates/components/_nav_desktop.html.twig
> Add link eurodéputés renaissance dans Nav Bar

- src/Command/Geo/ZoneMatcherCommand.php
- src/Entity/AddressHolderInterface.php
- src/Entity/BaseEvent.php
- src/Entity/Committee.php
- src/Geo/ZoneMatcher.php
This PR introduces the `app:geo:zone-matcher` command that matches zones for a given entity.
The target entity **MUST**:
- implements `App\Entity\AddressHolderInterface` (a new interface), a way to reach the data source
- implements `App\Entity\ZoneableEntity`, the target that receives the found zones (itself)
The command **skips** matching in these cases (doesn't change the current relation):
- `Address` is empty
- no `Zone` is found
Features:
- Pick a single entity filling the `--id` option
Current support:
- `App\Entity\Committee`
- `App\Entity\CitizenAction`
- `App\Entity\InstitutionalEvent`
- `App\Entity\Event`
- `App\Entity\MunicipalEvent`
---
```
bin/console app:geo:zone-matcher --help
```
```
Description:
Assigns zones to entities
Usage:
app:geo:zone-matcher [options] [--] …
```
> Introduce app:geo:zone-matcher command

- config/packages/prod/framework.yaml
> [Security] Improve cookie settings

- src/Repository/CommitteeRepository.php
- src/Validator/UniqueCommitteeValidator.php
[EM-399]
[EM-399]: https://em-tech-innovation.atlassian.net/browse/EM-399
> [Committee] Fix committee address validator

- config/packages/doctrine.yaml
- config/packages/security.yaml
- config/services.yaml
- migrations/Version20210324151041.php
- src/Security/AdherentLoginTimestampRecorder.php
- templates/security/adherent_login.html.twig
> Add Session TTL with Remember me feature

- front/app.js
- front/components/BatchActionsWidget.js
- front/pages/batch_actions.js
- src/Coalition/Filter/CauseFilter.php
- src/Controller/EnMarche/Coalition/CausesController.php
- src/Entity/Coalition/Cause.php
- src/Repository/Coalition/CauseRepository.php
- templates/coalition/causes_list.html.twig
- tests/Controller/EnMarche/Coalition/CausesControllerTest.php
- tests/TestHelperTrait.php
> [Coalition space] Batch actions

- templates/coalition/causes_list.html.twig
Reverts EnMarche/en-marche.fr#5546
> Revert "[EM-592][Cause] replace image by link on cause list"

- config/packages/nelmio_cors.yaml
This reverts commit d3319df28c75a6fd0b11c5f89b184c9b6d9918c9.
> [EM-711] Revert "Enable CORS config for deconnexion route"

- .circleci/config.yml
- .github/workflows/lint.yml
- config/packages/assets_version.yaml
> add lint job to github actions

- composer.lock
```
- Upgrading symfony/asset (v4.4.20 => v4.4.22)
- Upgrading symfony/browser-kit (v4.4.20 => v4.4.22)
- Upgrading symfony/cache (v4.4.21 => v4.4.22)
- Upgrading symfony/cache-contracts (v2.2.0 => v2.4.0)
- Upgrading symfony/config (v4.4.20 => v4.4.22)
- Upgrading symfony/console (v4.4.21 => v4.4.22)
- Upgrading symfony/debug (v4.4.20 => v4.4.22)
- Upgrading symfony/dependency-injection (v4.4.21 => v4.4.22)
- Upgrading symfony/deprecation-contracts (v2.2.0 => v2.4.0)
- Upgrading symfony/doctrine-bridge (v4.4.21 => v4.4.22)
- Upgrading symfony/error-handler (v4.4.21 => v4.4.22)
- Upgrading symfony/expression-language (v4.4.20 => v4.4.22)
- Upgrading symfony/filesystem (v4.4.21 => v4.4.22)
- Upgrading symfony/form (v4.4.21 => v4.4.22)
- Upgrading symfony/framework-bundle (v4.4.21 => …
```
> [PHP] Update symfony 4.4.22

- features/api/causes.feature
- src/Coalition/Filter/CauseFilter.php
- src/DataFixtures/ORM/LoadCauseData.php
- src/Form/Coalition/CauseFilterType.php
- src/Repository/Coalition/CauseRepository.php
- templates/coalition/causes_list.html.twig
- tests/Controller/EnMarche/Coalition/CausesControllerTest.php
> [EM-548] Enhance Causes filter form

- src/Adherent/AdherentInterestsMigrationHandler.php
- src/Adherent/Command/AdherentMigrateInterestsCommand.php
- src/Adherent/Handler/AdherentMigrateInterestsCommandHandler.php
- src/Command/MigrateAdherentInterestsCommand.php
- src/Controller/EnMarche/AdherentController.php
- src/Form/AdherentMessage/AdherentZoneFilterType.php
- src/Form/ManagedUsers/ManagedUsersFilterType.php
- src/Form/SummaryType.php
- templates/adherent/_profile_menu.html.twig
- templates/adherent_profile/_layout.html.twig
- templates/components/_dropdown_user_desktop.html.twig
- templates/components/_dropdown_user_mobile.html.twig
- templates/managed_users/filter_form.html.twig
- templates/message/filter/_adherent_zone_filter.html.twig
- templates/message/filter/referent.html.twig
- tests/Controller/EnMarche/AdherentControllerTest.php
- tests/Controller/EnMarche/SummaryManagerControllerTest.php
This PR should be reverted once interests have been migrated.
> [EM-582] Adherents interests migration

- composer.lock
Reverts EnMarche/en-marche.fr#6051
> Revert "Bump symfony/phpunit-bridge from 5.3.3 to 5.3.4"

- composer.lock
Reverts EnMarche/en-marche.fr#6050
> Revert "Bump symfony/twig-bridge from 4.4.26 to 4.4.27"

- Dockerfile
- docker/prod/nginx.conf
Reverts EnMarche/en-marche.fr#6083
> Revert "Change APP_ENV to dev"

- composer.lock
```
Lock file operations: 0 installs, 17 updates, 0 removals
- Upgrading symfony/browser-kit (v4.4.25 => v4.4.27)
- Upgrading symfony/config (v4.4.26 => v4.4.27)
- Upgrading symfony/console (v4.4.26 => v4.4.29)
- Upgrading symfony/dom-crawler (v4.4.25 => v4.4.27)
- Upgrading symfony/finder (v4.4.25 => v4.4.27)
- Upgrading symfony/form (v4.4.26 => v4.4.27)
- Upgrading symfony/framework-bundle (v4.4.26 => v4.4.27)
- Downgrading symfony/mime (v5.3.4 => v4.4.27)
- Upgrading symfony/options-resolver (v4.4.25 => v4.4.27)
- Upgrading symfony/polyfill-intl-grapheme (v1.23.0 => v1.23.1)
- Upgrading symfony/process (v4.4.26 => v4.4.27)
- Upgrading symfony/security-acl (v3.1.2 => v3.2.0)
- Upgrading symfony/security-bundle (v4.4.26 => v4.4.27)
- Upgrading symfony/stopwatch (v4.4.25 => v4.4.27)
- …
```
> [PHP] Update Symfony

- src/Controller/Api/AdherentList/ColumnsConfigurationController.php
- src/Controller/Api/Audience/RetrieveAudiencesController.php
- src/Controller/Api/ScopeTrait.php
- src/ManagedUsers/ColumnsConfigurator.php
- src/Scope/AuthorizationChecker.php
- src/Scope/Exception/InvalidFeatureCodeException.php
- src/Scope/Exception/InvalidScopeException.php
- src/Scope/Exception/NotFoundScopeGeneratorException.php
- src/Scope/Exception/ScopeExceptionInterface.php
- src/Scope/Exception/ScopeQueryParamMissingException.php
- src/Scope/GeneralScopeGenerator.php
- src/Scope/Generator/AbstractScopeGenerator.php
- src/Scope/Generator/CandidateScopeGenerator.php
- src/Scope/Generator/DeputyScopeGenerator.php
- src/Scope/Generator/NationalScopeGenerator.php
- src/Scope/Generator/ReferentScopeGenerator.php
- src/Scope/Generator/ScopeGeneratorInterface.php
- src/Scope/Generator/SenatorScopeGenerator.php
- src/Scope/Scope.php
- src/ValueObject/Genders.php
[EM-1179]
[EM-1179]: https://em-tech-innovation.atlassian.net/browse/EM-1179
> [Contacts] add column config endpoint

- features/api/scopes.feature
- src/DataFixtures/ORM/LoadScopeData.php
- src/DataFixtures/ORM/LoadTeamData.php
- src/Entity/Adherent.php
- src/Entity/Team/Team.php
- src/Scope/AppEnum.php
- src/Scope/Generator/PhoningScopeGenerator.php
- src/Scope/ScopeEnum.php
- tests/Scope/GeneralScopeGeneratorTest.php
```sql
INSERT INTO `scope` (code, name, apps)
VALUES ('phoning', 'Appelant', 'jemarche')
;
```
> Add phoning scope

- migrations/Version20210824172202.php
- src/Entity/Jecoute/DataSurvey.php
Merge this PR after execution of the command from PR https://github.com/EnMarche/en-marche.fr/pull/6153
> Change DataSurvey table

- src/Kernel.php
test phpunit: 
before: 
`Time: 03:03.874, Memory: 3.69 GB`
after:
`Time: 02:27.514, Memory: 2.39 GB`
> [Symfony] Enable inline Dumper factories

- src/Security/Voter/DataCornerVoter.php
- templates/candidate/_layout.html.twig
- templates/components/_dropdown_user_mobile.html.twig
- templates/components/_nav_desktop.html.twig
- tests/Security/Voter/DataCornerVoterTest.php
Reverts EnMarche/en-marche.fr#6249
> Revert "Datacorner delegated accesses"

- composer.json
- composer.lock
Reverts EnMarche/en-marche.fr#6288
> Revert "Update dependency behat/mink-browserkit-driver to v1.3.4"

- templates/components/_footer.html.twig
Hi,
This link goes to a 404 page, I don't know if it's the correct new URL. Let me know if not.
> Change URL for Renew Europe

- features/api/profile.feature
- features/registration.feature
- src/DataFixtures/ORM/LoadSubscriptionTypeData.php
- templates/candidate/_table.html.twig
- templates/managed_users/_table.html.twig
- templates/membership/join.html.twig
- templates/municipal_chief/adherent/list.html.twig
- templates/referent/territorial_council/members.html.twig
post deploy: 
```
UPDATE subscription_type 
SET label = 'Recevoir les informations sur les actions militantes du mouvement par téléphone'
WHERE code = 'militant_action_sms'
;
```
> Change phone SubscriptionType label

- composer.json
- composer.lock
Reverts EnMarche/en-marche.fr#6476
> Revert "Update dependency odolbeau/phone-number-bundle to v3.5.0"

- features/api/pap_campaigns.feature
- migrations/Version20211117174035.php
- src/Controller/Api/Pap/GetPapCampaignSurveyConfigController.php
- src/DataFixtures/ORM/LoadPapAddressData.php
- src/DataFixtures/ORM/LoadPapCampaignHistoryData.php
- src/Entity/Pap/CampaignHistory.php
Need to remove all entries from `pap_campaign_history` before running the migration.
> [PAP] Add Building to CampaignHistory

- features/api/pap_campaigns.feature
- src/Entity/Pap/Campaign.php
[EM-1730]
[EM-1730]: https://em-tech-innovation.atlassian.net/browse/EM-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [API][PAP] Change get campaign endpoint for DC

- README.md
> Update CI/CD badge

- config/services/services.xml
- features/api/events.feature
- src/Api/Doctrine/BaseEventExtension.php
- src/Api/Doctrine/JecouteNewsExtension.php
Reverts EnMarche/en-marche.fr#6644
> Revert "[ToRevert] test sentry on app"

- composer.lock
```
- Upgrading symfony/flex (v1.17.5 => v1.17.6): Extracting archive
- Upgrading symfony/mime (v4.4.34 => v4.4.36): Extracting archive
- Upgrading symfony/http-foundation (v4.4.34 => v4.4.36): Extracting archive
- Upgrading symfony/var-dumper (v4.4.34 => v4.4.36): Extracting archive
- Upgrading symfony/debug (v4.4.31 => v4.4.36): Extracting archive
- Upgrading symfony/error-handler (v4.4.34 => v4.4.36): Extracting archive
- Upgrading symfony/http-kernel (v4.4.35 => v4.4.36): Extracting archive
- Upgrading symfony/property-access (v4.4.30 => v4.4.36): Extracting archive
- Upgrading symfony/intl (v4.4.34 => v4.4.36): Extracting archive
- Upgrading symfony/form (v4.4.34 => v4.4.36): Extracting archive
- Upgrading symfony/doctrine-bridge (v4.4.34 => v4.4.36): Extracting archive
- Upgrading …
```
> [PHP] Update Symfony to 4.4.36

- features/api/scopes.feature
- src/DataFixtures/ORM/LoadScopeData.php
- src/Scope/Generator/PapScopeGenerator.php
- src/Scope/ScopeEnum.php
- tests/Scope/GeneralScopeGeneratorTest.php
```sql
INSERT INTO `scope` (code, name, apps)
VALUES ('pap', 'Porte-à-porteur', 'jemarche')
;
```
> [API][PAP] Add PAP scope

- features/api/pap_campaigns.feature
- migrations/Version20220114104853.php
- src/DataFixtures/ORM/LoadPapAddressData.php
- src/DataFixtures/ORM/LoadPapCampaignData.php
- src/Entity/Pap/Address.php
- src/Repository/Pap/CampaignHistoryRepository.php
```sql
-- Set zones of pap_address
-- Paris arrondissements
INSERT INTO pap_address_zone (address_id, zone_id)
SELECT pap_address.id, geo_zone.id
FROM pap_address, geo_zone 
WHERE geo_zone.code = pap_address.insee_code AND geo_zone.type = 'borough' AND geo_zone.name LIKE 'Paris %'
-- villes hors Paris
INSERT INTO pap_address_zone (address_id, zone_id)
SELECT pap_address.id, geo_zone.id
FROM pap_address, geo_zone 
WHERE geo_zone.code = pap_address.insee_code AND geo_zone.type = 'city' AND geo_zone.name != 'Paris'
-- DPT hors Paris
INSERT INTO pap_address_zone (address_id, zone_id)
SELECT pap_address.id, geo_zone.id
FROM pap_address, geo_zone 
INNER JOIN geo_zone_parent gzp ON geo_zone.id = gzp.parent_id AND geo_zone.type = 'department' AND geo_zone.code != '75'
INNER JOIN …
```
> Change relation between PapAddress and GeoZone to ManyToMany

- src/Entity/MyTeam/Member.php
- src/Entity/MyTeam/MyTeam.php
> Remove temporary is_granted('ROLE_OAUTH_SCOPE_JEMENGAGE_ADMIN') from MyTeam endpoints

- composer.lock
```
- Upgrading composer/package-versions-deprecated (1.11.99.4 => 1.11.99.5): Extracting archive
- Upgrading symfony/flex (v1.17.6 => v1.18.3): Extracting archive
- Upgrading symfony/options-resolver (v4.4.30 => v4.4.37): Extracting archive
- Upgrading symfony/mime (v4.4.36 => v4.4.37): Extracting archive
- Upgrading symfony/http-foundation (v4.4.36 => v4.4.37): Extracting archive
- Upgrading symfony/event-dispatcher (v4.4.34 => v4.4.37): Extracting archive
- Upgrading symfony/var-dumper (v4.4.36 => v4.4.37): Extracting archive
- Upgrading symfony/debug (v4.4.36 => v4.4.37): Extracting archive
- Upgrading symfony/error-handler (v4.4.36 => v4.4.37): Extracting archive
- Upgrading symfony/http-kernel (v4.4.36 => v4.4.37): Extracting archive
- Upgrading symfony/inflector (v4.4.34 => …
```
> [PHP] Update Symfony to 4.4.37

- config/services/admin.xml
- features/api/jecoute_news.feature
- migrations/Version20220217113503.php
- src/Admin/Jecoute/NewsAdmin.php
- src/Controller/Admin/AdminJecouteNewsCRUDController.php
- src/DataFixtures/ORM/LoadJecouteNewsData.php
- src/Entity/Jecoute/News.php
- src/Jecoute/NewsHandler.php
- src/Repository/Jecoute/NewsRepository.php
- src/Validator/Jecoute/NewsText.php
- src/Validator/Jecoute/NewsTextValidator.php
- templates/admin/jecoute/news/action_pin.html.twig
- templates/admin/jecoute/news/edit.html.twig
- templates/admin/layout.html.twig
- translations/validators.fr.yml
```sql
UPDATE jecoute_news 
SET link_label = 'Voir'
WHERE external_link IS NOT NULL
;
```
> [Admin][News] Add 'pinned' and 'enriched' fields and make some other modifications

- src/Repository/ProcurationProxyRepository.php
- src/Repository/ProcurationRequestRepository.php
Reverts EnMarche/en-marche.fr#7029
> Revert "Count other cities when matching proxies"

- package.json
- yarn.lock
Reverts EnMarche/en-marche.fr#7044
> Revert "Bump flatpickr from 4.6.6 to 4.6.11"

- templates/base.html.twig
> Remove unused Mailchimp script

- features/api/membership_avecvous.feature
- src/Entity/Contact.php
Reverts EnMarche/en-marche.fr#7093
> Revert "Disable contact captcha"

- src/Admin/Phoning/CampaignAdmin.php
- src/Api/Listener/PhoningCampaignParticipantsCountUpdateListener.php
- src/Command/PhoningCampaignUpdateParticipantsCountCommand.php
> Update participant count on prod

- features/api/surveys.feature
- src/Api/Filter/JeMengageSurveyScopeFilter.php
> [Surveys][LPN-575] retrieve national surveys with national phoning and pap manager

- features/api/pap_campaigns.feature
- migrations/Version20220401171433.php
- src/Api/Filter/PapVotePlaceScopeFilter.php
- src/DataFixtures/ORM/LoadPapVotePlaceData.php
- src/Entity/EntityIdentityTrait.php
- src/Entity/Pap/Campaign.php
- src/Entity/Pap/CampaignHistory.php
- src/Entity/Pap/VotePlace.php
```sql
UPDATE pap_vote_place vp
INNER JOIN 
(
SELECT pa.vote_place_id, COUNT(pa.id) AS nb, SUM(pa.voters_count) AS voters_count
FROM pap_address pa
GROUP BY pa.vote_place_id
) addr ON addr.vote_place_id = vp.id 
SET 
vp.nb_addresses = addr.nb,
vp.nb_voters = addr.voters_count
;
```
> [API][PAP] Add vote places list endpoint

- templates/banner/call.html.twig
> css tmp fix

- front/style/layout/_base.scss
- migrations/Version20220504182132.php
- src/Admin/AdherentAdmin.php
- src/Admin/ProcurationProxyAdmin.php
- src/Command/ProcessProcurationProxyElectionRoundAvailabilitiesCommand.php
- src/Entity/ProcurationProxy.php
- src/Entity/ProcurationProxyElectionRound.php
- src/Form/Procuration/ProcurationProxyType.php
- src/Procuration/Filter/ProcurationFilters.php
- src/Procuration/Filter/ProcurationProxyProposalFilters.php
- src/Repository/ElectionRoundRepository.php
- src/Repository/ProcurationProxyRepository.php
- src/Repository/ProcurationRequestRepository.php
- src/Repository/ProcurationTrait.php
- templates/procuration/proxy/_available_rounds.html.twig
- templates/procuration_manager/_matching_proxy.html.twig
- templates/procuration_manager/_proposals_list.html.twig
- templates/procuration_manager/associate.html.twig
- templates/procuration_manager/deassociate.html.twig
- templates/procuration_manager/proposal.html.twig
- templates/procuration_manager/proposals.html.twig
- templates/procuration_manager/request.html.twig
- tests/Controller/EnMarche/ProcurationManagerControllerTest.php
- tests/Controller/Procuration/ProcurationControllerTest.php
- tests/Entity/ProcurationProxyTest.php
- tests/Entity/ProcurationRequestTest.php
After merge execute `app:procuration:process-availabilities` command.
> [Procuration] Apply proxies count for every election round and change calculation of availability

- src/DataFixtures/ORM/LoadCmsBlockData.php
- templates/donation/index.html.twig
```
INSERT INTO cms_block (
name,
description,
content,
created_at,
updated_at
)
VALUES
(
'donation-index-header-content',
'Texte affiché dans le header de la page d\'accueil des dons',
'<h1 class="text--larger">
Donnons une majorité au Président de la République les 12 et 19 juin
</h1>',
NOW(),
NOW()
),
(
'donation-index-why-content',
'Texte affiché dans la section "Pourquoi donner?" de la page d\'accueil des dons',
'<h2 class="text--large b__nudge--bottom-larger">Pourquoi faire un don ?</h2>
<p class="text--body">
Grâce aux ressources générées par notre représentation dans la vie politique nationale, 
votre générosité fidèle depuis 2017 et grâce à la bonne gestion de notre Mouvement, 
<b>La République en Marche a financé une grande partie de la campagne présidentielle 
et apporte son …
```
> Make donation index content editable

- composer.lock
```
- Upgrading guzzlehttp/guzzle (7.4.1 => 7.4.3)
```
> Upgrade guzzle/guzzle-http

- features/javascript/donation.feature
- tests/Controller/EnMarche/DonationControllerTest.php
Reverts EnMarche/en-marche.fr#7335
> Revert "[CI] fix donation tests"

- templates/base.html.twig
Reverts EnMarche/en-marche.fr#7406
> Revert "Replace GA by ABLA"

- composer.lock
- Upgrading symfony/flex (v1.19.2 => v1.19.3): Extracting archive
- Upgrading symfony/options-resolver (v4.4.37 => v4.4.44): Extracting archive
- Upgrading symfony/mime (v4.4.43 => v4.4.44): Extracting archive
- Upgrading symfony/http-foundation (v4.4.43 => v4.4.44): Extracting archive
- Upgrading symfony/http-client-contracts (v2.5.1 => v2.5.2): Extracting archive
- Upgrading symfony/event-dispatcher-contracts (v1.1.12 => v1.1.13): Extracting archive
- Upgrading symfony/event-dispatcher (v4.4.42 => v4.4.44): Extracting archive
- Upgrading symfony/var-dumper (v4.4.42 => v4.4.44): Extracting archive
- Upgrading symfony/debug (v4.4.41 => v4.4.44): Extracting archive
- Upgrading symfony/error-handler (v4.4.41 => v4.4.44): Extracting archive
- Upgrading symfony/http-kernel (v4.4.43 => …
> [PHP] update Symfony 4.4.44

- assets/style/components/_donation.scss
- assets/style/mixins/_colors.scss
- tailwind.config.js
Reverts EnMarche/en-marche.fr#7511
> Revert "Change colors"

- config/packages/workflows.yaml
- src/Membership/MembershipRequest/RenaissanceMembershipRequest.php
- templates/renaissance/adhesion/additional_informations.html.twig
- translations/validators.fr.yml
> Enhance validation for additional informations step

- src/Mailchimp/Campaign/Listener/SetCampaignReplyToSubscriber.php
- tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php
Reverts EnMarche/en-marche.fr#7785
> Revert "[LPN-1289][CampaignMessage] update sender email"

- templates/components/_footer.html.twig
Hi,
The "La République Ensemble" link is KO then i propose to remove it.
> Remove "La République Ensemble" link in footer

- src/Committee/CommandHandler/RefreshCommitteeMembershipsInZoneCommandHandler.php
- src/Entity/Geo/Zone.php
Reverts EnMarche/en-marche.fr#8493
> Revert "[Committee] report committee assignation"

- config/services.yaml
- src/Api/Serializer/CommitteeGroupsContextBuilder.php
- src/Entity/Committee.php
- src/Entity/EntityNameSlugTrait.php
Reverts EnMarche/en-marche.fr#8467
> Committee PUT is limited during elections

- .github/actions/build/action.yml
- docker-compose.ci.yml
- docker-compose.override.yml.dist
- docker-compose.yml
Reverts parti-renaissance/espace-adherent#8975
> Revert "[CI] use GH cache for Docker image layers"

- assets/components/ReSelect.js
- assets/components/Validator/index.js
- assets/pages/adhesion_funnel/components/Page.js
- assets/pages/adhesion_funnel/google_places.js
- assets/pages/adhesion_funnel/index.js
- templates/renaissance/adhesion/form.html.twig
- Il y a un inversement des critères entre le nom et le prénom :
- fix ➝ Prénom = 2 caractères ; Nom = 1 caractère
- L'adresse postale m'indique que je suis à la fois dans la ville de Milan et aux Etats-Unis
-  fix ➝ Clear address form at each autocomplete changes
- On me demande de remplir le CP alors que j'ai mis un adresse non française 
- fix ➝  Remove native HTML required attribute when country is not France
> fix: Etape 2 : Ajouter les critères de champs

- src/Admin/Jecoute/NewsAdmin.php
- translations/messages+intl-icu.fr.yml
> Update Jecoute\News label

- config/services/admin.xml
- src/DataFixtures/ORM/LoadAdministratorRoleData.php
post-deploy: 
```
UPDATE administrator_role
SET group_code = 'archives_a_depublier'
WHERE code = 'ROLE_ADMIN_TECH_USER_LIST_DEFINITIONS'
;
```
> [Admin] Archive user list definitions

- src/Command/ImportDonationsCommand.php
> Update donation import command

- src/Entity/ProcurationV2/Request.php
> [Procuration Request] Serialize fromFrance boolean

- features/api/procuration.feature
- migrations/Version20240614123828.php
- src/Admin/Procuration/AbstractProcurationAdmin.php
- src/Admin/Procuration/ProxyAdmin.php
- src/Admin/Procuration/RequestAdmin.php
- src/DataFixtures/ORM/LoadProcurationV2ProxyData.php
- src/DataFixtures/ORM/LoadProcurationV2RequestData.php
- src/Entity/ProcurationV2/AbstractSlot.php
- src/Entity/ProcurationV2/Proxy.php
- src/Entity/ProcurationV2/ProxySlot.php
- src/Entity/ProcurationV2/Request.php
- src/Entity/ProcurationV2/RequestSlot.php
- src/Entity/ProcurationV2/Round.php
- src/Procuration/V2/ProcurationFactory.php
- templates/admin/procuration_v2/_list_proxy_requests.html.twig
- templates/admin/procuration_v2/_list_rounds.html.twig
Reverts parti-renaissance/espace-adherent#10389
> Revert "Revert "[Procurations] Handle slots per round""

- migrations/Version20240623120631.php
- src/Command/RemindProcurationMatchedSlotCommand.php
- src/Entity/ProcurationV2/RequestSlot.php
- src/Entity/ProcurationV2/RequestSlotAction.php
- src/Entity/ProcurationV2/Round.php
- src/Mailer/Message/Procuration/V2/AbstractProcurationMessage.php
- src/Mailer/Message/Procuration/V2/ProcurationMatchReminderMessage.php
- src/Mailer/Message/Procuration/V2/ProcurationRequestMatchedConfirmationMessage.php
- src/Procuration/V2/Command/MatchedRequestSlotReminderCommand.php
- src/Procuration/V2/Handler/MatchedRequestSlotReminderCommandHandler.php
- src/Procuration/V2/ProcurationNotifier.php
- src/Repository/Procuration/RequestSlotRepository.php
- tests/Command/RemindProcurationMatchedSlotCommandTest.php
- tests/Controller/Renaissance/Adhesion/PersistEmailControllerTest.php
- tests/Controller/Renaissance/ValidateEmailControllerTest.php
Fix deprecation notices
Do not serialize matchRemindedAt
> [Procuration] Add match reminder command

- templates/renaissance/adhesion/finish.html.twig
Reverts parti-renaissance/espace-adherent#10913
> Revert "[Readhesion] redirect on profile page"

- features/api/profile.feature
- src/Address/AddressTrait.php
- src/Controller/Api/ProfileController.php
Reverts parti-renaissance/espace-adherent#10912
> Revert "[Api] Users can't update address during votes"
