Makefile, docker-compose.yml, docker/tools/Dockerfile, docker/tools/php.ini, docs/1. Installer le projet en local.md
Démarrer le projet :
```bash
make
```
La commande au-dessus execute toutes celles en-dessous (hormis "watch" et "test").
Builder et lancer docker :
```bash
make boot
```
Installer les dépendances PHP et JS :
```bash
make install
```
Générer les assets :
```bash
make assets
```
Générer les assets en temps réel :
```bash
make watch
```
Lancer le serveur PHP :
```bash
make run
```
Lancer les tests :
```bash
make test
```
=> Added a Makefile and better docker support

app/AppKernel.php, app/config/config_test.yml, app/config/config_test_mysql.yml, app/config/config_test_sqlite.yml, circle.yml, docker-compose.yml, phpunit.xml.dist, src/AppBundle/Donation/PayboxFormFactory.php, tests/AppBundle/Committee/CommitteeManagerTest.php, tests/AppBundle/Controller/AdherentControllerTest.php, tests/AppBundle/Controller/Api/IntlControllerTest.php, tests/AppBundle/Controller/ArticleControllerTest.php, tests/AppBundle/Controller/ControllerTestTrait.php, tests/AppBundle/Controller/DonationControllerTest.php, tests/AppBundle/Controller/EventsControllerTest.php, tests/AppBundle/Controller/HomeControllerTest.php, tests/AppBundle/Controller/InvitationControllerTest.php, tests/AppBundle/Controller/MembershipControllerTest.php, tests/AppBundle/Controller/NewsletterControllerTest.php, tests/AppBundle/Controller/PageControllerTest.php, tests/AppBundle/Controller/Security/AdherentSecurityControllerTest.php, tests/AppBundle/Controller/Security/AdminSecurityControllerTest.php, tests/AppBundle/MysqlWebTestCase.php, tests/AppBundle/Repository/AdherentRepositoryTest.php, tests/AppBundle/Repository/CommitteeMembershipRepositoryTest.php, tests/AppBundle/Repository/CommitteeRepositoryTest.php, tests/AppBundle/SqliteWebTestCase.php, tests/bootstrap.php
This PR introduces two types of WebTestCase: one for SQLite and another for MySQL.
Usage: extends SqliteWebTestCase or MysqlWebTestCase. **Be careful** to use `makeClient` instead of `createClient`.
Example for MySQL:
``` php
<?php
namespace Tests\AppBundle\Controller;
use AppBundle\DataFixtures\ORM\LoadHomeBlockData;
use AppBundle\DataFixtures\ORM\LoadLiveLinkData;
use Symfony\Component\HttpFoundation\Request;
use Tests\AppBundle\MysqlWebTestCase;
class MysqlControllerTest extends MysqlWebTestCase
{
use ControllerTestTrait;
public function testHome()
{
$this->client->request(Request::METHOD_GET, '/');
}
protected function setUp()
{
parent::setUp();
$this->loadFixtures([
LoadHomeBlockData::class,
LoadLiveLinkData::class,
]);
$this->client = $this->makeClient();
}
protected function …
```
=> Add support of MySQL tests

app/config/services/committee.xml, src/AppBundle/Committee/CommitteeFeedHandler.php, src/AppBundle/Controller/AdherentController.php, src/AppBundle/Entity/CommitteeFeedItem.php, src/AppBundle/Mailjet/Message/CommitteeFeedNotificationMessage.php, src/AppBundle/Mailjet/Message/MailjetMessage.php, tests/AppBundle/Committee/CommitteeFeedHandlerTest.php, tests/AppBundle/Controller/CommitteeControllerTest.php, tests/AppBundle/TestHelperTrait.php
Closes [EM-48](http://jira.sensiolabs.net/browse/EM-48).
=> Added email notification for committee subscribers

app/Resources/views/article/article.html.twig, app/Resources/views/page/emmanuel-macron/layout.html.twig, docs/content-styleguide.md, front/style/_content.scss
Un petit compromis puisqu'il n'y a pas de videos ou citations sur ces pages.
=> Fix layout issue on articles + keep fullscreen option for EM pages

src/AppBundle/Asset/GoogleMapsStaticProvider.php
Don't ask me why, but usage of this method in this context produce the error:
```
[2017-02-10 10:57:16] php.CRITICAL: Call to undefined method GuzzleHttp\Exception\ConnectException::getReasonPhrase() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method GuzzleHttp\\Exception\\ConnectException::getReasonPhrase() at /Users/Romain/Developer/en-marche/en-marche/vendor/csa/guzzle-bundle/src/DataCollector/GuzzleCollector.php:105)"} []
```
=> Removes usage of undefined method

app/Resources/views/security/adherent_reset_password.html.twig
When using an invalid password (ie length < 8), the error was not displayed
=> Fixed display of error message

src/AppBundle/Controller/ArticleController.php, tests/AppBundle/Controller/ArticleControllerTest.php
When the number of articles is a multiple of the pagination size, we don't have to perform a query on article to throw a 404
=> Minor perf improvement

app/config/config_test.yml
The test duration is divided by 3 now.
=> Switch to the md5 encoder in test env to speed up tests

app/Resources/views/adherent/list_my_committees.html.twig, app/Resources/views/base.html.twig, app/config/services/platform.xml, src/AppBundle/Collection/CommitteeCollection.php, src/AppBundle/Collection/CommitteeMembershipCollection.php, src/AppBundle/Committee/CommitteeManager.php, src/AppBundle/Committee/Voter/CreateCommitteeVoter.php, src/AppBundle/Committee/Voter/FollowCommitteeVoter.php, src/AppBundle/Committee/Voter/HostCommitteeVoter.php, src/AppBundle/Committee/Voter/PostMessageCommitteeVoter.php, src/AppBundle/Committee/Voter/SuperviseCommitteeVoter.php, src/AppBundle/Entity/Adherent.php, src/AppBundle/Entity/CommitteeMembership.php, src/AppBundle/Event/Voter/HostEventVoter.php, src/AppBundle/Repository/AdherentRepository.php, src/AppBundle/Repository/CommitteeMembershipRepository.php, src/AppBundle/Repository/CommitteeRepository.php, tests/AppBundle/Committee/CommitteeManagerTest.php, tests/AppBundle/Committee/Voter/CreateCommitteeVoterTest.php, tests/AppBundle/Committee/Voter/FollowCommitteeVoterTest.php, tests/AppBundle/Committee/Voter/HostCommitteeVoterTest.php, tests/AppBundle/Committee/Voter/SuperviseCommitteeVoterTest.php, tests/AppBundle/Controller/AdherentControllerTest.php, tests/AppBundle/Controller/Api/CommitteesControllerTest.php, tests/AppBundle/Controller/Api/IntlControllerTest.php, tests/AppBundle/Controller/PageControllerTest.php, tests/AppBundle/Controller/ProcurationManagerControllerTest.php, tests/AppBundle/Controller/Security/AdherentSecurityControllerTest.php, tests/AppBundle/Repository/CommitteeMembershipRepositoryTest.php, tests/AppBundle/Repository/CommitteeRepositoryTest.php
This PR greatly improves the number of SQL queries performed on the frontend side when an adherent is logged in to his\her account. From 21 SQL queries to only 2!
Before
After
The duplicated SQL queries came from two different locations:
1. the adherent's navigation bar in the top right end corner,
2. security voters.
All voters now receive the `CommitteeManager` class that performs SQL queries with Doctrine repositories. This means optimizing can now be done inside the `CommitteeManager` class directly as everything is centralized. The `CommitteeManager` object is now able to check an `Adherent` entity's memberships directly before falling back to repositories to perform SQL queries. This way we can prevent some extra unneeded SQL queries to the database.
Thus, this design also enables …
=> Optimize number of SQL queries whenever possible.

app/Resources/views/procuration/index.html.twig, app/Resources/views/procuration/proposal.html.twig, front/services/voteOffice/VoteOfficeForm.js
The bug was due to `insertBefore` behavior, see http://stackoverflow.com/questions/26863048/javascript-insertbefore-method-cannot-be-called-mulitple-times-adding-same-child
We just want to be sure that the new input is different from the old input.
=> Fixed procuration form's office field

app/Resources/translations/validators.fr.yml, app/migrations/Version20170424164217.php, src/AppBundle/Entity/JeMarcheReport.php, tests/AppBundle/Controller/JeMarcheControllerTest.php
This PR is not really a fix for Sentry issue [258906440](
https://sentry.io/en-marche-i7/en-marchefr/issues/258906440/). This issue is a both a bug and an invalid value. The user tried to store the integer `605,525,601` in a `SIGNED SMALLINT` field. To prevent this situation from happening again in the future, the PR provides the following fixes:
* Make the `not_convinced` SQL field `unsigned` to increase its value from up to `65535` instead of `32767`,
* Add server-side data validation to prevent the user submitting a value greater than `65000` for this field.
=> Fixes Sentry issue #258906440.

docker/dev/nginx.conf, docker/prod/nginx.conf
The EnMarche site delivers woff2-format fonts with an incorrect MIME type. Nginx does not have a MIME type mapping included in its standard `mime.types` file for woff2, so it defaults to `application/octet-stream`, and then relies on the browser to figure out (sniff) what type the content really is. In some browsers (e.g. Safari), this is not a problem, however, other browsers may not allow MIME type sniffing as it is a security risk, and this may cause fonts to be ignored.
Example on the live site:
```
#curl -I https://en-marche.fr/fonts/gillsans-heavy-italic.woff2
HTTP/1.1 200 OK
Date: Tue, 09 May 2017 12:23:38 GMT
Content-Type: application/octet-stream
Content-Length: 48140
...
```
This PR adds the `font/woff2` MIME type (see [WOFF2 spec](https://dev.w3.org/webfonts/WOFF2/spec/#IMT) …
=> Use correct MIME type for woff2 fonts

docker/dev/nginx.conf, docker/prod/nginx.conf
These three headers are pretty much standard issue, and any security scan will flag their absence.
`X-Content-Type-Options` is used to disable content sniffing, telling browsers to believe MIME types in content-type headers and not to try and figure out incorrectly-set types (see #1097). This helps prevent sniffing attacks where content types can be substituted - e.g. Javascript hidden inside GIF images. You need to be sure that your site *is* delivering correct MIME types when you enable this!
`X-XSS-Protection` enables some XSS protection features, particularly in Internet Explorer.
`X-Frame-Options` is used to prevent other sites from presenting the site in a frame, and this can help prevent clickjacking attacks.
There are several other security-related headers that can improve …
=> Add app security headers

src/AppBundle/Repository/EventRepository.php
https://sentry.io/en-marche-i7/stagingen-marchefr/issues/280304039/
```
Tried to index `category` relation which is a `Proxies\__CG__\AppBundle\Entity\EventCategory` instance, which is not recognized as an entity to index.
```
=> Fix Algolia issues with proxies indexing in events

src/AppBundle/Event/EventMessageNotifier.php
Fix https://sentry.io/en-marche-i7/en-marchefr/issues/270440031/
=> Fix EventCanecellationMessage one Adherent recipients is required

front/style/_base.scss, front/style/_colors.scss
FR:
Sur la page d'accueil et d'autres pages, la règle CSS `color` est définie, tandis que la règle `background-color` ne l'est pas.
Cela peut se révéler gênant si le visiteur a modifié les couleurs par défaut de son navigateur (`background-color` et `color`) pour obtenir un thème sombre par exemple (en particulier pour les pages de chargements).
Dans ce cas on obtient une `color` et une `background-color` foncé très proche, rendant le texte difficilement lisible, sans oublier que la charte graphique n'est alors plus respectée :
La solution consiste uniquement à définir les couleurs par défaut au niveau de `body`.
EN:
This is needed when the visitor has changed his default browser `background-color` and `color` rules.
Those are usually `white` and `#333` by default, but some users change …
=> Set the default background and text color in order to make the front page legible on some configuration

src/Admin/EventAdmin.php
We don't need to use a Callback filter for these properties, the TypeGuesser will do the work.
Plus this enables the "advanced search" dropdowns for these two properties (contains, does not contains, equals).
=> Enhance filters on Event Admin

app/config/services/platform.xml, src/CitizenInitiative/CitizenInitiativeRegistrationCommandHandler.php, src/Event/EventRegistrationCommandHandler.php, src/Mailjet/Message/CitizenInitiativeRegistrationConfirmationMessage.php, src/Mailjet/Message/EventRegistrationConfirmationMessage.php, tests/Mailjet/Message/CitizenInitiativeRegistrationConfirmationMessageTest.php, tests/Mailjet/Message/EventRegistrationConfirmationMessageTest.php
MailJet templates must be updated accordingly after this is merged.
1. Mail ID : 118620
=> new parameter {{var:event_link}}
2. Mail ID: 196483
=> new parameter {{var:IC_link}}
=> Send event links to mail templates

src/Committee/CommitteeManagementAuthority.php, src/Committee/CommitteeManager.php, src/Committee/MultipleReferentsFoundException.php, src/Controller/Admin/AdminCommitteeController.php, src/Repository/AdherentRepository.php, tests/Committee/CommitteeManagementAuthorityTest.php, tests/Controller/Admin/AdminCommitteeControllerTest.php, tests/Repository/AdherentRepositoryMysqlTest.php
- a committee can now be managed by more than one referent
- no mail is sent to referents after a committee approval if more than one referent is found
- admins should be notified about this eventual referent conflict
=> Notify if no mail is sent to any referent

circle.yml
=> Disable Xdebug on CircleCI for a faster build

app/config/services/services.xml, src/Algolia/ManualIndexer.php, src/Algolia/ManualIndexerInterface.php, src/Command/AlgoliaSynchronizeCommand.php, src/Command/TimelineImportCommand.php, src/Command/TimelineSynchronizeCommand.php, src/Entity/Timeline/Theme.php, tests/Command/AlgoliaSynchronizeCommandTest.php, tests/Command/ImportReferentBioPictureCommandTest.php, tests/Command/ProcurationSendReminderCommandTest.php, tests/Command/TimelineSynchronizeCommandTest.php, tests/Test/Algolia/DummyIndexer.php, tests/Test/Algolia/DummyManualIndexer.php
1. Command `app:algolia:synchronize` now updates Algolia index settings **if defined**.
2. Introduced the command `app:timeline:synchronize` which synchronizes the entities and index settings related to the Timeline with Algolia.
=> Add Timeline synchronization command

features/registration.feature, src/Entity/CitizenProject.php, src/Entity/Summary.php
The position became optional and it was not reflected on this page
=> Hotfix - user cannot access adherent profile page

composer.lock, src/Controller/EnMarche/MembershipController.php, src/Controller/EnMarche/UserController.php, src/Form/AdherentType.php, src/Membership/MembershipRequest.php
Previously the phone country was set through the object but in some cases
where the code country matches more than 1 country the PhoneNumberType was
not able to choose the right country.
Now, the default phone country is set though the form type which
prevents any weird behavior like this.
=> Bugfix - by default phone country fallback to address country

app/trusted_proxies.php, web/index.php
https://app.clubhouse.io/enmarche/story/2784/l-ip-récupéré-sur-les-failed-login-attempt-les-donations-etc-n-est-pas-bon
=> Add Google IP ranges to trusted proxies

circle.yml
The goal of this PR is run `php-cs-fixer` check just for modified files in `git diff`. Actually this check take 58sec in circle for checking all files of the project.
https://github.com/FriendsOfPhp/PHP-CS-Fixer#using-php-cs-fixer-on-ci
=> Run php-cs-fixer just for modified files

front/style/layout/_base.scss, src/CitizenAction/CitizenActionMessageNotifier.php, src/Form/ContactMembersType.php, src/Mailer/Message/CitizenActionCancellationMessage.php, templates/citizen_action/show.html.twig, templates/citizen_action_manager/contact_participants.html.twig, templates/committee/contact.html.twig, templates/events/contact_members.html.twig
The field `contacts` was deleted from Type class and added directly in template to avoid displaying error message when array of `contacts` passed to controller from previous page and not from page with concerned form.
=> [CA] Change link displaying + add link to mail + fix error message

src/Entity/Projection/ReferentManagedUser.php, src/Twig/AdherentExtension.php
https://app.clubhouse.io/enmarche/story/2949/les-co-al-sont-marqu%C3%A9s-sur-la-plateforme-comme-animateur-dans-le-drop-down-%C3%A7a-fait-confusion
=> Display Co-AL label in the drop-down

templates/user/my_account.html.twig
https://app.clubhouse.io/enmarche/story/3001/la-partie-adherente-depuis-x-devrait-etre-visible-uniquement-si-la-personne-est-adherente
=> [ch3001] Fix display in "my account" for un-adherent

templates/procuration/proposal.html.twig
Without this id:
- the JS breaks
- city input stays hidden
(see https://github.com/EnMarche/en-marche.fr/blob/develop/front/services/vote/VoteLocationForm.js#L65)
=> [Hotfix] Add id to postalCode row

front/style/layout/_nav.scss
Fix little visual bug  on separator.
With some specific user, the separator wasn't visible.
Quick fix by adding a height on border-top.
=> fix visual bug on separator

app/config/config.yml
We misunderstood each other with @ottaviano.
The routing key should be part of the consumer as the bundle has one by default when messages are produced.
=> Mails consumer requires a routing key

.circleci/config.yml
Useless because already configured by docker aliases
=> Remove configure hosts from circleCI config

src/Repository/CommitteeMembershipRepository.php
https://app.clubhouse.io/enmarche/story/4172/bug-dans-l-affichage-des-comit%C3%A9s-en-admin-l-animateur-n-est-pas-le-bon
=> Select SUPERVISOR first and HOST after for committee host members

.circleci/config.yml, scripts/build.sh
Examples:
```
❯ GCLOUD_PROJECT=project CIRCLE_BRANCH=master CIRCLE_TAG=v1.0.0 CIRCLE_SHA1=sha1 scripts/build.sh
DOCKER_IMAGE_TAG       = eu.gcr.io/project/app:v1.0.0-sha1
DOCKER_IMAGE_CACHE_TAG = eu.gcr.io/project/app:master
❯ GCLOUD_PROJECT=project CIRCLE_BRANCH=hotfix-for-something CIRCLE_TAG=v1.0.1 CIRCLE_SHA1=sha1 scripts/build.sh
DOCKER_IMAGE_TAG       = eu.gcr.io/project/app:v1.0.1-sha1
DOCKER_IMAGE_CACHE_TAG = eu.gcr.io/project/app:master
❯ GCLOUD_PROJECT=project CIRCLE_TAG=v1.0.1 CIRCLE_SHA1=sha1 scripts/build.sh
DOCKER_IMAGE_TAG       = eu.gcr.io/project/app:v1.0.1-sha1
DOCKER_IMAGE_CACHE_TAG = eu.gcr.io/project/app:master
❯ GCLOUD_PROJECT=project CIRCLE_BRANCH=master CIRCLE_SHA1=sha1 scripts/build.sh
DOCKER_IMAGE_TAG       = eu.gcr.io/project/app:master-sha1 …
```
=> Add tag based build for deployment to google cloud container

app/config/services/repositories.xml, features/admin/adherent.feature, features/api/adherents.feature, features/bootstrap/FeatureContext.php, src/Controller/Api/AdherentsController.php, src/DataFixtures/ORM/LoadAdherentData.php, src/DataFixtures/ORM/LoadEmailSubscriptionHistoryData.php, src/Entity/Reporting/EmailSubscriptionHistory.php, src/History/EmailSubscriptionHistoryHandler.php, src/Repository/EmailSubscriptionHistoryRepository.php, tests/Controller/Api/StatsControllerTest.php, tests/Controller/EnMarche/AdherentControllerTest.php, tests/Controller/EnMarche/MapControllerTest.php, tests/Repository/AdherentRepositoryMysqlTest.php, tests/Repository/AdherentRepositoryTest.php, tests/TestHelperTrait.php
https://app.clubhouse.io/enmarche/story/3637/1%C3%A8re-partie-section-adh%C3%A9rents-graph-double-histogramme-emails-subscription
Need to change tests to be not time depending.
=> Add an endpoint for emails subscriptions graph by month in referent managed area

Makefile, composer.json, composer.lock, tests/Controller/EnMarche/CitizenActionControllerTest.php, tests/Membership/EventListener/UserSubscriberTest.php
Package operations: 7 installs, 70 updates, 1 removal
- Removing gecko-packages/gecko-php-unit (v3.0)
- Updating ocramius/package-versions (1.2.0 => 1.3.0): Loading from cache
- Updating symfony/polyfill-mbstring (v1.7.0 => v1.8.0): Downloading (100%)
- Updating twig/twig (v2.4.7 => v2.4.8): Downloading (100%)
- Updating symfony/polyfill-php70 (v1.7.0 => v1.8.0): Downloading (100%)
- Updating symfony/polyfill-util (v1.7.0 => v1.8.0): Downloading (100%)
- Updating symfony/polyfill-php56 (v1.7.0 => v1.8.0): Downloading (100%)
- Updating symfony/polyfill-intl-icu (v1.7.0 => v1.8.0): Downloading (100%)
- Updating symfony/symfony (v3.4.8 => v3.4.11): Downloading (100%)
- Updating symfony/polyfill-apcu (v1.6.0 => v1.8.0): Downloading (100%)
- …
=> Composer update

templates/committee/timeline/_event.html.twig
https://app.clubhouse.io/enmarche/story/4275/supprimer-les-param%C3%A8tres-uuid-sur-les-liens-%C3%A9v%C3%A9nements-depuis-les-pages-comit%C3%A9s
=> [ch4275] Remove UUID in the events links

templates/events/_event_header.html.twig
https://app.clubhouse.io/enmarche/story/3208/bug-lors-de-l-ajout-d-un-%C3%A9v%C3%A9nement-%C3%A0-mon-calendrier-j-ai-un-d%C3%A9calage-d-heure
=> Create Google calendar event with the event platform time as it's done for Apple event creation

front/style/pages/_image-generator.scss
https://app.clubhouse.io/enmarche/story/3628/bug-les-couleurs-de-l-outil-de-promotion-d-images-pc-ne-s-affichent-pas-r%C3%A9seaux-sociaux-tract
=> Fix color display for CP media creation

templates/committee/_sidebar.html.twig, templates/events/show.html.twig, tests/Controller/EnMarche/CommitteeControllerTest.php
https://app.clubhouse.io/enmarche/story/4606/supprimer-les-liens-de-contact-pour-les-non-adh%C3%A9rents-sur-les-pages-de-comit%C3%A9s
=> Removed contact link for not connected users on committee page

front/style/layout/_layout.scss, front/style/pages/_citizen-projects.scss, src/DataFixtures/ORM/LoadCitizenProjectData.php, src/Entity/CitizenProject.php, src/Security/Voter/CitizenProject/CreateCitizenProjectVoter.php, templates/admin/adherent/list_status.html.twig, templates/citizen_project/_sidebar.html.twig, templates/citizen_project/edit.html.twig, templates/citizen_project/show_base.html.twig, tests/Controller/EnMarche/AdherentControllerTest.php, tests/Controller/EnMarche/CitizenProjectControllerTest.php, tests/Security/Voter/CitizenProject/CreateCitizenProjectVoterTest.php
Adherent can create an unlimited number of Citizen Projects but only in the case when he has no Citizen Project with pending, pre-approved or pre-refused status.
=> Allow adherent to create an unlimited number of Citizen Projects

app/config/services/admin.xml, app/config/services/services.xml, src/Admin/TurnkeyProjectAdmin.php, src/Entity/TurnkeyProject.php, src/Validator/UniqueTurnkeyProjectPinned.php, src/Validator/UniqueTurnkeyProjectPinnedValidator.php, translations/validators.fr.yml
- Adds custom validator instead of the deprecated `validate` method of Sonata Admin
( see https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/AdminInterface.php#L428 )
- Adds missed translation messages
=> [Turnkey Projects] Added custom validator

templates/javascript.js.twig
Problem : Chart still visible under the tab
Solution 1 : `element.css("visibility", "hidden");` => Big white space under tab
Solution 2 : `element.remove();` => No white space, no more chart
=> [RFR] Remove popup from html after click on accept

src/React/App/IdeasWorkshopApp.php, templates/components/_nav_desktop.html.twig, templates/components/_nav_mobile.html.twig
i confirm we want to:
- hide the links pointing to ideas workshop in the navigation (for now)
- enable the react app of ideas workshop
=> [ADI] Enable in production

app/migrations/Version20190118142342.php
I had to fix the migration because, when executed, a `?` was put as name instead of `LaREM` tag. 
I also fixed the down part, no `label` column exists here. 
Also, as the migration has already been executed on both staging and staging-adi env, I updated direclty the tag name from the admin.
=> [ADI] fix migration

src/Admin/IdeasWorkshopIdeaAdmin.php
When we have a single word like this in a column 
Even with a width limitation on header_style, word is not broke. 
As a workaround and to avoid overriding the `base_list_field.html.twig` template, I used the row style because it's the only param as a style
`<td class="sonata-ba-list-field sonata-ba-list-field-{{ field_description.type }}" objectId="{{ admin.id(object) }}"{% if field_description.options.row_align is defined %} style="text-align:{{ field_description.options.row_align }}"{% endif %}>
`
Result looks like this
=> [ADI] Switch name to title and update css

.circleci/config.yml
Based on `testsuite` branch after phpunit refacto:
same time as before, but we only use 4* containers max now.
how can we reduce the `build` job?
=> Test new config circle

Makefile
This PR adds the `formatted` option for the `doctrine:migration:diff` command.
Doc : https://www.doctrine-project.org/projects/doctrine-migrations/en/2.0/reference/generating-migrations.html#formatted-sql
Before : 
```php
namespace Migrations;
use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
final class Version20190215183542 extends AbstractMigration
{
public function up(Schema $schema): void
{
$this->addSql('CREATE TABLE institutional_event_referent_tag (institutional_event_id INT UNSIGNED NOT NULL, referent_tag_id INT UNSIGNED NOT NULL, INDEX IDX_893A83F2D07A00D (institutional_event_id), INDEX IDX_893A83F29C262DB3 (referent_tag_id), PRIMARY KEY(institutional_event_id, referent_tag_id)) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_unicode_ci ENGINE = InnoDB'); …
```
=> [Makefile] Added formatted option for doctrine:migration:diff

app/config/services/services.xml, src/Admin/AdherentAdmin.php, src/Admin/IdeaDatagrid.php, src/Admin/IdeasWorkshopIdeaAdmin.php, src/Command/NotifyIdeaAuthorAboutContributionsCommand.php, src/Command/NotifyIdeaAuthorCommand.php, src/Controller/Admin/AdminIdeaController.php, src/DataFixtures/ORM/LoadIdeaQuestionData.php, src/Entity/IdeasWorkshop/Idea.php, src/Filter/IdeaStatusFilter.php, src/Normalizer/IdeaNormalizer.php, src/Repository/IdeasWorkshop/IdeaRepository.php, src/Repository/IdeasWorkshop/QuestionRepository.php, src/Validator/MandatoryQuestion.php, src/Validator/MandatoryQuestionValidator.php, tests/Controller/Admin/AdminIdeaControllerTest.php, tests/TestHelperTrait.php, translations/validators.fr.yml
- Add new validator to test if all mandatory questions have been answered
- Move ADI repositories to IdeasWorkshop directory
- Add `QuestionRepository` to have the `enabled` doctrine filter in queries (for question and guideline)
Request from Profiler
```sql
SELECT i0_.id AS id_0, i0_.placeholder AS placeholder_1, i0_.position AS position_2, i0_.category AS category_3, i0_.name AS name_4, i0_.required AS required_5, i0_.enabled AS enabled_6, i0_.guideline_id AS guideline_id_7 FROM ideas_workshop_question i0_ LEFT JOIN ideas_workshop_guideline i1_ ON i0_.guideline_id = i1_.id AND (i1_.enabled = 1) WHERE (i0_.required = 1) AND (i0_.enabled = 1)
```
=> [ADI] Add validation on mandatory questions

app/config/services/services.xml, app/migrations/Version20190304170145.php, features/admin/ideas_workshop_ideas.feature, features/api/ideas_workshop_ideas.feature, src/Admin/IdeasWorkshopIdeaAdmin.php, src/Controller/Admin/AdminIdeaController.php, src/Controller/Api/IdeasWorkshop/IdeaController.php, src/Entity/IdeasWorkshop/Idea.php, src/IdeasWorkshop/Command/SendMailForExtendedIdeaCommand.php, src/IdeasWorkshop/Handler/SendMailForExtendedIdeaHandler.php, src/IdeasWorkshop/Listener/IdeaExtendListener.php, src/Mailer/Message/IdeaExtendMessage.php, templates/admin/ideas_workshop/idea/list_action_extend.html.twig, templates/admin/ideas_workshop/idea/list_extensions.html.twig
Add extend action as `PUT` on the `Idea` class
This action should extends to 10 days a published or finalized idea
Idea will be back as `published` if `finalized`
Admin must be able to do it as many times he wants (no date update, no incrementation) 
An email is send when user extend his idea, but none when admin do it
=> [ADI] Add extend action for ideas

front/app.js, front/pages/procuration_proxy.js, front/pages/procuration_request.js, templates/procuration/profile.html.twig, templates/procuration/proposal.html.twig
This feature add the google autocomplete places on both procuration form (new proxy and new request).
It will hide `address-block` composed with `address`, `city`, `postalCode` and `country`, display an input with `change` event on it, then, if found, fill & show all previous hidden fields. 
I add to removed the form validation process that send a `POST` to `/api/form/validation/{formType}` because both forms are different than the one from donation and registration (new adherent)
=> Add autocomplete on new proxy and request proposal

app/migrations/Version20190227153320.php, features/bootstrap/FeatureContext.php, features/procuration.feature, src/DataFixtures/ORM/LoadProcurationData.php, src/Entity/ProcurationProxy.php, src/Entity/ProcurationRequest.php, src/Form/Procuration/ProcurationRequestType.php, src/Procuration/Filter/ProcurationProxyProposalFilters.php, src/Repository/ProcurationProxyRepository.php, src/Repository/ProcurationRequestRepository.php, templates/admin/procuration/proxy_list_actions.html.twig, templates/procuration/election_rounds.html.twig, templates/procuration/proposal.html.twig, templates/procuration_manager/_matching_election_rounds.html.twig, templates/procuration_manager/_proposals_list.html.twig, templates/procuration_manager/_requests_list.html.twig, templates/procuration_manager/associate.html.twig, templates/procuration_manager/deassociate.html.twig, templates/procuration_manager/proposals.html.twig, templates/procuration_manager/request.html.twig, tests/Controller/EnMarche/ProcurationControllerTest.php, tests/Controller/EnMarche/ProcurationManagerControllerTest.php, tests/Entity/ProcurationProxyTest.php, tests/Entity/ProcurationRequestTest.php, translations/validators.fr.yml
A procuration proxy can now have more than one request associated (OneToOne => OneToMany) based on those two rules :
- A French proxy (voting in France) can receive max one request from France or two requests made in another country or one of each.
- A foreign proxy (voting in another country) can receive one request from France, or one in France and one (or two) from another country, than France or 3 from another chountry than France. 
_You will have all details here (in french) =>_ https://www.service-public.fr/particuliers/vosdroits/F1604
Severals changes on the front
**First, on the new proxy form (`procuration/je-propose`)**
_from #3415 the only thing that changed is the rule saying that a foreign proxy can take 3 requests from another country._
**Second, the request form …
=> Add new column for proxy count

front/pages/procuration_proxy.js, front/pages/procuration_request.js, front/services/form/changeFieldsVisibility.js
1) Fix when user autocomplete address and state is not displayed
2) Add codePostal and State clear to avoid wrong validation logic
=> [Procuration] Fix widget conflict

src/Mailer/Message/AssessorRequestConfirmationMessage.php
Mailjet API does not allow null vars for templates.
=> [Assessor] Fixed nullable var for confirmation message

composer.lock
```
Symfony Security Check Report
=============================
2 packages have known vulnerabilities.
symfony/phpunit-bridge (v3.4.11)
--------------------------------
* [CVE-2019-10912][]: Prevent destructors with side-effects from being unserialized
symfony/symfony (v3.4.25)
-------------------------
* [CVE-2019-10909][]: Escape validation messages in the PHP templating engine
* [CVE-2019-10910][]: Check service IDs are valid
* [CVE-2019-10911][]: Add a separator in the remember me cookie hash
* [CVE-2019-10912][]: Prevent destructors with side-effects from being unserialized
* [CVE-2019-10913][]: Reject invalid HTTP method overrides
[CVE-2019-10912]: https://symfony.com/cve-2019-10912
[CVE-2019-10909]: https://symfony.com/cve-2019-10909
[CVE-2019-10910]: …
```
=> Update symfony/symfony & symfony/phpunit-bridge

behat.yml.dist
This context is useful to debug Behat tests (breakpoint, screenshots, etc)
Example with the `And I put a breakpoint` step :
=> [Behat] Enabled Behatch DebugContext

.circleci/config.yml, behat.yml.dist
When the Behat test suite has failed, a screenshot is uploaded and visible via the "Artifacts" panel : 
Example : https://49724-76485630-gh.circle-artifacts.com/1/screenshots/fail_1561382244_default__I_can_create_a_local_survey%252C_edit_it_and_show_the_statistics_page.png
=> [Behat] Added screenshots artifacts for the CI

app/config/services/services.xml, features/referent_space.feature, features/surveys.feature, migrations/Version20190719115840.php, src/Command/UpdateLocalSurveysTagsCommand.php, src/Controller/EnMarche/Jecoute/AbstractJecouteController.php, src/DataFixtures/ORM/LoadAdherentData.php, src/DataFixtures/ORM/LoadJecouteSurveyData.php, src/Entity/Jecoute/LocalSurvey.php, src/Entity/ReferentManagedArea.php, src/Repository/Jecoute/LocalSurveyRepository.php, src/Security/Voter/SurveyManagedAreaVoter.php, templates/jecoute/_manager_space_layout.html.twig
This PR changes the surveys management behavior.
Now, when a local survey is created, the survey is tagged by area codes.
In the referent space and the jecoute manager space, we can now see and manage all surveys by area codes.
=> [Jecoute] Added surveys visibility by managed areas

src/Intl/FranceCitiesBundle.php
post-deploy:
```
UPDATE procuration_requests
SET vote_city_name = 'Paris 16e'
WHERE vote_city_name = 'Paris 16'
;
UPDATE procuration_proxies
SET vote_city_name = 'Paris 16e'
WHERE vote_city_name = 'Paris 16'
;
UPDATE procuration_managed_areas
SET codes = CONCAT(codes, ',75116')
WHERE FIND_IN_SET('75016', codes) > 0
AND FIND_IN_SET('75116', codes) = 0
;
```
=> Paris 16e is an exception with 2 postalcodes 75016 & 75116

composer.lock
```
Package operations: 0 installs, 53 updates, 0 removals
- Updating symfony/thanks (v1.1.0 => v1.2.5): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
- Updating symfony/asset (v3.4.35 => v3.4.38): Loading from cache
- Updating symfony/polyfill-mbstring (v1.13.1 => v1.14.0): Loading from cache
- Updating symfony/polyfill-ctype (v1.13.1 => v1.14.0): Loading from cache
- Updating symfony/doctrine-bridge (v3.4.35 => v3.4.38): Loading from cache
- Updating symfony/polyfill-php70 (v1.13.1 => v1.14.0): Loading from cache
- Updating …
```
=> Update Sf patch version

migrations/Version20200319132336.php, src/Entity/Election/CityVoteResult.php, src/Entity/Election/VotePlaceResult.php, src/Entity/Election/VoteResultList.php, src/Entity/Election/VoteResultListCollection.php
on database level:
- when deleting a `City`, all related `CityResult` should be delete on cascade
- when deleting a `VotePlace`, all related `VoteResult` should be delete on cascade
- when deleting a `VoteResultListCollection`, all related `VoteResultList` should be delete on cascade
=> Add cascades on election results

config/services/services.xml, elected_representative_migration.sql, src/Admin/ElectedRepresentative/ElectedRepresentativeAdmin.php, src/Command/RestructureElectedRepresentativesRegisterCommand.php, src/Entity/ElectedRepresentative/PoliticalFunctionNameEnum.php
Pour faire la migration : 
1. Exécuter le script SQL, les étapes de 1 à 4 incluses.
2. Exécuter la commande `bin/console app:elected-representative:complete-migration`.
Il y a 3 parties de cette commande : 
- ordonner les mandats (option `--only-mandates`)
- ajouter aux mandats les zones EPCI manquant (option `--only-epci`)
- ajouter aux mandats les zones Communes manquant (option `--only-cities`)
Il est possible d'exécuter chaque partie séparément en ajoutant l'option à la commande.
3. Faire la vérification du résultat de la migration avec l'étape 5 du script SQL.
4. Remettre la structure des tables comme avant avec l'étape 6 du script SQL.
=> Add SQL to migrate data from 'elected_representatives_register' to multiple tables

composer.lock
```
Package operations: 1 install, 44 updates, 0 removals
- Updating symfony/thanks (v1.2.5 => v1.2.7): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
Downloading (100%)
- Updating symfony/asset (v3.4.40 => v3.4.41): Downloading (100%)
- Updating symfony/doctrine-bridge (v3.4.40 => v3.4.41): Downloading (100%)
- Updating symfony/dotenv (v4.4.8 => v4.4.9): Downloading (100%)
- Installing symfony/polyfill-php80 (v1.17.0): Downloading (100%)
- Updating symfony/intl (v4.4.8 => v4.4.9): Downloading (100%)
- Updating symfony/cache (v3.4.40 => v3.4.41): Downloading …
```
=> Update SF from 3.4.40 to 3.4.41

src/Entity/ProcurationProxy.php, tests/Entity/ProcurationRequestTest.php
to execute post-deploy:
```
UPDATE procuration_proxies 
SET french_request_available = 1
WHERE id IN (
SELECT id
FROM (
SELECT
pp.id,
pp.proxies_count,
pp.french_request_available,
pp.foreign_request_available,
COUNT(DISTINCT(mpr.id)) AS matched_requests,
COUNT(DISTINCT(frmpr.id)) AS french_matched_requests,
COUNT(DISTINCT(fompr.id)) AS foreign_matched_requests,
pp.proxies_count - COUNT(DISTINCT(mpr.id)) AS free_slots
FROM procuration_proxies AS pp
INNER JOIN procuration_proxies_to_election_rounds AS pper
ON pper.procuration_proxy_id = pp.id
INNER JOIN election_rounds AS er
ON er.id = pper.election_round_id 
INNER JOIN elections AS e
ON e.id = er.election_id
LEFT JOIN procuration_requests AS mpr
ON mpr.found_proxy_id = pp.id
LEFT JOIN procuration_requests AS frmpr
ON frmpr.found_proxy_id …
```
=> Procuration proxies can now accept up to 2 french requests

front/components/UserListDefinitionWidget.js
Updates:
- if labels list is displayed, hide it clicking on `Ajouter un label`.
- can apply labels modification if any, no more need to wait that all labels have defined status.
=> Change UserListDefinition managing system display

composer.lock
```
❯ dc exec app entrypoint.sh composer update "symfony/*"
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "3.4.*"
Package operations: 0 installs, 40 updates, 0 removals
- Updating symfony/flex (v1.7.1 => v1.8.4): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
- Updating symfony/thanks (v1.2.7 => v1.2.9): Loading from cache
- Updating symfony/asset (v3.4.41 => v3.4.42): Loading from cache
- Updating symfony/doctrine-bridge (v3.4.41 => …
```
=> Update SF from 3.4.41 to 3.4.42

migrations/Version20200825130502.php, src/Entity/Geo/Canton.php, src/Entity/Geo/City.php, src/Entity/Geo/CityCommunity.php, src/Entity/Geo/CollectivityInterface.php, src/Entity/Geo/Country.php, src/Entity/Geo/Department.php, src/Entity/Geo/District.php, src/Entity/Geo/GeoTrait.php, src/Entity/Geo/Region.php
This PR create basis entities for new zone engine.
Tables:
- `geo_country`
- `geo_region`
- `geo_department`
- `geo_canton`
- `geo_district`
- `geo_city_community`
- `geo_city`
- `geo_city_canton`
Relations are declared in acendenting way, because:
- Populating will run in descending: country, then region, and so on
- Flat zones will be catched from the zone node to its parents, and so on
=> French geo entities

composer.lock
```
Prefetching 23 packages 🎶 💨
- Downloading (100%)
Package operations: 0 installs, 39 updates, 0 removals
- Updating symfony/flex (v1.9.1 => v1.9.3): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
- Updating symfony/asset (v3.4.43 => v3.4.44): Loading from cache
- Updating symfony/doctrine-bridge (v3.4.43 => v3.4.44): Loading from cache
- Updating symfony/cache (v3.4.43 => v3.4.44): Loading from cache
- Updating symfony/expression-language (v3.4.43 => v3.4.44): Loading from cache
- Updating symfony/http-foundation (v3.4.43 => v3.4.44): …
```
=> Update SF from 3.4.43 to 3.4.44

composer.lock, symfony.lock
```
❯ dc exec app entrypoint.sh composer update lullabot/amp --with-dependencies
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "3.4.*"
Package operations: 3 installs, 6 updates, 0 removals
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
- Installing ralouphie/getallheaders (3.0.3): Loading from cache
- Updating guzzlehttp/psr7 (1.4.2 => 1.6.1): Loading from cache
- Installing symfony/polyfill-intl-normalizer (v1.18.1): Loading from cache
- Installing …
```
=> [Deps] update lullabot/amp (sabberworm/php-css-parser [CVE-2020-13756])

composer.lock
```
❯ dc exec app entrypoint.sh composer update "symfony/*"
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "3.4.*"
Prefetching 17 packages 🎶 💨
- Downloading (100%)
Package operations: 0 installs, 41 updates, 0 removals
- Updating symfony/flex (v1.9.3 => v1.9.4): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
- Updating symfony/asset (v3.4.44 => v3.4.45): Loading from cache
- Updating symfony/doctrine-bridge (v3.4.44 => v3.4.45): Loading …
```
=> Update SF from 3.4.44 to 3.4.45

migrations/Version20201006102454.php, src/Command/Geo/UpdateCommunitiesCommand.php, src/Entity/Geo/CityCommunity.php, src/Repository/Geo/DepartmentRepository.php
- Update relation between `CityCommunity` and `Department` (from n-1 to n-n)
- Create command `app:geo:update-communities`, source https://www.insee.fr/fr/information/2510634
---
```
bin/console app:geo:update-communities -h
```
```
Usage:
app:geo:update-communities [options]
Options:
--dry-run         Execute the algorithm but will not persist in database.
-h, --help            Display this help message
-q, --quiet           Do not output any message
-V, --version         Display this application version
--ansi            Force ANSI output
--no-ansi         Disable ANSI output
-n, --no-interaction  Do not ask any interactive question
-e, --env=ENV         The Environment name. [default: "dev"]
--no-debug        Switches off debug mode.
-v|vv|vvv, --verbose  Increase the verbosity of …
```
=> Add command to update intercommunalities

src/Command/Geo/UpdateFranceCommand.php
[Geo API] doesn't offer any information about oversea cities' departments.
This PR makes possible linking them to the right department.
[Geo API]: https://geo.api.gouv.fr/
=> Guess department from overseas cities

migrations/Version20201013145634.php, src/Command/Geo/SyncZonesCommand.php, src/Entity/Geo/Country.php, src/Entity/Geo/CustomZone.php, src/Entity/Geo/ForeignDistrict.php, src/Entity/Geo/Zone.php
The "Abroad" level is the parent of "Foreign Districts", therefore "Consular Districts" and "Countries".
This change allows us to group these levels into the FDE one as "Zones" entities.
=> Add FDE level as an entity in the new geo mapping

src/Entity/Geo/Country.php
The foreign district is not always present, so `getParents()` is broken.
This PR fixes it.
=> Fix getParents() in Country

migrations/Version20201014175014.php, src/Entity/ElectedRepresentative/Mandate.php
Geo zones will migrate to a new schema.
This PR allows us to keep both relationships in the `Mandate` entity.
- `zone` already exists and will remain until the complete migration
- `geoZone` points to the new mapping
Once this PR is merged:
1. we can populate the new field with the new corresponding id, then
2. make a new PR to turn the new field as `NOT NULL`
=> Introduce geo zone into mandate entity

migrations/Version20201026115711.php, src/Entity/Geo/Zone.php, src/Entity/ReferentTag.php, src/Repository/ReferentTagRepository.php, src/Repository/TerritorialCouncil/TerritorialCouncilRepository.php
Change the relation between  Zone and ReferentTag from `ManyToOne` to unidirectional `OneToOne`.
Changes:
- Remove ReferentTag reference in Zone entity
- Create a `OneToOne` reference to Zone in ReferentTag entity
- Zone entity is intentionally not aware of its relationship with ReferentTag
- Mark ReferentTag as its repository as deprecated
As consequence, when migrating from ReferentTag to Zone there will be at least one more query to execute, e.g. `TerritorialCouncilRepository::findByMandates()`
---
Note that we need to fill up the new `referent_tags.zone_id` field once it gets deployed.
=> Update relationship between zone and referent tag

src/Entity/Geo/Zone.php, src/Entity/ReferentTag.php, tests/AdherentMessage/Handler/AdherentMessageChangeCommandHandlerTest.php, tests/Deputy/Subscriber/BindAdherentDistrictSubscriberTest.php, tests/Entity/AdherentTest.php, tests/RepublicanSilence/TagExtractor/ReferentTagExtractorTest.php, tests/Security/Voter/ManageUserListDefinitionElectedRepresentativeVoterTest.php
`ReferentTag` has a like-readonly relation with `Geo\Zone`, this PR fix tests that want to create mocked `ReferentTag` allowing injecting `Geo\Zone`.
=> Inject mocked zone in mocked referent tags

src/Command/Geo/SyncZonesCommand.php
Fix `app:geo:sync-zones`, allow it to remove no more existing relation between two zones.
=> Allow to remove a relation parent/child in app:geo:sync-zones command

src/ElectedRepresentative/Filter/ListFilter.php, src/Repository/ElectedRepresentative/ElectedRepresentativeRepository.php, src/Repository/Projection/ManagedUserRepository.php
This PR is an attempt to fix filtering by zones widely in the application.
**The symptom**: when filtering users by managed zones *AND* given zones, there is no match
**The problem**: the application applies the second filter (given zones) over those entities already filtered, as a result, we have only zones linked directly to the given zones, but not their children
**THE FIX** present in this PR: the application discards the "managed zones" if a "given zone" is present, the "managed zone" is taken into account otherwise
**Discarded fix**: apply both at once with `OR` filtering directly in the `JOIN` operation
(there is also a typo fix embedded)
=> Fix filtering by zone

src/Repository/Geo/ZoneRepository.php
This PR allows matching the input `Hauts de` with the text `Hauts-de-France` when searching for the zone widget in the filter form.
=> Permissive Zone name matching

src/Controller/Api/ZoneController.php, src/Form/ElectedRepresentative/ElectedRepresentativeFilterType.php, src/Repository/Geo/ZoneRepository.php
This PR makes the application no longer suggest inactive zones in the zone widget on **adherents' search page**.
Note we keep the widget's behavior on the **elected representatives' search page**.
=> Do not suggest inactive zone

docs/1-Installer-le-projet-en-local.md
Cette commande est peu visible dans le yml et génère une erreur lorsque l'on suit la documentation.
=> Création du réseau avant le make

composer.json, composer.lock, symfony.lock, translations/validators.fr.yml
```
Lock file operations: 0 installs, 51 updates, 1 removal
- Removing symfony/deprecation-contracts (v2.2.0)
- Upgrading symfony/asset (v4.4.18 => v4.4.20)
- Upgrading symfony/browser-kit (v4.4.18 => v4.4.20)
- Upgrading symfony/cache (v4.4.18 => v4.4.21)
- Upgrading symfony/config (v4.4.18 => v4.4.20)
- Upgrading symfony/console (v4.4.18 => v4.4.21)
- Upgrading symfony/css-selector (v3.4.47 => v4.4.20)
- Upgrading symfony/debug (v4.4.18 => v4.4.20)
- Upgrading symfony/debug-bundle (v4.4.18 => v4.4.20)
- Upgrading symfony/dependency-injection (v4.4.18 => v4.4.21)
- Upgrading symfony/doctrine-bridge (v4.4.18 => v4.4.21)
- Upgrading symfony/dom-crawler (v4.4.18 => v4.4.20)
- Upgrading symfony/dotenv (v4.4.18 => v4.4.20)
- Upgrading symfony/error-handler (v4.4.18 => v4.4.21)
- Upgrading …
```
=> [PHP] Update Symfony 4.4.21

composer.lock
```
Package operations: 0 installs, 5 updates, 0 removals
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
- Downloading paragonie/constant_time_encoding (v2.4.0)
- Downloading phpseclib/phpseclib (3.0.7)
- Downloading php-amqplib/php-amqplib (v2.12.3)
- Downloading php-amqplib/rabbitmq-bundle (v1.15.1)
- Upgrading paragonie/random_compat (v9.99.99 => v9.99.100): Extracting archive
- Upgrading paragonie/constant_time_encoding (v2.3.0 => v2.4.0): Extracting archive
- Upgrading phpseclib/phpseclib (2.0.29 => 3.0.7): Extracting archive
- Upgrading …
```
=> [PHP] Update `php-amqplib/rabbitmq-bundle` to 1.15

composer.lock
```
- Upgrading symfony/flex (v1.17.2 => v1.17.5): Extracting archive
- Upgrading symfony/mime (v4.4.31 => v4.4.34): Extracting archive
- Upgrading symfony/http-foundation (v4.4.33 => v4.4.34): Extracting archive
- Upgrading symfony/http-client-contracts (v2.4.0 => v2.5.0): Extracting archive
- Upgrading symfony/event-dispatcher-contracts (v1.1.9 => v1.1.11): Extracting archive
- Upgrading symfony/event-dispatcher (v4.4.30 => v4.4.34): Extracting archive
- Upgrading symfony/var-dumper (v4.4.33 => v4.4.34): Extracting archive
- Upgrading symfony/error-handler (v4.4.30 => v4.4.34): Extracting archive
- Upgrading symfony/http-kernel (v4.4.33 => v4.4.35): Extracting archive
- Upgrading symfony/deprecation-contracts (v2.4.0 => v2.5.0): Extracting archive
- Upgrading symfony/service-contracts …
```
=> [PHP] Update Symfony to 4.4.34

templates/banner/call.html.twig
=> Bandeau procuration fix

src/Entity/ProcurationProxy.php, src/Entity/ProcurationRequest.php
post-deploy :
```
UPDATE procuration_requests
SET vote_city_insee = REPLACE(vote_city_insee, '-', '-0')
WHERE LENGTH(
SUBSTR(
vote_city_insee,
POSITION('-' IN vote_city_insee) + 1,
5
)
) = 4
;
UPDATE procuration_proxies
SET vote_city_insee = REPLACE(vote_city_insee, '-', '-0')
WHERE LENGTH(
SUBSTR(
vote_city_insee,
POSITION('-' IN vote_city_insee) + 1,
5
)
) = 4
;
```
=> Fix insee codes with leading zeros

composer.lock
```
Updating dependencies
Lock file operations: 0 installs, 42 updates, 0 removals
- Upgrading monolog/monolog (2.4.0 => 2.5.0)
- Upgrading symfony/cache (v4.4.40 => v4.4.41)
- Upgrading symfony/cache-contracts (v2.5.0 => v2.5.1)
- Upgrading symfony/config (v4.4.37 => v4.4.41)
- Upgrading symfony/console (v4.4.40 => v4.4.41)
- Upgrading symfony/debug (v4.4.37 => v4.4.41)
- Upgrading symfony/dependency-injection (v4.4.40 => v4.4.41)
- Upgrading symfony/deprecation-contracts (v2.5.0 => v2.5.1)
- Upgrading symfony/doctrine-bridge (v4.4.39 => v4.4.41)
- Upgrading symfony/error-handler (v4.4.40 => v4.4.41)
- Upgrading symfony/event-dispatcher-contracts (v1.1.11 => v1.1.12)
- Upgrading symfony/expression-language (v4.4.40 => v4.4.41)
- Upgrading symfony/finder (v4.4.37 => v4.4.41)
- Upgrading …
```
=> [PHP] Update Symfony 4.4.41

composer.lock
```
- Upgrading symfony/mime (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/http-foundation (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/http-kernel (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/form (v4.4.44 => v4.4.45): Extracting archive
- Upgrading doctrine/collections (1.6.8 => 1.7.2): Extracting archive
- Upgrading symfony/serializer (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/console (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/dom-crawler (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/yaml (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/translation (v4.4.44 => v4.4.45): Extracting archive
- Upgrading symfony/framework-bundle (v4.4.44 => v4.4.45): Extracting archive
- Upgrading …
```
=> [PHP] Update Symfony 4.4.45

composer.lock
Reverts EnMarche/en-marche.fr#8387
=> Revert "Bump coduo/php-matcher from 6.0.11 to 6.0.12"

assets/components/ReSlider.js, assets/pages/adhesion_funnel/components/ReContributionOpt.js, templates/components/Atoms/ReSlider.html.twig, templates/components/Molecules/ReContributionOpt.html.twig
Lorsque je sélectionne la sommes affiché pour en renseigné une de mon choix je commence à60€ et pas 0€.
Ainsi si je sélectionne et je remplis 1453 je vais en réalité taper 601 453 et donc basculer sur la limite haute de 7500€
fix: use onChange, sync value, and auto select field
=> Fix: Étape 4 : Choix formule adhésion
